
<div id="rightColumn">
             	<div class="mainColumnWidget">
                 	<div class="categoryHeader" style="border-top: 1px solid #E2E2E2;">
                       <?php echo $this->Translate('Search')?><?php echo $this->qstring?> 
                    </div>
					
				<form name="frmcatproduct" method="post" id="frmcatproduct">
						<?php if(count($this->records) > 0){?>
						<div class="portlet">
                         <div class="bluewidgetHeader">
                               <div style="float:left">
                                    <select id="sortBy" style="width:150px;" name="sortBy" onchange="this.form.submit();">
 											<option value="bestseller" <?php echo $this->bestseller;?>>Bestseller</option>
											<option value="most_liked" <?php echo $this->most_liked;?>>Most Liked</option>
											<option value="price_asc" <?php echo $this->price_asc;?>>Price: Low to High</option>
											<option value="price_desc" <?php echo $this->price_desc;?>>Price: High to Low</option>
                         			 </select>
                                </div>
                                
                                <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_top.phtml'); ?>
                            	<div style="clear:both;"></div>
                        </div>
                    
                    </div>
					<div class="portlet" style="border-bottom:1px solid #E2E2E2">
				<div class="productListingNav">
				   <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_bottom.phtml'); ?>
				</div>
				<div style="clear:both"></div>
			</div>
						<?php }else{?>
							<div style="font-size:12px;">
								<p>"<?php echo $this->Translate('NoProduct')?>"</p>
							</div>
						<?php }?> 
						<div id="productGridView" class="portlet">
						<?php foreach($this->records as $prodval){?>
							<div class="productGridItem productGridItemTopRow">
								<div class="thumbnailImage" style="margin-top:14px;">
									<a target="_top" href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $prodval['product_id'];?>">
									
									<?php if(!$prodval['image_name']){?>
										<img class="img" src="<?php echo IMAGES_FB_PATH ?>/Default.gif"/>
									<?}else{?>
									
										<img class="img" src="<?php echo $prodval['image_path'] ?>/<?php echo $prodval['image_name'] ?>" width="128"/>
									<?}?>
									</a>
								</div>
								<div class="productTitle">
									<a target="_top" href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $prodval['product_id'];?>"><?php echo $prodval['product_name'];?></a> 
								</div>
								<div class="productPrice">
								   <?php echo "$".$prodval['product_price'];?>
								</div>
								<div class="socialbtn">
									<div class="left">
										<img src="<?php echo IMAGES_FB_PATH ?>/like_1.jpg" alt="" />
									</div>
								   <div style="text-align: right;">
									   <div class="share" id="shareLinkContGrid_lls1">
											<a class="shareLinks" rel="Grid_lls1" href="#">Share</a>
									   </div>
										<div style="clear: both;"></div>
					
									</div>
									<div style="clear: both"></div>
								 </div>    
							 </div>
						  <?php }?>   
						 </div>   
					</div>
					<?php if(count($this->records) > 0){?>
					<div class="portlet">
						<div class="productListingNav">
						   
						<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_bottom.phtml'); ?>
						</div>
						<input type="hidden" name="page_no" id="page_no" value="<?php echo $this->page_no; ?>" />
	
						<div style="padding-bottom:10px; clear:both"></div>
					</div>
					<?php }?>
					
				</form>
                <!--<script type="text/javascript">
					$(document).ready(function(){
						$("#slider1").easySlider({
							auto: false,
							continuous: false,
							nextId: "slidernext",
							prevId: "sliderprev",
							prevText: "",
							nextText: "",
							controlsShow: false
						});
			
						$("#slidernext").show();
						$("#sliderprev").show();
					});
				</script>-->
               
            </div>