
<div id="rightColumn">
<form name="frmcatproduct" method="get" id="frmcatproduct" action="<?php echo $this->temp_url;?>" target="_top" enctype="multipart/form-data">
             	<div class="mainColumnWidget">
                 	<div class="categoryHeader" style="border-top: 1px solid #E2E2E2;">
                       <?php echo $this->Translate('Search')?><?php echo $this->qstring?> 
                    </div>
					
				
						<?php if(count($this->records) > 0){?>
						<div class="portlet">
                         <div class="bluewidgetHeader">
                               <div style="float:left">
                                    <select id="sortBy" style="width:150px;" name="sortBy" onchange="this.form.submit();">
							<option value="bestseller" <?php echo $this->bestseller;?>><?php echo $this->Translate('BestSeller')?></option>
							<option value="most_liked" <?php echo $this->most_liked;?>><?php echo $this->Translate('MostLiked')?></option>
							<option value="price_asc" <?php echo $this->price_asc;?>><?php echo $this->Translate('LowToHigh')?></option>
							<option value="price_desc" <?php echo $this->price_desc;?>><?php echo $this->Translate('HighToLow')?></option>
                         			 </select>
                                </div>
                                
                                <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_top.phtml'); ?>
                            	<div style="clear:both;"></div>
                        </div>
                    
                    </div>
					<div class="portlet" style="border-bottom:1px solid #E2E2E2">
						<div class="productListingNav">
						   <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_bottom.phtml'); ?>
						</div>
						<div style="clear:both"></div>
				 	</div>
						<?php }else{?>
							<div style="font-size:12px; padding: 8px 10px 9px; border-bottom: 1px solid #E2E2E2;">
								<p>"<?php echo $this->Translate('NoProduct')?>"</p>
							</div>
						<?php }?> 
						<div id="productGridView" class="portlet">
						<?php foreach($this->records as $prodval){?>
							<?php 
								if($prodval['ProdName'] != '')
								{
									$prodName = $prodval['ProdName'];
								}else{
									$prodName = $prodval['product_name'];
								}
							?>
							<div class="productGridItem productGridItemTopRow">
								<div class="thumbnailImage" style="margin-top:14px;">
									<a target="_top" href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $prodval['product_id'];?>">
									
									<?php if(!$prodval['image_name']){?>
										<img class="img" src="<?php echo IMAGES_FB_PATH ?>/Default.gif" alt="Default" title="Default"/>
									<?}else{?>
									
										<img class="img" src="<?php echo SITE_PRODUCT_IMAGES_PATH.$prodval['image_path'] ?>/<?php echo $prodval['image_name'] ?>" width="128" alt="<?php echo $prodName;?>" title="<?php echo $prodName;?>"/>
									<?}?>
									</a>
								</div>
								<div class="productTitle">
									<a target="_top" href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $prodval['product_id'];?>"><?php echo $prodName;?></a> 
								</div>
								<div class="productPrice">
								    <?php echo DEFAULT_CURRENCY_SYMBOL. $prodval['Prod_convert_price']."&nbsp;".DEFAULT_CURRENCY_CODE;?>
								</div>
								<div class="socialbtn">
									<script>(function(d, s, id) {
										  var js, fjs = d.getElementsByTagName(s)[0];
										  if (d.getElementById(id)) {return;}
										  js = d.createElement(s); js.id = id;
										  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<?php echo FACEBOOK_APP_API_ID; ?>";
										  fjs.parentNode.insertBefore(js, fjs);
										}(document, 'script', 'facebook-jssdk'));</script>
										<fb:like href="<?php echo SITE_FB_URL . "product/view/id/" . $prodval['product_id']; ?>" send="true" layout="button_count" width="181" show_faces="false"></fb:like>
								   
									<div style="clear: both"></div>
								 </div>    
							 </div>
						  <?php }?>   
						 </div>   
					</div>
					<?php if(count($this->records) > 0){?>
					<div class="portlet">
						<div class="productListingNav">
						   
						<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_bottom.phtml'); ?>
						</div>
						<input type="hidden" name="page_no" id="page_no" value="<?php echo $this->page_no; ?>" />
						<input type="hidden" name="q" id="q" value="<?php echo $this->QueryString; ?>" />
						<input type="hidden" name="search" id="search" value="<?php echo $this->Search; ?>" />
						<input type="hidden" name="cid" id="cid" value="<?php echo $this->CatId; ?>" />
	
						<div style="padding-bottom:10px; clear:both"></div>
					</div>
					<?php }?>
					
				</form>
                <!--<script type="text/javascript">
					$(document).ready(function(){
						$("#slider1").easySlider({
							auto: false,
							continuous: false,
							nextId: "slidernext",
							prevId: "sliderprev",
							prevText: "",
							nextText: "",
							controlsShow: false
						});
			
						$("#slidernext").show();
						$("#sliderprev").show();
					});
				</script>-->
               
            </div>