
<div id="rightColumn">
	<div class="mainColumnWidget">
		<?php if($this->parentcat_id == '0'){?>
			<div id="breadCrumb">
				<ul>
					<li>
						<a target="_top" href="<?php echo SITE_FB_URL;?>">
							<img title="home" alt="home" src="<?php echo IMAGES_FB_PATH ?>/home.png">
						</a>
					</li>
					<li>
						<a target="_top" href="<?php echo SITE_FB_URL;?>category/subcat/id/<?php echo $this->cat_id ?>"><?php echo $this->catname?></a>
					</li>
				</ul>
			</div>
		<?php }else{?>
			<div id="breadCrumb">
				<ul>
					<li>
						<a target="_top" href="<?php echo SITE_FB_URL;?>">
							<img title="home" alt="home" src="<?php echo IMAGES_FB_PATH ?>/home.png">
						</a>
					</li>
					<li>
						<a target="_top" href="<?php echo SITE_FB_URL;?>category/subcat/id/<?php echo $this->parentcat_id ?>"><?php echo $this->parentcat_name?></a>
					</li>
					<li>
						<a target="_top" href="<?php echo SITE_FB_URL;?>category/subcat/id/<?php echo $this->cat_id ?>"><?php echo $this->catname?></a>
					</li>
	
				</ul>
			</div>
		<?php }?>
		<div class="categoryHeader">
			<div class="left">
				<?php echo $this->ProdName;?>
			</div>
			<div class="right" id="prod_price">
				<?php echo DEFAULT_CURRENCY_SYMBOL."&nbsp;".$this->ProdPrice; ?> 
			</div>
			<div class="clear"></div>
		</div>  
		<div class="right" style="width:350px; padding-right: 10px;">
			<div id="bigimg1" style="visibility:visible;display:block;"><img src="<?php echo $this->DefaultImagePath; ?>" border="0" alt="<?php echo $this->ProdName;?>" title="<?php echo $this->ProdName;?>" /></div>
																
			<div class="smallimg_1">
				 <ul>
					<?php echo $this->imageList; ?>
				 </ul>
			  </div>
			<div class="clear"></div>
			<div class="reportmessage" style="text-align: center">
				<!--<a href="#"> Report This Item </a>-->
			</div>
		 </div>  
		<div class="left" style="width:170px; padding-left:10px;">
			<div class="description">
				<div id="pfdesc">
					
					<span style="font-weight:bold;"><?php echo $this->Translate('Weight')?> - </span><?php echo $this->ProdWeight;?>
					<br />
				 
					<span style="font-weight:bold;"><?php echo $this->Translate('Length')?> - </span><?php echo $this->ProdLength;?>
				</div>
			</div>
			<div id="pd_facepile">
				<p><b><?php echo $this->Translate('ShopperLike')?></b></p>
				<div style="clear:both;height:5px;"></div>
					<div id="fb-root"></div>
					<script>(function(d, s, id) {
					  var js, fjs = d.getElementsByTagName(s)[0];
					  if (d.getElementById(id)) {return;}
					  js = d.createElement(s); js.id = id;
					  //js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
					  fjs.parentNode.insertBefore(js, fjs);
					}(document, 'script', 'facebook-jssdk'));</script>
					
					<fb:facepile href="<?php echo SITE_FB_URL . "product/view/id/" . $this->ProdId; ?>" width="170" max_rows="1"></fb:facepile>
			</div>
			<div class="productInfoBox">
				<form id="productForm" name="productForm" method="post" enctype="multipart/form-data" action="<?php echo SITE_FB_URL;?>product/addtocart" >
					<div id="pfitemoptions">
						<table style="width: 100%;">
							<tbody>
								<?php echo $this->OptionCombo;?>
								
								<!--<tr>
									<td><b>How did you hear about us?:</b><br /><input name="itemOption2" id="itemOption2" size="18" class="optionText inputtext" type="text"></td>
								</tr>-->
							</tbody>
						</table>
						<input type="hidden" value="<?php echo $this->totalCombo;?>" name="Opt_Combo" id="Opt_Combo" />
					</div>
					<div id="pfcartbin" style="margin-top:10px;">
						<input type="button" class="add_cartbtn" value="" id="btn" onclick="validateAddToCart()" />
					</div>
						<input id="productId" name="productId" type="hidden" value="<?php echo $this->ProdId;?>"/>
						<input id="productPrice" name="productPrice" type="hidden" value="<?php echo $this->ProdPrice1;?>" />
						<input type="hidden" name="hiddenPrice" id="hiddenPrice" value="0" />
						<input type="hidden" name="DefaultPrice" id="DefaultPrice" value="<?php echo $this->ProdPrice1; ?> " />
						<input type="hidden" name="TotalPrice" id="TotalPrice" value="<?php echo $this->ProdPrice1; ?> " />
						<input type="hidden" name="FbuserId" id="FbuserId" value="<?php echo $this->FB_userid;?>" />
						<input id="product_userId" name="product_userId" type="hidden" value="<?php echo $this->ProdUserId;?>"/>
				</form>
			</div>
			<div id="backgroundPopup"></div>
 		</div>
		<div class="clear"></div>
		<div style="border-top:solid 1px #E2E2E2;background:#F2F2F2; margin-top:10px; padding-bottom:12px;">  
			<div class="left" style="padding-left: 10px;">
				<div class="productInfoBox">
					<div>
						<div id="pfshipto">
							<strong><h3><?php echo $this->Translate('Description')?></h3></strong>
						</div>
						<div id="pfshipmethod">
							<?php echo $this->ProdDesc; ?>
						</div>
					</div>
				</div>
			 </div>
			<div class="clear"></div>
		</div>
		
		<div class="clear"></div>
		
		<div style="border-top:solid 1px #E2E2E2; border-bottom:solid 1px #E2E2E2; background:#F2F2F2; padding-bottom:12px;">  
			<div class="left" style="padding-left: 10px;">
				<div class="productInfoBox">
					<div>
						<!--<div id="pfshipto">
							<strong><?php echo $this->Translate('ShipTo')?></strong>
							<a href="#"><?php echo $this->Translate('WorldWide')?></a>
						</div>-->
						<div style="clear:both;padding-bottom:5px"></div>
						<div id="pfshipmethod">
							<?php echo $this->Translate('ShippingCalculate')?>  
						</div>
					</div>
				</div>
 			 </div>
			<div class="right">
				<div class="productInfoBox">
					<div id="pfseller"><b><?php echo $this->Translate('Seller')?></b> <a  target="_top" href="<?php echo SITE_FB_URL;?>retailer/view/id/<?php echo $this->ProdSellerId;?>" style="color: #3B5998;"><?php echo $this->ProdSeller;?></a></div>
					<div style="clear:both;padding-bottom:5px"></div>
					<div>
						<img class="sellerInfo" src="<?php echo IMAGES_FB_PATH ?>/card_graphic.png" alt="" />
						<a id="btn1" href="javascript:void(0)" style="color: #3B5998;"><?php echo $this->Translate('SellerInfo')?></a>
					</div>
					<div style="clear: both; padding-bottom: 5px;"></div>
					<?php if($this->todaydate > $this->Expiredate){?>
					
					<?php }else{?>   
					<div class="retailerPositiveReviewWidget">
					
						<span class="sellerRatingThumbs "><?php echo $this->Translate('NewSeller')?></span>
					</div> 
					<?php }?>
				</div>
			 </div>
			<div class="clear"></div>
			<div class="socialbtn" style="margin-left:10px; margin-top:0px;">
					<div id="fb-root"></div>
					<script>(function(d, s, id) {
					  var js, fjs = d.getElementsByTagName(s)[0];
					  if (d.getElementById(id)) {return;}
					  js = d.createElement(s); js.id = id;
					  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<?php echo FACEBOOK_APP_API_ID; ?>";
					  fjs.parentNode.insertBefore(js, fjs);
					}(document, 'script', 'facebook-jssdk'));</script>
					<fb:like href="<?php echo SITE_FB_URL . "product/view/id/" . $this->ProdId; ?>" send="true" layout="button_count" width="500" show_faces="false"></fb:like>
					
			</div>
		</div>
		<div style="border-top:solid 1px #E2E2E2; border-bottom:solid 1px #E2E2E2;">
			<div id="fb-root"></div>
			<script>(function(d, s, id) {
			  var js, fjs = d.getElementsByTagName(s)[0];
			  if (d.getElementById(id)) {return;}
			  js = d.createElement(s); js.id = id;
			  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
			  fjs.parentNode.insertBefore(js, fjs);
			}(document, 'script', 'facebook-jssdk'));</script>

			<fb:comments href="<?php echo SITE_FB_URL . "product/view/id/" . $this->ProdId; ?>" num_posts="2" width="550"></fb:comments>
		</div>
	</div>
</div>
<!--<script type="text/javascript">

		$(document).ready(function()
		{
			 $("#popupContactClose").click(function()
			 {
				 disablePopup();
				 $(this).fadeIn(1000000, function() {
						top.location.href = request_url;
												  });
			 });
		});

</script>-->