<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Puvoo</title>
<script type="text/javascript" src="<?php echo JS_PATH ?>/jquery-1.6.2.min.js"></script> 
<script type="text/javascript" src="<?php echo JS_PATH ?>/jquery.validate.js"></script> 

 
</head>

<body>
 <?php echo $this->layout()->content ?>
</body>
</html>
