
<!--<script type="text/javascript" src="<?php echo JS_FB_PATH ?>/jquery.jscrollpane.min.js"></script>-->
    <script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
    </script>

<div id="rightColumn">
	<?php if($this->bannerCnt > 0){?>
   
            <div id="slider" class="theme-default">
                <?php foreach($this->banner as $banner){?>
				<a href="<?php echo $banner['banner_link'];?>" target="_top"><img src="<?php echo SITE_BANNER_IMAGES_PATH ?>/<?php echo $banner['banner_image'];?>" width="547" height="264" alt="Banner"/></a>
				<?php }?>
            </div>
            
	<?php }?>
	<div id="gallery">
		<div id="slides">
			<?php if(count($this->frndslike) > 0){?>
			<div class="slide">
				<?php foreach($this->frndslike as $val2){?>
				
					<?php 
						if($val2['ProdName'] != '')
						{
							$prodName2 = $val2['ProdName'];
						}else{
							$prodName2 = $val2['product_name'];
						}
					?>
					
					<div class="productGridBox_scroll">
						<div class="thumbnailImage" style="margin-top:14px;">
						
					 <?php
						$SmallImg2 = str_replace('img','th1',$val2['image_name']);
						$tinyImage2 = SITE_PRODUCT_IMAGES_PATH.$val2['image_path']."/".$SmallImg2;	
						$ThumbImage2 = SITE_PRODUCT_IMAGES_PATH.$val2['image_path']."/".$val2['image_name'];
					 ?>
							<a url="<?php echo $ThumbImage2;?>" class="preview" style="cursor:pointer" href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $val2['product_id'];?>" target="_top">
								<img class="img" src="<?php echo $tinyImage2;?>" alt="<?php echo $prodName2;?>" title="<?php echo $prodName2;?>" />
							</a>
						</div>
						<div class="productTitle">
							<a href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $val2['product_id'];?>" target="_top"><?php echo $prodName2;?></a>
						</div>
						<div class="productPrice"><?php echo DEFAULT_CURRENCY_SYMBOL.$val2['converted_price']."&nbsp;".DEFAULT_CURRENCY_CODE;?> </div>
					</div>
				<?php }?>
				
			</div>
			<?php }?>
			<div class="slide">
				<?php foreach($this->bestSeller as $val1){?>
					<?php 
						if($val1['ProdName'] != '')
						{
							$prodName1 = $val1['ProdName'];
						}else{
							$prodName1 = $val1['product_name'];
						}
						
 						
					?>
					<div class="productGridBox_scroll">
						<div class="thumbnailImage" style="margin-top:14px;">
						
						 <?php
							$SmallImg = str_replace('img','th1',$val1['image_name']);
							$tinyImage = SITE_PRODUCT_IMAGES_PATH.$val1['image_path']."/".$SmallImg;	
							$ThumbImage = SITE_PRODUCT_IMAGES_PATH.$val1['image_path']."/".$val1['image_name'];
						 ?>
							<a url="<?php echo $ThumbImage;?>" class="preview" style="cursor:pointer" href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $val1['product_id'];?>" target="_top">
								<img class="img" src="<?php echo $tinyImage;?>" alt="<?php echo $prodName1;?>" title="<?php echo $prodName1;?>" />
							</a>
						</div>
						<div class="productTitle">
							<a href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $val1['product_id'];?>" target="_top"><?php echo $prodName1;?></a>
						</div>
						<div class="productPrice"><?php echo DEFAULT_CURRENCY_SYMBOL.$val1['converted_price']."&nbsp;".DEFAULT_CURRENCY_CODE;?> </div>
					</div>
				<?php }?>
		</div>
		
	</div>
		<div id="menu_slide" align="center">
			<ul>
				<?php if(count($this->frndslike) > 0){?>
				<li class="fbar">&nbsp;</li><li class="menuItem" style="padding-left:1px;"><a href=""><?php echo $this->Translate('FrndsLike')?></a></li>
				<?php }?>
				<li class="menuItem"><a href=""><?php echo $this->Translate('BestSeller')?></a></li>
			</ul>
		</div>
	</div>
	<?php if(count($this->frndslike) > 0){?>
 	<div class="mainColumnWidget">
		<div class="widgetHeader">
			<div class="widgetHeaderText"><?php echo $this->Translate('YourFrndsLike')?></div>
			<div style="clear:both;"></div>
		</div>
		<div id="celebritySliderContainer">
			<ul>
				<?php foreach($this->frndslike as $prod){?>
					<?php 
						if($prod['ProdName'] != '')
						{
							$prodName3 = $prod['ProdName'];
						}else{
							$prodName3 = $prod['product_name'];
						}
					?>
					<li>
						<div class="productGridBox">
							<div class="thumbnailImage" style="margin-top:14px;">
						 <?php
							$Img = str_replace('img','th1',$prod['image_name']);
							$tinyImg = SITE_PRODUCT_IMAGES_PATH.$prod['image_path']."/".$Img;	
							$ThumbImg = SITE_PRODUCT_IMAGES_PATH.$prod['image_path']."/".$prod['image_name'];
						 ?>
					
								<a url="<?php echo $ThumbImg;?>" class="preview" style="cursor:pointer" href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $prod['product_id'];?>" target="_top">
									<img class="img" src="<?php echo $tinyImg; ?>" alt="<?php echo $prodName3;?>" title="<?php echo $prodName3;?>" />
								</a>
							</div>
							<div class="productTitle">
								<a href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $prod['product_id'];?>" target="_top"><?php echo $prodName3;?></a>
							</div>
							<div class="productPrice"><?php echo DEFAULT_CURRENCY_SYMBOL.$prod['converted_price']."&nbsp;".DEFAULT_CURRENCY_CODE;?> </div>
						
						</div>
					</li>
				<?php }?>
			</ul>
		</div>
		<div class="clear"></div>
	</div>
	<?php }?>
</div>