
<!--<script type="text/javascript" src="<?php echo JS_FB_PATH ?>/jquery.jscrollpane.min.js"></script>-->
    <script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
    </script>

<div id="rightColumn">
	<?php if($this->bannerCnt > 0){?>
   
            <div id="slider" class="theme-default">
                <?php foreach($this->banner as $banner){?>
				<a href="<?php echo $banner['banner_link'];?>" target="_top"><img src="<?php echo SITE_BANNER_IMAGES_PATH ?>/<?php echo $banner['banner_image'];?>" width="547" height="264" /></a>
				<?php }?>
            </div>
            
	<?php }?>
	<div id="gallery">
		<div id="slides">
			<div class="slide">
				<?php foreach($this->frndslike as $val2){?>
					<div class="productGridBox_scroll">
						<div class="thumbnailImage" style="margin-top:14px;">
						<?php
							$SmallImg2 = explode('_',$val2['image_name']);
							$tinyImage2 = SITE_PRODUCT_IMAGES_PATH.$val2['image_path']."/".$SmallImg2[0]."_th1.jpg";
						?>
							<a href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $val2['product_id'];?>" target="_top">
								<img class="img" src="<?php echo $tinyImage2;?>" alt="" />
							</a>
						</div>
						<div class="productTitle">
							<a href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $val2['product_id'];?>" target="_top"><?php echo $val2['product_name'];?></a>
						</div>
						<div class="productPrice"><?php echo DEFAULT_CURRENCY_SYMBOL.$val2['converted_price']."&nbsp;".DEFAULT_CURRENCY_CODE;?> </div>
					</div>
				<?}?>
				
			</div>
			<div class="slide">
				<?php foreach($this->bestSeller as $val1){?>
				
					<div class="productGridBox_scroll">
						<div class="thumbnailImage" style="margin-top:14px;">
						<?php
							$SmallImg = explode('_',$val1['image_name']);
							$tinyImage = SITE_PRODUCT_IMAGES_PATH.$val1['image_path']."/".$SmallImg[0]."_th1.jpg";
						?>
							<a href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $val1['product_id'];?>" target="_top">
								<img class="img" src="<?php echo $tinyImage;?>" alt="" />
							</a>
						</div>
						<div class="productTitle">
							<a href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $val1['product_id'];?>" target="_top"><?php echo $val1['product_name'];?> </a>
						</div>
						<div class="productPrice"><?php echo DEFAULT_CURRENCY_SYMBOL.$val1['converted_price']."&nbsp;".DEFAULT_CURRENCY_CODE;?> </div>
					</div>
				<?php }?>
		</div>
		
	</div>
		<div id="menu_slide" align="center">
			<ul>
				<li class="fbar">&nbsp;</li><li class="menuItem" style="padding-left:1px;"><a href=""><?php echo $this->Translate('FrndsLike')?></a></li><li class="menuItem"><a href=""><?php echo $this->Translate('BestSeller')?></a></li>
			</ul>
		</div>
	</div>
 	<div class="mainColumnWidget">
		<div class="widgetHeader">
			<div class="widgetHeaderText"><?php echo $this->Translate('YourFrndsLike')?></div>
			<div style="clear:both;"></div>
		</div>
		<div id="celebritySliderContainer">
			<ul>
				<?php foreach($this->frndslike as $prod){?>
					<li>
						<div class="productGridBox">
							<div class="thumbnailImage" style="margin-top:14px;">
								<?php
									$Img = explode('_',$prod['image_name']);
									$tinyImg = SITE_PRODUCT_IMAGES_PATH.$prod['image_path']."/".$Img[0]."_th1.jpg";
					?>
								<a href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $prod['product_id'];?>" target="_top">
									<img class="img" src="<?php echo $tinyImg; ?>" alt="" />
								</a>
							</div>
							<div class="productTitle">
								<a href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $prod['product_id'];?>" target="_top"><?php echo $prod['product_name']; ?></a>
							</div>
							<div class="productPrice"><?php echo DEFAULT_CURRENCY_SYMBOL.$prod['converted_price']."&nbsp;".DEFAULT_CURRENCY_CODE;?> </div>
						
						</div>
					</li>
				<?php }?>
			</ul>
		</div>
		<div class="clear"></div>
	</div>
</div>