
<!--<script type="text/javascript" src="<?php echo JS_FB_PATH ?>/jquery.jscrollpane.min.js"></script>-->
<script type="text/javascript">
						$.noConflict();
						$(window).load(function() {
						  $('#slider').nivoSlider ({
								effect:'fade', 
								slices:15,
								animSpeed:500,
								pauseTime:4000,
								startSlide:0, //Set starting Slide (0 index)
								directionNav:false, //Next & Prev
								directionNavHide:true, //Only show on hover
								controlNav:true, //1,2,3...
								controlNavThumbs:false, //Use thumbnails for Control Nav
								controlNavThumbsFromRel:false, //Use image rel for thumbs
								controlNavThumbsSearch: '.jpg', //Replace this with...
								controlNavThumbsReplace: '_thumb.jpg', //...this in thumb Image src
								keyboardNav:true, //Use left & right arrows
								pauseOnHover:true, //Stop animation while hovering
								manualAdvance:false, //Force manual transitions
								captionOpacity:0.8, //Universal caption opacity
								beforeChange: function(){},
								afterChange: function(){},
								slideshowEnd: function(){}, //Triggers after all slides have been shown
								prevText: 'Prev',
								nextText: 'Next'
						
							});
						});

				</script>

<div id="rightColumn">
	<div class="nivoSlider_wrapper"><div id="slider" class="nivoSlider"><a href="#"><img src="<?php echo IMAGES_FB_PATH ?>/banner_slider_01.jpg" alt="Banner11 for slider" title=" Banner11 for slider " width="547" height="264" /></a><a href="#" ><img src="<?php echo IMAGES_FB_PATH ?>/banner_slider_02.jpg" alt="Banner12 for slider" title=" Banner12 for slider " width="547" height="264" /></a><a href="#"><img src="<?php echo IMAGES_FB_PATH ?>/banner_slider_03.jpg" alt="Banner13 for slider" title=" Banner13 for slider " width="547" height="264" /></a></div></div>
	<div id="gallery">
		<div id="slides">
			<div class="slide">
				<div class="productGridBox_scroll">
					<div class="thumbnailImage" style="margin-top:14px;">
						<a href="#" target="_top">
							<img class="img" src="<?php echo IMAGES_FB_PATH ?>/prod1.jpg" alt="" />
						</a>
					</div>
					<div class="productTitle">
						<a href="#" target="_top">Limited Edition double </a>
					</div>
					<div class="productPrice"> $20.00 (USD) </div>
				</div>
				<div class="productGridBox_scroll">
					<div class="thumbnailImage" style="margin-top:14px;">
						<a href="#" target="_top">
							<img class="img" src="<?php echo IMAGES_FB_PATH ?>/prod2.jpg" alt="" />
						</a>
					</div>
					<div class="productTitle">
						<a href="#" target="_top">Limited Edition double </a>
					</div>
					<div class="productPrice"> $20.00 (USD) </div>
				</div>
				<div class="productGridBox_scroll">
					<div class="thumbnailImage" style="margin-top:14px;">
						<a href="#" target="_top">
							<img class="img" src="<?php echo IMAGES_FB_PATH ?>/prod3.jpg" alt="" />
						</a>
					</div>
					<div class="productTitle">
						<a href="#" target="_top">Limited Edition double </a>
					</div>
					<div class="productPrice"> $20.00 (USD) </div>
				</div>
				
			</div>
			<div class="slide">
				<div class="productGridBox_scroll">
					<div class="thumbnailImage" style="margin-top:14px;">
						<a href="#" target="_top">
							<img class="img" src="<?php echo IMAGES_FB_PATH ?>/prod3.jpg" alt="" />
						</a>
					</div>
					<div class="productTitle">
						<a href="#" target="_top">Limited Edition double </a>
					</div>
					<div class="productPrice"> $20.00 (USD) </div>
				</div>
				<div class="productGridBox_scroll">
					<div class="thumbnailImage" style="margin-top:14px;">
						<a href="#" target="_top">
							<img class="img" src="<?php echo IMAGES_FB_PATH ?>/prod2.jpg" alt="" />
						</a>
					</div>
					<div class="productTitle">
						<a href="#" target="_top">Limited Edition double </a>
					</div>
					<div class="productPrice"> $20.00 (USD) </div>
				</div>
				<div class="productGridBox_scroll rightborder">
					<div class="thumbnailImage" style="margin-top:14px;">
						<a href="#" target="_top">
							<img class="img" src="<?php echo IMAGES_FB_PATH ?>/prod1.jpg" alt="" />
						</a>
					</div>
					<div class="productTitle">
						<a href="#" target="_top">Limited Edition double </a>
					</div>
					<div class="productPrice"> $20.00 (USD) </div>
				</div>
			</div>
			
		</div>
	
		<div id="menu_slide" align="center">
			<ul>
				<li class="fbar">&nbsp;</li><li class="menuItem" style="padding-left:1px;"><a href="">Friend's Like</a></li><li class="menuItem"><a href="">Best Sellers</a></li>
			</ul>
		</div>
	</div>
 	<div class="mainColumnWidget">
                    <div class="widgetHeader">
                    	<div class="widgetHeaderText">Your Friends Like</div>
                   		<div style="clear:both;"></div>
                   	</div>
                    <div id="celebritySliderContainer">
                    	<ul>
                        	<li>
                            	<div class="productGridBox leftbordernone">
                                    <div class="thumbnailImage" style="margin-top:14px;">
                                        <a href="#" target="_top">
                                            <img class="img" src="<?php echo IMAGES_FB_PATH ?>/c58faa54e4c3de95ac413a2cf96d7b293d5de8f6_med.jpg" alt="" />
                                        </a>
                                    </div>
                                    <div class="productTitle">
                                        <a href="#" target="_top">Limited Edition double disc Collectors DVD of The Perfect House</a>
                                    </div>
                                    <div class="productPrice"> $20.00 (USD) </div>
                                </div>
                            </li>
                            <li>
                            	<div class="productGridBox">
                                    <div class="thumbnailImage" style="margin-top:14px;">
                                        <a href="#" target="_top">
                                            <img class="img" src="<?php echo IMAGES_FB_PATH ?>/c58faa54e4c3de95ac413a2cf96d7b293d5de8f6_med.jpg" alt="" />
                                        </a>
                                    </div>
                                    <div class="productTitle">
                                        <a href="#" target="_top">Limited Edition double disc Collectors DVD</a>
                                    </div>
                                    <div class="productPrice"> $20.00 (USD) </div>
                                </div>
                            </li>
                            <li>
                            	<div class="productGridBox">
                                    <div class="thumbnailImage" style="margin-top:14px;">
                                        <a href="#" target="_top">
                                            <img class="img" src="<?php echo IMAGES_FB_PATH ?>/c58faa54e4c3de95ac413a2cf96d7b293d5de8f6_med.jpg" alt="" />
                                        </a>
                                    </div>
                                    <div class="productTitle">
                                        <a href="#" target="_top">Limited Edition double </a>
                                    </div>
                                    <div class="productPrice"> $20.00 (USD) </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="clear"></div>
                </div>
				
<!--<script type="text/javascript" id="sourcecode">
		
		    var serrings = new Array();
			    serrings["horizontalDragMinWidth"] = 250;
				serrings["horizontalDragMaxWidth"] = 250;
			
			/*$('a[rel="lightbox"]').lightBox({
			   fixedNavigation: true
			}); 
			 
			function make_search(form) 
			{
			   if(  form.q.value.length < 3 )
			   {
			       alert('Simbols have to be  3 or more!');
				   return false;
			   }
					   	
			   form.action = form.action + '&q=' + form.q.value;
			}
*/
			
			$(function()
			{
				$('.scroll-pane').jScrollPane(serrings);			
			});	
             
			 
			
		</script>-->		

</div>