<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="#"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Weight'); ?></span></li>
	</ul>
</div>


<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate('Manage_Weight'); ?>
	</div>
	
	<div >
		<?php echo $this->addErrorMessage; ?>
	</div>
	
	<form method="post" name="add_form" id="add_form" >
		<table class="Panel" style="margin-top:10px;">
			<tr>
				<td class="Heading2" colspan="2"><?php echo $this->Translate('Add_Weight'); ?></td>
			</tr>
			<tr>
				<td colspan="2">
				<div id="div0" style="padding-bottom:5px">
					<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Weight_Unit_Name'); ?>
							</td>
							<td>
								<input type="text" name="weight_unit_name" id="weight_unit_name" class="Field250" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Weight_Unit_Key'); ?>
							</td>
							<td>
								<input type="text" name="weight_unit_key" id="weight_unit_key" class="Field250" />
								<span></span>
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						<tr>
						   	<td colspan="2">
								<input type="submit" id="anything" onclick="Javascript: return ValidateAddFrom()"  value="<?php echo $this->Translate('Submit'); ?>" />
								<input type="button" id="anything"  value="<?php echo $this->Translate('Cancle'); ?>" onclick="window.location='<?php echo $this->site_url; ?>'"/>
						   </td>
						</tr>
					</table>
				</div>
				</td>
			</tr>
		</table>   
	</form>            
</div> 

<!--     JS Global Variable for the language    -->

<script language="javascript" type="text/javascript">
var siteurl = '<?php echo SITE_URL; ?>';
var ERR_WEIGHT_UNIT_NAME = '<?php echo $this->Translate("Err_Weight_Unit_Name"); ?>';  
var ERR_WEIGHT_UNIT_KEY = '<?php echo $this->Translate("Err_Weight_Unit_Key"); ?>';  
</script>