<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="#"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Currency'); ?></span></li>
	</ul>
</div>



<div class="BodyContainer DashboardContainer" style="text-align:left;">
	
	
	<!--  Page Header Start  -->
	<div class="Heading1" >
		<?php echo $this->Translate('Manage_Currency'); ?>
	</div>
	<!--  Page Header End  -->
	
	<div style="text-align:center">
		<?php echo $this->Admin_Message; ?>
	</div>
	
	
	<!--   Main Form start     -->
	<form name="frmCurrency" id="frmCurrency" method="post">
	
		<!--  Buttons start -->
		<div>
			<div style="float:left; margin-top:7px; margin-bottom:10px;">
				<input type="button" id="search" show='1'  value="<?php echo $this->Translate('Search'); ?>" />
			</div>
			<div id="button" style="float:right;">
				<input type="button" id="anything"  value="<?php echo $this->Translate('Add_New'); ?>" onclick="window.location='<?php echo $this->add_action; ?>'"/>
				<input type="button" id="anything" onclick="Javascript: deleteAllRecords('frmCurrency','<?php echo $this->delete_all_action; ?>')"  value="<?php echo $this->Translate('M_Delete'); ?>"/>	   
				<select name="pagesize" id="pagesize" onchange="this.form.submit();">
					<?php
						foreach($this->arr_pagesize as $key => $val){
							echo "<option value='".$key."'". ($key == $this->pagesize ? ' selected ' : '') ." >" . $val . "</option>";
						}
					?>
				</select>
			</div>
		</div>
		<!--  Buttons end -->
	
		<!--  Search Form start     -->
		<div class="toggler box" style="clear:both; ">
			<div id="effect" class='ui-widget-content ui-corner-all' > 					  
				<div style="padding:20px;">	
					<table class="" width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Currency_Name'); ?>:
							</td>
							<td>
								<input type="text" class="Field250" name="currency_name" class="inputtext" /> 
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Currency_Code'); ?>:
							</td>
							<td>
								<input type="text" class="Field250" name="currency_code" class="inputtext" /> 
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Currency_Symbol'); ?>:
							</td>
							<td>
								<input type="text" class="Field250" name="currency_symbol" class="inputtext" /> 
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Currency_Value'); ?>:
							</td>
							<td>
								<input type="text" class="Field250" name="currency_value" class="inputtext" /> 
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						<tr>
						   <td colspan="2">
								<input type="button" id="anything"  onclick="Javascript: SearchRecords(1,'frmCurrency');"  value="<?php echo $this->Translate('Search'); ?>" />
								<input type="button" id="anything"  onclick="Javascript: SearchRecords(0,'frmCurrency');"  value="<?php echo $this->Translate('Clear'); ?>" />
						   </td>
						</tr>
					</table>
				</div>								
			</div>
		</div>
		<!--  Search Form end     -->
	 
		<div class="Clear"></div>				
 	
		<!--   Records list start   -->
		<div style="margin-top:-10px;" id="table1">		
			<table width="100%" cellpadding="0" cellspacing="0" style="float:left;">
				<tr class="trclass1">
					<td width="5%" class="tdclasshome" style="text-align:left; padding-left:15px;" ><?php echo $this->Translate('All'); ?></td>
					<td width="30%" align="center" class="tdclasshome"><?php echo $this->Translate('Currency_Name'); ?></td>
					<td width="10%" align="center" class="tdclasshome"><?php echo $this->Translate('Currency_Code'); ?></td>
					<td width="10%" align="center" class="tdclasshome"><?php echo $this->Translate('Currency_Symbol'); ?></td>
					<td width="20%" align="center" class="tdclasshome"><?php echo $this->Translate('Currency_Value'); ?></td>
					<td width="10%" align="center" class="tdclasshome bordernone"><?php echo $this->Translate('Actions'); ?></td>
				</tr>	
	<?php 
				if(count($this->records) > 0) 	{ 
				
					for($i = 0; $i < count($this->records); $i++)
					{
	?>
				<tr id="tr100" class="GridRow" onmouseover="this.className='GridRowOver'" onmouseout="this.className='GridRow'">
					<td class="FieldLabel2" style="padding-left:15px;" ><input type="checkbox" name="id[]" id="id[]" value="<?php echo $this->records[$i]['currency_id']; ?>"></td>
					  
					<td class="FieldLabel2" align="center"><?php echo $this->records[$i]['currency_name']; ?></td>
					
					<td class="FieldLabel2" align="center"><?php echo $this->records[$i]['currency_code']; ?></td>
					
					<td class="FieldLabel2" align="center"><?php echo $this->records[$i]['currency_symbol']; ?></td>
					
					<td class="FieldLabel2" align="center"><?php echo $this->records[$i]['currency_value']; ?></td>
					
					<td class="FieldLabel2" align="center">
						<ul id="icons" class="ui-widget ui-helper-clearfix" >
							<li class="ui-state-default ui-corner-all" onclick="Javascript: editRecord(<?php echo $this->records[$i]['currency_id']; ?>,'frmCurrency','<?php echo $this->edit_action; ?>')" title="<?php echo $this->Translate('Edit'); ?>">
								<span class="ui-icon ui-icon-pencil"></span>
							</li>
							<li onclick="Javascript: deleteRecord(<?php echo $this->records[$i]['currency_id']; ?>,'frmCurrency','<?php echo $this->delete_action; ?>')" class="ui-state-default ui-corner-all" title="<?php echo $this->Translate('Delete'); ?>">
								<span class="ui-icon ui-icon-close"></span>
							</li>
						</ul>
					</td>
				</tr>
	<?php 		}
			}	
			else {  	?>
				<tr id="tr100" class="GridRow" onmouseover="this.className='GridRowOver'" onmouseout="this.className='GridRow'">
					<td class="FieldLabel2" colspan="5" align="center"><?php echo $this->Translate('No_record'); ?></td>
				</tr>
	<?php 		 } 		?>				
			
			</table>
			
			
			
			<!--  Pagination start  	 -->
			<div class="box-footer" style="background:none; border:none; float:right; margin-top:10px;">
					<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>					
			</div>
			<!--  Pagination end 		 -->
				
			<!-- 	Hidden field	-->
			<input type="hidden" name="page_no" id="page_no" value="<?php echo $this->page_no; ?>" />
			<input type="hidden" name="is_search" id="is_search" value="<?php echo $this->user_status; ?>" />
			<input type="hidden" name="hidden_primary_id" id="hidden_primary_id" value="" />

		</div>
		<!--   Records list end   -->
	
	</form>
	<!--   Main Form end   -->
	
 	<div class="Clear"></div>	              
</div>

<!--     JS Global Variable for the language    -->

<script language="javascript" type="text/javascript">
	var siteurl = '<?php echo SITE_URL; ?>';
	var HIDE = '<?php echo $this->Translate("Hide"); ?>';  
	var SEARCH = '<?php echo $this->Translate("Search"); ?>';  
	var ERR_CATEGORY_NAME = '<?php echo $this->Translate("Err_Category_Name"); ?>';  
	var ERR_CATEGORY_CODE = '<?php echo $this->Translate("Err_Category_Code"); ?>';  
	var ERR_CATEGORY_SYMBOL = '<?php echo $this->Translate("Err_Category_Symbol"); ?>';  
	var ERR_CATEGORY_VALUE = '<?php echo $this->Translate("Err_Category_Value"); ?>'; 
</script>

<!--     Dialoag box for the delete and delete all    -->

<div id="dialog-confirm" title="<?php echo $this->Translate('Confirm_Delete_Title'); ?>" style="display:none;">
	<div style="text-align:left;">
		<span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
		<?php echo $this->Translate('Confirm_Delete_Currency'); ?>
	</div>
</div>

<div id="dialog-confirm2" title="<?php echo $this->Translate('Confirm_Delete_Title'); ?>" style="display:none;">
	<div style="text-align:left;">
		<span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
		<?php echo $this->Translate('Confirm_M_Delete_Currency'); ?>
	</div>
</div>