<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="<?php echo SITE_URL; ?>admin/"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last1"><a href="<?php echo SITE_URL; ?>admin/currency"><?php echo $this->Translate('Currency'); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Update_Currency'); ?></span></li>
	</ul>
</div>


<div class="BodyContainer DashboardContainer" style="text-align:left;">

	<!--  Page Header Start  -->
	<div class="Heading1" >
		<?php echo $this->Translate('Manage_Currency'); ?>
	</div>
	<!--  Page Header End  -->
	
	<?php if(count($this->editErrorMessage) > 0 ) { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
				<?php foreach($this->editErrorMessage as $key => $val ) { ?>
					<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
					<strong><?php echo $val; ?></strong></p>
				<?php } ?>
			</div>
		</div>
	<?php } ?>	
	
	
	<!--   Main Form start     -->
	<form name="frmCurrency" id="frmCurrency" method="post">
		
 	
		<!--   Records list start   -->
		<div style="margin-top:10px;" id="table1">		
			<table width="100%" cellpadding="0" cellspacing="0" style="float:left;">
				<tr class="trclass1">
					<td width="30%" align="center" class="tdclasshome"><?php echo $this->Translate('Currency_Name'); ?></td>
					<td width="10%" align="center" class="tdclasshome"><?php echo $this->Translate('Currency_Code'); ?></td>
					<td width="10%" align="center" class="tdclasshome"><?php echo $this->Translate('Currency_Symbol'); ?></td>
					<td width="20%" align="center" class="tdclasshome"><?php echo $this->Translate('Currency_Value'); ?></td>
				</tr>	
	<?php 
				if(count($this->records) > 0) 	{ 
				
					for($i = 0; $i < count($this->records); $i++)
					{
	?>
				<tr id="tr100" class="GridRow" onmouseover="this.className='GridRowOver'" onmouseout="this.className='GridRow'">
					
					<td class="FieldLabel2" align="center"><input type="text" name="currency_name_<?php echo $i ?>" id="currency_name_<?php echo $i ?>" class="Field150" value="<?php echo $this->records[$i]['currency_name']; ?>" /><input type="hidden" name="currency_id_<?php echo $i ?>" value="<?php echo $this->records[$i]['currency_id']; ?>" /></td>
					
					<td class="FieldLabel2" align="center"><input type="text" name="currency_code_<?php echo $i ?>" id="currency_code_<?php echo $i ?>" class="Field150" value="<?php echo $this->records[$i]['currency_code']; ?>" maxlength="3" /></td>
					
					<td class="FieldLabel2" align="center"><input type="text" name="currency_symbol_<?php echo $i ?>" id="currency_symbol_<?php echo $i ?>" class="Field150" value="<?php echo $this->records[$i]['currency_symbol']; ?>" maxlength="1" /></td>
					
					<td class="FieldLabel2" align="center"><input type="text" name="currency_value_<?php echo $i ?>" id="currency_value_<?php echo $i ?>" class="Field150" value="<?php echo $this->records[$i]['currency_value']; ?>" /></td>
					
				</tr>
	<?php 		} ?>
				
				<tr><td colspan="4">&nbsp;</td></tr>
				<tr>
					<td colspan="4">
						<input type="submit" id="anything"  value="<?php echo $this->Translate('Submit'); ?>" />
						<input type="button" id="anything"  value="<?php echo $this->Translate('Cancle'); ?>" onclick="window.location='<?php echo $this->site_url; ?>'"/>
				   </td>
				</tr>
	<?php		}	
			else {  	?>
				<tr id="tr100" class="GridRow" onmouseover="this.className='GridRowOver'" onmouseout="this.className='GridRow'">
					<td class="FieldLabel2" colspan="5" align="center"><?php echo $this->Translate('No_record'); ?></td>
				</tr>
	<?php 		 } 		?>				
			
			</table>
			
		</div>
		<!--   Records list end   -->
		<input type="hidden" name="total_records" id="total_records" value="<?php echo count($this->records); ?>" />
	</form>
	<!--   Main Form end   -->
	
 	<div class="Clear"></div>	              
</div>

<!--     JS Global Variable for the language    -->

<script language="javascript" type="text/javascript">
	var siteurl = '<?php echo SITE_URL; ?>';
</script>

