<div id="rightColumn">
                    <div class="mainColumnWidget" style="border-bottom:1px solid #e2e2e2;">
                        <div id="breadCrumb">
                            <ul>
                                <li>
                                    <a target="_top" href="<?php echo SITE_FB_URL ?>index">
                                        <img title="home" alt="home" src="<?php echo IMAGES_FB_PATH ?>/home.png">
                                    </a>
                                </li>
                                <li>
                                    <a target="_top" href="<?php echo SITE_FB_URL ?>page/aboutus/">About Puvoo</a>
                                </li>
                            </ul>
                        </div>
                        <div class="portlet">
                             <div class="bluewidgetHeader">
                                   About Puvoo
                            </div>
                        </div>
                        <div class="content">
                            <p>
                                Shopping Mall is your place on Facebook to grab exclusive deals on top brand merchandise. Share what you like with friends and shop from the over 50,000 merchants selling on Facebook. Shopping Mall is powered by puvoo, Facebook's #1 e-commerce provider. 
                            </p>
                            <p>
                                Shopping Mall is your place on Facebook to grab exclusive deals on top brand merchandise. Share what you like with friends and shop from the over 50,000 merchants selling on Facebook. Shopping Mall is powered by puvoo, Facebook's #1 e-commerce provider. 
                            </p>
                            <p>
                                Shopping Mall is your place on Facebook to grab exclusive deals on top brand merchandise. Share what you like with friends and shop from the over 50,000 merchants selling on Facebook. Shopping Mall is powered by puvoo, Facebook's #1 e-commerce provider. 
                            </p>
                            <p>
                                Shopping Mall is your place on Facebook to grab exclusive deals on top brand merchandise. Share what you like with friends and shop from the over 50,000 merchants selling on Facebook. Shopping Mall is powered by puvoo, Facebook's #1 e-commerce provider. 
                            </p>
                            <p>
                                Shopping Mall is your place on Facebook to grab exclusive deals on top brand merchandise. Share what you like with friends and shop from the over 50,000 merchants selling on Facebook. Shopping Mall is powered by puvoo, Facebook's #1 e-commerce provider. 
                            </p>
                            <p>
                                Shopping Mall is your place on Facebook to grab exclusive deals on top brand merchandise. Share what you like with friends and shop from the over 50,000 merchants selling on Facebook. Shopping Mall is powered by puvoo, Facebook's #1 e-commerce provider. 
                            </p>
                            <p>
                                Shopping Mall is your place on Facebook to grab exclusive deals on top brand merchandise. Share what you like with friends and shop from the over 50,000 merchants selling on Facebook. Shopping Mall is powered by puvoo, Facebook's #1 e-commerce provider. 
                            </p>
                            <p>
                                Shopping Mall is your place on Facebook to grab exclusive deals on top brand merchandise. Share what you like with friends and shop from the over 50,000 merchants selling on Facebook. Shopping Mall is powered by puvoo, Facebook's #1 e-commerce provider. 
                            </p>
                            <p>
                                Shopping Mall is your place on Facebook to grab exclusive deals on top brand merchandise. Share what you like with friends and shop from the over 50,000 merchants selling on Facebook. 
                            </p>
                            <p>
                                Shopping Mall is your place on Facebook to grab exclusive deals on top brand merchandise. Share what you like with friends and shop from the over 50,000 merchants selling on Facebook. Shopping Mall is powered by puvoo, Facebook's #1 e-commerce provider. 
                            </p>
                           
                        </div>
                    </div>
                    
                   
                </div>