<div id="rightColumn">
                    <div class="mainColumnWidget" style="border-bottom:1px solid #e2e2e2;">
                        <div id="breadCrumb">
                            <ul>
                                <li>
                                    <a target="_top" href="<?php echo SITE_FB_URL ?>">
                                        <img title="home" alt="home" src="<?php echo IMAGES_FB_PATH ?>/home.png">
                                    </a>
                                </li>
                                <li>
                                    <a target="_top" href="<?php echo SITE_FB_URL ?>page/aboutus/"><?php echo $this->Translate('AboutUs')?></a>
                                </li>
                            </ul>
                        </div>
                        <div class="portlet">
                             <div class="bluewidgetHeader">
                                   <?php echo $this->Translate('AboutUs')?>
                            </div>
                        </div>
                        <div class="content">
							<?php echo $this->Translate('AboutUsDetail')?>
                           
                        </div>
                    </div>
                    
                   
                </div>