<div id="rightColumn">
                    <div style="border-bottom:1px solid #e2e2e2;" class="mainColumnWidget">
                        <div id="breadCrumb">
                            <ul>
                                <li>
                                    <a href="<?php echo SITE_FB_URL ?>index" target="_top">
                                        <img src="<?php echo IMAGES_FB_PATH ?>/home.png" alt="home" title="home">
                                    </a>
                                </li>
                                <li>
                                    <a href="<?php echo SITE_FB_URL ?>page/contactus/" target="_top">Contact Us</a>
                                </li>
                            </ul>
                        </div>
                        <div class="portlet">
                             <div class="bluewidgetHeader">
                                 Contact Us
                            </div>
                        </div>
                        <div class="content">
                        	<table cellspacing="0" cellpadding="0">
                                <tbody><tr>
                                    <td><img alt="" src="<?php echo IMAGES_FB_PATH ?>/home_contact.png"></td>
                                    <td width="12"></td>
                                    <td>
                                        <table cellspacing="0" cellpadding="0">
                                            <tbody><tr>
                                                <td class="style2">
                                                    PO Box 782368,
                                                </td>
                                            </tr>
                                            <tr><td height="2"></td></tr>
                                            <tr>
                                                <td class="style2">
                                                    Sandton, South Africa 2146
                                                </td>
                                            </tr>
                                        </tbody></table>
                                    </td>
                                </tr>
                                <tr><td height="12"></td></tr>
                                <tr>
                                    <td><img alt="" src="<?php echo IMAGES_FB_PATH ?>/retailer_panel_icon.png"></td>
                                    <td width="12"></td>
                                    <td>
                                        <table cellspacing="0" cellpadding="0">
                                            <tbody><tr>
                                                <td class="style2">
                                                    +2782-960-0922
                                                </td>
                                            </tr>
                                        </tbody></table>
                                    </td>
                                </tr>
                                <tr><td height="12"></td></tr>
                                <tr>
                                    <td><img alt="" src="<?php echo IMAGES_FB_PATH ?>/email.png"></td>
                                    <td width="12"></td>
                                    <td>
                                        <table cellspacing="0" cellpadding="0">
                                            <tbody><tr>
                                                <td class="style2">
                                                    <a href="#">coo@puvoo.com</a><br>
                                                    <a href="mailto:marketing@puvoo.com">marketing@puvoo.com</a><br>
                                                    <a href="mailto:sales@puvoo.com">sales@puvoo.com</a>
                                                </td>
                                            </tr>
                                        </tbody></table>
                                    </td>
                                </tr>
                            </tbody></table>
                       </div>
                        
                    </div>
                    
                   
                </div>