<div id="rightColumn">
                    <div class="mainColumnWidget" style="border-bottom:1px solid #e2e2e2;">
                        <div id="breadCrumb">
                            <ul>
                                <li>
                                    <a target="_top" href="<?php echo SITE_FB_URL ?>">
                                        <img title="home" alt="home" src="<?php echo IMAGES_FB_PATH ?>/home.png">
                                    </a>
                                </li>
                                <li>
                                    <a target="_top" href="<?php echo SITE_FB_URL ?>page/invitefriend/">Invite</a>
                                </li>
                            </ul>
                        </div>
                        <div class="portlet">
                            <div class="bluewidgetHeader">
                                Add People to Your Network
                            </div>
                        </div>
						<?php if( $this->userlogin == 1 )  { ?>
                        <div class="content" style="padding-bottom:0px;">
                        	<div id="findfrnd">
							<form method="post" action="" name="invitefriendfrm" id="invitefriendfrm">
                                <table cellspacing="0" width="100%" cellpadding="0" border="0">
									<tr>
										<td style="padding-right:5px;">
										    <strong>Find Friends:&nbsp;</strong>
											<table cellspacing="5" width="100%" cellpadding="3">
												<tr>
													<td colspan="2">
														<?php if( count($this->addError) > 0 ) { ?>
														<?php 	foreach($this->addError as $key => $val ) { ?>
																	<h5 style="color:#FF0000;font-size:12px;"><?php echo $val; ?></h5>
														<?php 	}?>
														<?php } ?>
														<?php if($this->success != '' ) { ?>
															<h5 style="color:#009900; font-size:12px;"><?php echo $this->success; ?></h5>
														<?php } ?>
													</td>
												</tr>
												<tr>
													<td width="30%">Email Id:</td>
													<td width="70%">
														<input id="q" class="inputtext" type="text" title="Start typing a friend's email id" style="height: 18px; width: 235px;width: 230px\0/; color: rgb(119, 119, 119);" value="Start typing a friend's name" onblur="if (this.value=='') { this.value='Start typing a friend\'s email id'; } " onfocus="this.value='';" name="friends_email" id="friends_email" />
													</td>
												</tr>
												<tr>
													<td width="30%" valign="top">Comments:</td>
													<td width="70%">
														<textarea cols="45" rows="7" name="friends_mailtext" id="friends_mailtext"></textarea>
													</td>
												</tr>
												<tr>
													<td></td>
													<td valign="middle">
													<label class="uiButton">
														<input type="submit" style="width:65px;" value="" class="sendbtn" />
													</label>
													</td>
												</tr>
											</table>
										</td>
									</tr>
                                 </table>   
								</form>
                            </div>
                          	<div id="network">
                            	<!--<div class="addfrnd">
                                	<div class="thumnail"><img src="<?php echo IMAGES_FB_PATH ?>/picture.gif" alt="" /></div>
                                    <div class="frndname">
                                    	Maria France Lanza
                                    </div>
                                    <div class="invitebtn">
                                    	<input type="button" value="" class="invite" /><input type="button" value="" class="skip" />
                                    </div>
                                    <div class="clear"></div>
                                </div>
                                <div class="addfrnd">
                                	<div class="thumnail"><img src="<?php echo IMAGES_FB_PATH ?>/picture.gif" alt="" /></div>
                                    <div class="frndname">
                                    	Macro camisani calzolari calzolari
                                    </div>
                                    <div class="invitebtn">
                                    	<input type="button" value="" class="invite" /><input type="button" value="" class="skip" />
                                    </div>
                                    <div class="clear"></div>
                                </div>-->
                            </div>
                            <div class="clear" style="height:0px;"></div>
                        </div>
                        <?php } else { ?>
						<div class="content" style="padding-bottom:0px;">
							<div id="findfrnd">
								<fb:login-button></fb:login-button>
							</div>
						</div>
						<?php } ?>
                    </div>
                    
                   
                </div>
				
<script type="text/javascript">
$(document).ready(
function(){
/*FB.ui({method:'permissions.request',perms:''},function(response){
			if(response.status=="connected"){
				
				return false;
			}else if(response.status=="notConnected"){
				
				return false;
			}
		});*/
		
		/*
		FB.ui({
        client_id: '124974344272864',
        method: 'oauth',
        scope: 'email,user_birthday',
        redirect_uri: 'http://apps.facebook.com/pvalpha/',
        response_type: 'token'
      });*/
	  
	 /* FB.ui({
                'method': 'permissions.request',
                'perms': 'user_birthday,user_interests,user_likes,offline_access', 'display': 'iframe'
            },
            function(response) {
                if (response.perms == 'user_birthday,user_interests,user_likes,offline_access') { window.top.location.href = 'https://apps.facebook.com/pvalpha/page/invitefriend';
                } else {
                    //alert('Error requesting permission');
                }
            });*/
				
}
);
</script>