<div id="rightColumn">
                    <div class="mainColumnWidget" style="border-bottom:1px solid #e2e2e2;">
                        <div id="breadCrumb">
                            <ul>
                                <li>
                                    <a target="_top" href="<?php echo SITE_FB_URL ?>">
                                        <img title="home" alt="home" src="<?php echo IMAGES_FB_PATH ?>/home.png">
                                    </a>
                                </li>
                                <li>
                                    <a target="_top" href="<?php echo SITE_FB_URL ?>page/invitefriend/">Invite</a>
                                </li>
                            </ul>
                        </div>
                        <div class="portlet">
                            <div class="bluewidgetHeader">
                                Add People to Your Network
                            </div>
                        </div>
                        <div class="content" style="padding-bottom:0px;">
                        	<div id="findfrnd">
                                <table cellspacing="0" cellpadding="0" border="0">
                                    <tbody>
                                        <tr>
                                            <td style="padding-right:5px;">
                                                Find Friends:&nbsp;<input id="q" class="inputtext" type="text" title="Start typing a friend's name" style="height: 18px; width: 235px;width: 230px\0/; color: rgb(119, 119, 119);" value="Start typing a friend's name" onBlur="if (this.value=='') this.value='Start typing a friend's name'" onFocus="this.value=''" />
                                            </td>
                                            <td style="" valign="middle">
                                                <label class="uiButton">
                                                    <input type="submit" style="width:65px;" value="" class="searchbtn" />
                                                </label>
                                            </td>
                                        </tr>
                                    </tbody>
                                 </table>
                            </div>
                          	<div id="network">
                            	<div class="addfrnd">
                                	<div class="thumnail"><img src="<?php echo IMAGES_FB_PATH ?>/picture.gif" alt="" /></div>
                                    <div class="frndname">
                                    	Maria France Lanza
                                    </div>
                                    <div class="invitebtn">
                                    	<input type="button" value="" class="invite" /><input type="button" value="" class="skip" />
                                    </div>
                                    <div class="clear"></div>
                                </div>
                                <div class="addfrnd">
                                	<div class="thumnail"><img src="<?php echo IMAGES_FB_PATH ?>/picture.gif" alt="" /></div>
                                    <div class="frndname">
                                    	Macro camisani calzolari calzolari
                                    </div>
                                    <div class="invitebtn">
                                    	<input type="button" value="" class="invite" /><input type="button" value="" class="skip" />
                                    </div>
                                    <div class="clear"></div>
                                </div>
                            </div>
                            <div class="clear" style="height:0px;"></div>
                        </div>
                        
                    </div>
                    
                   
                </div>