<ul class="topnav">
	
	<li><a href="<?php echo SITE_URL . 'admin/' ?>"><img src="<?php echo IMAGES_PATH; ?>/admin/home2.png" style="vertical-align:middle; padding-bottom:6px;" />&nbsp;<?php echo $this->Translate("Administration"); ?></a>
		<ul class="subnav">
			<li>
				<a href="<?php echo SITE_URL . 'admin/index/changepassword' ?>" class="">
					<?php echo $this->Translate("Change_Password"); ?>
				</a>
			</li>
			<li><a href="<?php echo SITE_URL . 'admin/logout' ?>" class="">Logout</a></li>
		</ul>
	</li>

	<li>
		 <a href="<?php echo SITE_URL . 'admin/merchants' ?>" class="">
		 	<img src="<?php echo IMAGES_PATH; ?>/admin/user.png" style="vertical-align:middle; padding-bottom:4px;" />
			&nbsp;<?php echo $this->Translate("Merchants"); ?>
		</a>
	</li>

	<li><a href="#"><img src="<?php echo IMAGES_PATH; ?>/admin/article.png" style="vertical-align:middle; padding-bottom:6px;" />&nbsp;<?php echo $this->Translate("Warehouse"); ?></a>
		<ul class="subnav">
			<li>
				<a href="<?php echo SITE_URL . 'admin/category' ?>" class="">
					<?php echo $this->Translate("Categories"); ?>
				</a>
			<li>
			<li>
				<a href="<?php echo SITE_URL . 'admin/products' ?>" class="">
					<?php echo $this->Translate("Products"); ?>
				</a>
			</li>
			<li>
				<a href="<?php echo SITE_URL . 'admin/orders' ?>" class="">
					<?php echo $this->Translate("Orders"); ?>
				</a>
			</li>
			</ul>
	</li>
	
	<li><a href="#"><img src="<?php echo IMAGES_PATH; ?>/admin/article.png" style="vertical-align:middle; padding-bottom:6px;" />&nbsp;<?php echo $this->Translate("Settings"); ?></a>
		<ul class="subnav">
			<li>
				 <a href="<?php echo SITE_URL . 'admin/currency' ?>" class="">
					<?php echo $this->Translate("Currency"); ?>
				</a>
			</li>
			<li>
				<a href="<?php echo SITE_URL . 'admin/languages'; ?>" class="">
					<?php echo $this->Translate("Manage_Languages"); ?>
				</a>
			</li>
			<li><a href="<?php echo SITE_URL . 'admin/definitions'; ?>" >
				<?php echo $this->Translate("Language_Definitions"); ?>
				</a>
			</li>
			<li><a href="<?php echo SITE_URL . 'admin/country'; ?>" >
				<?php echo $this->Translate("Country_And_State"); ?>
				</a>
			</li>
			<li><a href="<?php echo SITE_URL . 'admin/weight'; ?>" >
				<?php echo $this->Translate("Manage_Weight"); ?>
				</a>
			</li>
			<li><a href="<?php echo SITE_URL . 'admin/weightunit'; ?>" >
				<?php echo $this->Translate("Weight_Conversion"); ?>
				</a>
			</li>
			<li><a href="<?php echo SITE_URL . 'admin/length'; ?>" >
				<?php echo $this->Translate("Manage_Length"); ?>
				</a>
			</li>
			<li><a href="<?php echo SITE_URL . 'admin/lengthunit'; ?>" >
				<?php echo $this->Translate("Length_Conversion"); ?>
				</a>
			</li>
		</ul>
	</li>
	
</ul>
