<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="#"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Merchants'); ?></span></li>
	</ul>
</div>


<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate('Merchant_Management'); ?>
	</div>
	
	<?php if(count($this->addErrorMessage) > 0 ) { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
				<?php foreach($this->addErrorMessage as $key => $val ) { ?>
					<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
					<strong><?php echo $val; ?></strong></p>
				<?php } ?>
			</div>
		</div>
	<?php } ?>	
	
	<form method="post" name="add_form" id="add_form" >
		<table class="Panel" style="margin-top:10px;">
			<tr>
				<td class="Heading2" colspan="2"><?php echo $this->Translate('Add_Merchant'); ?></td>
			</tr>
			<tr>
				<td colspan="2">
				<div id="div0" style="padding-bottom:5px">
					<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Merchant_FName'); ?>:
							</td>
							<td>
								<input type="text" name="user_fname" id="user_fname" class="Field250" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Merchant_LName'); ?>:
							</td>
							<td>
								<input type="text" name="user_lname" id="user_lname" class="Field250" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Merchant_Email'); ?>:
							</td>
						  <td>
							  <input type="text" name="user_email" id="user_email" class="Field250" />
							  <span></span>
						  </td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Merchant_Password'); ?>:
							</td>
							<td>
								<input type="text" name="user_password" id="user_password" class="Field250" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Merchant_FB_Id'); ?>:
							</td>
							<td>
								<input type="text" name="user_facebook_id" id="user_facebook_id" class="Field250" />
								<span></span>
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('User_Status'); ?>:
							</td>
							<td>
								<span>
									<input type="radio" name="user_status" id="user_status" class="" value="1" />
									<?php echo $this->Translate('Admin_User_Status_Active'); ?>&nbsp;
									<input type="radio" name="user_status" id="user_status"  value="0" />
									<?php echo $this->Translate('Admin_User_Status_Inactive'); ?>
								</span>
								<span></span>
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						<tr>
						   	<td colspan="2">
								<input type="submit" id="anything" onclick="Javascript: return ValidateAddFrom()"  value="<?php echo $this->Translate('Submit'); ?>" />
								<input type="button" id="anything"  value="<?php echo $this->Translate('Cancle'); ?>" onclick="window.location='<?php echo $this->site_url; ?>'"/>
						   </td>
						</tr>
					</table>
				</div>
				</td>
			</tr>
		</table>   
	</form>            
</div> 

<!--     JS Global Variable for the language    -->

<script language="javascript" type="text/javascript">
var siteurl = "<?php echo SITE_URL; ?>";
var ERR_MERCHANTS_FNAME = "<?php echo $this->Translate('Err_Merchant_FName'); ?>";  
var ERR_MERCHANTS_LNAME = "<?php echo $this->Translate('Err_Merchant_LName'); ?>";  
var ERR_MERCHANTS_EMAIL = "<?php echo $this->Translate('Err_Merchant_Email'); ?>";
var ERR_MERCHANTS_INVALID_EMAIL = "<?php echo $this->Translate('Err_Merchant_Invalid_Email'); ?>";
var ERR_MERCHANTS_PASSWORD = "<?php echo $this->Translate('Err_Merchant_Password'); ?>";
var ERR_MERCHANTS_PASSWORD_MIN_MAX = "<?php echo $this->Translate('Err_Merchant_Password_Min_Max'); ?>";
var ERR_MERCHANTS_FB = "<?php echo $this->Translate('Err_Merchant_FB'); ?>";
var ERR_USER_STATUS = "<?php echo $this->Translate('Err_user_status'); ?>" ; 
</script>