<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="<?php echo SITE_URL; ?>admin/"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last1"><a href="<?php echo SITE_URL; ?>admin/products"><?php echo $this->Translate('Products'); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Product_Edit_Detail'); ?></span></li>
	</ul>
</div>

<!--       Set Record value         -->
<?php  $detail = $this->detail;  ?>
<?php  $images = $this->images;  ?>
<?php  $category = $this->sub_category; ?>
<?php  $options = $this->options;  ?>

<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate('Products_Management'); ?>
	</div>
	
	<?php if(count($this->editErrorMessage) > 0 ) { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
				<?php foreach($this->editErrorMessage as $key => $val ) { ?>
					<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
					<strong><?php echo $val; ?></strong></p>
				<?php } ?>
			</div>
		</div>
	<?php } ?>	
	
	<form method="post" name="detail_edit_form" id="detail_edit_form" >
		<table class="Panel" style="margin-top:10px;">
			<tr>
				<td class="Heading2" colspan="2"><?php echo $this->Translate('Product_Edit_Detail'); ?></td>
			</tr>
			<tr>
				<td colspan="2">
				<div id="div0" style="padding-bottom:5px">
					<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Name'); ?>
							</td>
							<td>
								<input type="text" name="product_name" id="product_name" value="<?php echo $detail['product_name'];  ?>" class="Field250" />
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						
						<!--       Edit Product Language        -->
						<?php foreach( $this->language as $key => $val ) { ?>
						<?php 	if($val['language_id'] != DEFAULT_LANGUAGE ) { ?>
						<tr>
							<td class="FieldLabel"></td>
							<td>
								<?php $lagn_index = 'product_name_'.$val['language_id']; ?>
								<input  type="text" value="<?php if(isset($this->langdata[$val['language_id']]['product_name'])) {  echo $this->langdata[$val['language_id']]['product_name']; } ?>" name="product_name_<?php echo $val['language_id']; ?>" id="product_name_<?php echo $val['language_id']; ?>" class="Field250" />
								<span></span>
								&nbsp;&nbsp;&nbsp;<?php echo $val['name']." ( ".$val['code']." )"; ?>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						<?php 	}?>
						<?php } ?>
						
						
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Desc'); ?>
							</td>
							<td>
								<textarea name="product_description" cols="30" id="product_description"><?php echo $detail['product_description'];  ?></textarea>
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						
						
						<!--       Edit Category Language        -->
						<?php foreach( $this->language as $key => $val ) { ?>
						<?php 	if($val['language_id'] != DEFAULT_LANGUAGE ) { ?>
						<tr>
							<td class="FieldLabel"></td>
							<td>
								<?php $lagn_index = 'product_description_'.$val['language_id']; ?>
								<textarea name="product_description_<?php echo $val['language_id']; ?>" cols="30" id="product_description_<?php echo $val['language_id']; ?>"><?php if(isset($this->langdata[$val['language_id']]['product_description'])) {  echo $this->langdata[$val['language_id']]['product_description']; } ?></textarea>
								
								&nbsp;&nbsp;&nbsp;<?php echo $val['name']." ( ".$val['code']." )"; ?>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						<?php 	}?>
						<?php } ?>
						
						
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_User'); ?>
							</td>
							<td>
								<?php $user_name = ''; if(isset($detail['user_name'])) { $user_name =  $detail['user_name']; } else { $user_name = $this->user_name; }  ?>
								<input type="text" name="user_name" id="user_name" disabled="disabled" value="<?php echo $user_name;  ?>" class="Field250" />	
								<input type="hidden" name="product_user_name" id="product_user_name" value="<?php echo $user_name;  ?>" class="Field250" />							
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Price'); ?>
							</td>
							<td>
								<input type="text" name="product_price" id="product_price" value="<?php echo $detail['product_price'];  ?>" class="Field250" />								
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Code'); ?>
							</td>
							<td>
								<input type="text" name="product_code" id="product_code" value="<?php echo $detail['product_code'];  ?>" class="Field250" />
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Category'); ?>
							</td>
							<td>
								<select name="product_category" id="product_category" multiple="multiple"  >
									<!--<?php $category_array = $this->category; ?>-->
									<?php echo $this->cateTree; ?>
								</select>
								<input type="hidden" name="multiselect_product_category_value" id="multiselect_product_category_value" value="">
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Weight'); ?>
							</td>
							<td>
								<input type="text" name="product_weight" id="product_weight" value="<?php echo $detail['product_weight'];  ?>" class="Field250" />
								
								<select name="weight_unit_id" id="weight_unit_id" class="comboField">
									<option value=""  ><?php echo $this->Translate('Product_Select_Weight_Unit'); ?></option>
									<?php if(count($this->weight) > 0) {  ?>
									<?php  		foreach($this->weight as $key => $val) { ?>	
									<?php  		   	if ( $val['weight_unit_id'] == $detail["weight_unit_id"] ) { ?>	
									<option value="<?php echo $val['weight_unit_id']; ?>" selected="selected">
									<?php 			} else {  ?>
									<option value="<?php echo $val['weight_unit_id']; ?>">
									<?php 			}  ?>		
									<?php 			echo $val["weight_unit_key"];  ?>	
									</option>
									<?php 		}  ?>
									<?php } else {  ?>
									<?php }  ?>
								</select>
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Length'); ?>
							</td>
							<td>
								<input type="text" name="length" id="length" value="<?php echo $detail['length'];  ?>" class="Field250" />
								<select name="length_unit_id" id="length_unit_id" class="comboField">
									<option value="" ><?php echo $this->Translate('Product_Select_Length_Unit'); ?></option>
									<?php if(count($this->length) > 0) {  ?>
									<?php  		foreach($this->length as $key => $val) { ?>	
									<?php  		   	if ( $val['length_unit_id'] == $detail["length_unit_id"] ) {  ?>	
									<option value="<?php echo $val['length_unit_id']; ?>" selected="selected">
									<?php 			} else {  ?>
									<option value="<?php echo $val['length_unit_id']; ?>">
									<?php 			}  ?>		
									<?php 			echo $val["length_unit_key"];  ?>	
									</option>
									<?php 		}  ?>
									<?php } else {  ?>
									<?php }  ?>
								</select>
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Tax_Class'); ?>
							</td>
							<td>
								<select name="tax_rate_class_id" id="tax_rate_class_id" class="comboField">
									<option value="" ><?php echo $this->Translate('Product_Select_Length_Unit'); ?></option>
									<?php if(count($this->taxrate_class) > 0) {  ?>
									<?php  		foreach($this->taxrate_class as $key => $val) { ?>	
									<?php  		   	if ( $val['tax_rate_class_id'] == $detail["tax_rate_class_id"] ) {  ?>	
									<option value="<?php echo $val['tax_rate_class_id']; ?>" selected="selected">
									<?php 			} else {  ?>
									<option value="<?php echo $val['tax_rate_class_id']; ?>">
									<?php 			}  ?>		
									<?php 			echo $val["tax_rate_name"];  ?>	
									</option>
									<?php 		}  ?>
									<?php } else {  ?>
									<?php }  ?>
								</select>
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Width'); ?>
							</td>
							<td>
								<input type="text" name="width" id="width" value="<?php echo $detail['width'];  ?>" class="Field250" />
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Depth'); ?>
							</td>
							<td>
								<input type="text" name="depth" id="depth" value="<?php echo $detail['depth'];  ?>" class="Field250" />
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Quantity'); ?>
							</td>
						  <td>
							  <input type="text" name="available_qty" id="available_qty" value="<?php echo $detail['available_qty'];  ?>" class="Field250" />
						  </td>
						  <td></td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Discount'); ?>
							</td>
						  <td>
							  <input type="text" name="discount" id="discount" value="<?php echo $detail['discount'];  ?>" class="Field250" />
						  </td>
						  <td></td>
						</tr>
						<tr><td height="5"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Available_Date'); ?>
							</td>
							<td>
								<input type="text" name="available_date" id="available_date" value="<?php if(strtotime($detail['available_date']) > 0 ) { echo date('Y-m-d', strtotime($detail['available_date'])); }  ?>" class="Field250 datepicker" />		
							</td>
							<td></td>
						</tr>	
						<tr><td height="5"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Expiration_Date'); ?>
							</td>
							<td>
								<input type="text" name="expiration_date" id="expiration_date" value="<?php if(strtotime($detail['expiration_date']) > 0 ) { echo date('Y-m-d', strtotime($detail['expiration_date'])); } ?>" class="Field250 datepicker" />		
							</td>
							<td></td>
						</tr>	
						<tr><td height="5"></td></tr>	
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Promotion_Start_Date'); ?>
							</td>
							<td>
								<input type="text" name="promotion_start_date" id="promotion_start_date" value="<?php if(strtotime($detail['promotion_start_date']) > 0 ) { echo date('Y-m-d', strtotime($detail['promotion_start_date'])); } ?>" class="Field250 datepicker" />		
							</td>
							<td></td>
						</tr>	
						<tr><td height="5"></td></tr>	
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Promotion_End_Date'); ?>
							</td>
							<td>
								<input type="text" name="promotion_end_date" id="promotion_end_date" value="<?php if(strtotime($detail['promotion_end_date']) > 0 ) { echo date('Y-m-d', strtotime($detail['promotion_end_date'])); }  ?>" class="Field250 datepicker" />		
							</td>
							<td></td>
						</tr>			
						<tr><td height="5"></td></tr>	
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Start_Sales'); ?>
							</td>
							<td>
								<span>
									<?php if($detail["start_sales"] == "1") { ?>
										<input type="radio" name="start_sales" id="start_sales" checked="checked" class="" value="1" />			
										<?php echo $this->Translate('Admin_User_Status_Active'); ?>&nbsp;
										<input type="radio" name="start_sales"  value="0" />
										<?php echo $this->Translate('Admin_User_Status_Inactive'); ?>
									<?php } elseif($detail["start_sales"] == "0") {  ?>
										<input type="radio" name="start_sales" id="start_sales" class="" value="1" />			
										<?php echo $this->Translate('Admin_User_Status_Active'); ?>&nbsp;
										<input type="radio" name="start_sales"  value="0" checked="checked" />
										<?php echo $this->Translate('Admin_User_Status_Inactive'); ?>
									<?php } else { ?>
										<input type="radio" name="start_sales" id="start_sales" class="" value="1" />			
										<?php echo $this->Translate('Admin_User_Status_Active'); ?>&nbsp;
										<input type="radio" name="start_sales"  value="0" />
										<?php echo $this->Translate('Admin_User_Status_Inactive'); ?>
									<?php } ?>  
								</span>
								<span></span>
							</td>
						</tr>
					</table>
				</div>
				</td>
			</tr>
		</table>   
		
		<!--         Hidden fields                       -->
		<input type="hidden" name="product_id" id="product_id" value="<?php echo $this->product_id; ?>" />
		<input type="hidden" name="product_edit_type" id="product_edit_type" value="Detail" />
	
		<table class="Panel" >
			<tr>
				<td class="Heading2" colspan="2"><?php echo $this->Translate('Product_Images'); ?></td>
			</tr>
			<tr>
				<td colspan="2">
					<div id="div0" style="padding-bottom:5px">
						<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
							<tr>
								<td class="FieldLabel">
									<?php echo $this->Translate('Product_Upload_Images'); ?>
								</td>
								<td>
									<div id="file-uploader-demo1">
									</div>
								</td>
							</tr>
							<tr>
								<td colspan="2">
									<ul class="imagegallery" id="imagegallery">
									<?php 
										if( $images != NULL ) {
											foreach( $images as $key => $val ) 
										  	{  
												$img_string = SITE_PRODUCT_IMAGES_PATH."/p".$this->product_id."/".str_replace("_img","_th1",$val['image_name']);	
									?>
												<li id="imagegallery<?php echo $val['image_id']; ?>">
													<div class="prodimg">
														<img src="<?php echo $img_string; ?>" alt="" />
													</div>
												
													<div class="borderbottom1">
														<div style="float:left;">
															<?php if($val["is_primary_image"] == 1 ) { ?>
															<input type="radio" value="<?php echo $val['image_id']; ?>" name="product_primary_image" checked="checked" />
															<?php } else { ?>
															<input type="radio" value="<?php echo $val['image_id']; ?>" name="product_primary_image"  />
															<?php } ?>
														</div>
														<div style="float:right; margin-top:-5px;">
															<a style="cursor:pointer;" onclick="DeleteProductImage('<?php echo $this->product_id; ?>','<?php echo $val["image_id"]; ?>')">
																<img src="<?php echo IMAGES_PATH; ?>/admin/delicon.gif" alt="" style="vertical-align:middle; padding-top:1px;" />
															</a>
														</div>
														<div class="clear"></div>
													</div>
												</li>
									<?php  	}
										} else {
										
											echo $this->Translate('Product_No_Images_Found'); 
										} 
									 ?>
									 </ul>
								</td>
							</tr>
						</table>
					</div>
				</td>
			</tr>
		</table>
		<table class="Panel" >
			<tr>
				<td class="Heading2" colspan="2"><?php echo $this->Translate('Product_Properties'); ?></td>
			</tr>
			<tr>
				<td colspan="2">
					<div id="div0" style="padding-bottom:5px">
						<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
							<tr><td height="5"></td></tr>
							<tr>
								<td valign="top" class="FieldLabel">
									<?php echo $this->Translate('Product_Options'); ?>
								</td>
								<td>
									<table id="PrDOptVal" cellspacing="0" cellpadding="3" width="100%" > 
									<?php  if($options != NULL) {  	?>
									<?php  $option_value = '';  	?>
									<?php		foreach($options as $key =>$val) {  ?>
									<?php			if($val["product_options_id"] != $option_value) { ?>
										<tr id="PD_Row_<?php echo $val["product_options_id"]; ?>">
											<td width="25%" valign="top" id="PD_Option_<?php echo $val["product_options_id"]; ?>"><?php echo $val["option_title"]; ?></td>
											<td width="55%" >
												<table width="100%" id="PD_Option_Table_<?php echo $val["product_options_id"]; ?>">
					
									<?php				foreach($options as $key =>$val2) { ?>
									<?php					if($val["LNK_options_id"] == $val2["LNK_options_id"] && $val2["product_options_detail_id"] != "" ) { ?>
								
													<tr id="POD_Row_<?php echo $val2["product_options_detail_id"]; ?>">
														<td width="35%" id="POD_Name_<?php echo $val2["product_options_detail_id"]; ?>" >
															<?php echo $val2["option_name"]; ?>	
														</td>
														<td width="35%" id="POD_Code_<?php echo $val2["product_options_detail_id"]; ?>" >
															<?php echo $val2["option_code"]; ?>	
														</td>
														<td width="25%">
															<a  onclick="EditProductOption(<?php echo $val2["product_options_detail_id"]; ?>)" style="color:#17649E; cursor:pointer;" >
																<?php echo $this->Translate("Edit"); ?>
															</a>
															&nbsp;/&nbsp;
															<a  style="color:#17649E; cursor:pointer;" onclick="DeleteProductOptionValue(<?php echo $val2["product_options_detail_id"]; ?>)" >
																<?php echo $this->Translate("Delete"); ?>
															</a>
														
														</td>
													</tr>
																
									<?php  					}		?>
									<?php  				}			?>		
																			
												</table>
											</td>
										</tr>
										<tr >
											<td></td>
											<td>
												<input type="button" onclick="AddMoreOptionValue(<?php echo $val["product_options_id"]; ?>)"  value="<?php echo $this->Translate('Product_Add_Option'); ?>"> 
												<input type="button" onclick="DeleteProductOption(<?php echo $val["product_options_id"]; ?>)"  value="<?php echo $this->Translate('Product_Delete_Option'); ?>">
											</td>
										</tr>
									<?php  			}  				?>
									<?php 		 $option_value = $val["product_options_id"]; ?>
									<?php  		}  					?>
									<?php  } else {  				?>
									<?php  $option_value = '';  	?>
										<tr id="No_Option">
											<td colspan="3"><?php echo $this->Translate('Product_No_Options_Found'); ?></td>
										</tr>
									<?php  }   ?>
									<input type="hidden" name="last_product_option_id" id="last_product_option_id" value="<?php echo $option_value; ?>">
									</table>
								</td>
							</tr>
							<tr><td height="10"></td></tr>
							<tr><td height="5" ></td><td><input type="button" onclick="AddProductOption(<?php echo $this->product_id; ?>)" value="<?php echo $this->Translate('Add_New'); ?>"></td></tr>
						</table>
					</div>
				</td>
			</tr>
		</table>
		<table>		
			<tr><td height="15"></td></tr>
			<tr>
				<td colspan="2">
					<input type="submit" onclick="Javascript: return ValidateProductDetailForm()" value="<?php echo $this->Translate('Submit'); ?>" />
					<input type="button" value="<?php echo $this->Translate('Back'); ?>" onclick="window.location='<?php echo $this->site_url; ?>'"/>
			   </td>
			</tr>
			<tr><td height="15"></td></tr>		
		</table>
	</form>
</div> 

<!--     JS Global Variable for the language    -->

<script language="javascript" type="text/javascript">
window.onload = createUploader;
$(function(){
   	$("#product_category").multiselect({
	   header: false,
	   noneSelectedText: "<?php echo $this->Translate('Product_Select_MCategory'); ?>"
	});
});

var siteurl = "<?php echo SITE_URL; ?>";
var image_path = "<?php echo IMAGES_PATH; ?>/admin/";
var product_id = "<?php echo $this->product_id; ?>";
var EDIT = "<?php echo $this->Translate('Edit'); ?>"; 
var ADD = "<?php echo $this->Translate('Add'); ?>";  
var DELETE = "<?php echo $this->Translate('Delete'); ?>"; 
var UPDATE = "<?php echo $this->Translate('Update'); ?>";
var CANCEL = "<?php echo $this->Translate('Cancel'); ?>"; 
var PRODUCT_ADD_OPTION = "<?php echo $this->Translate('Product_Add_Option'); ?>"; 
var PRODUCT_DELETE_OPTION = "<?php echo $this->Translate('Product_Delete_Option'); ?>"; 
var ERR_PRODUCT_NAME = "<?php echo $this->Translate('Err_Product_Name'); ?>";  
var ERR_PRODUCT_DESC = "<?php echo $this->Translate('Err_Product_Desc'); ?>";  
var ERR_PRODUCT_PRICE = "<?php echo $this->Translate('Err_Product_Price'); ?>";
var ERR_PRODUCT_INVALID_PRICE = "<?php echo $this->Translate('Err_Product_Invalid_Price'); ?>";
var ERR_PRODUCT_CODE = "<?php echo $this->Translate('Err_Product_Code'); ?>";
var ERR_PRODUCT_WEIGHT = "<?php echo $this->Translate('Err_Product_Weight'); ?>";
var ERR_PRODUCT_INVALID_WEIGHT = "<?php echo $this->Translate('Err_Product_Invalid_Weight'); ?>";
var ERR_PRODUCT_WEIGHT_UNIT = "<?php echo $this->Translate('Err_Product_Weight_Unit'); ?>" ; 
var ERR_PRODUCT_LENGTH = "<?php echo $this->Translate('Err_Product_Length'); ?>" ; 
var ERR_PRODUCT_INVALID_LENGTH = "<?php echo $this->Translate('Err_Product_Invalid_Length'); ?>" ; 
var ERR_PRODUCT_LENGTH_UNIT = "<?php echo $this->Translate('Err_Product_Length_Unit'); ?>" ; 
var ERR_PRODUCT_WIDTH = "<?php echo $this->Translate('Err_Product_Width'); ?>" ; 
var ERR_PRODUCT_INVALID_WIDTH = "<?php echo $this->Translate('Err_Product_Invalid_Width'); ?>" ; 
var ERR_PRODUCT_DEPTH = "<?php echo $this->Translate('Err_Product_Depth'); ?>" ; 
var ERR_PRODUCT_INVALID_DEPTH = "<?php echo $this->Translate('Err_Product_Invalid_Depth'); ?>" ; 
var ERR_PRODUCT_QUANTITY = "<?php echo $this->Translate('Err_Product_Quantity'); ?>" ; 
var ERR_PRODUCT_INVALID_QUANTITY = "<?php echo $this->Translate('Err_Product_Invalid_Quantity'); ?>" ; 
var ERR_PRODUCT_START_SALE = "<?php echo $this->Translate('Err_Product_Start_Sales'); ?>" ; 
var ERR_PRODUCT_OPTION_TITLE = "<?php echo $this->Translate('Err_Product_Option_Title'); ?>";
var ERR_PRODUCT_OPTION_DETAIL = "<?php echo $this->Translate('Err_Product_Option_Detail'); ?>";
var ERR_PRODUCT_PRIMARY_IMAGE = "<?php echo $this->Translate('Err_Product_Primary_Image'); ?>";
var ERR_PRODUCT_PRIMARY_IMAGE_OTHER = "<?php echo $this->Translate('Err_Product_Primary_Image_Other'); ?>"; 
var ERR_PRODUCT_OPTION_VALUE_NAME = "<?php echo $this->Translate('Err_Product_Option_Value_Name'); ?>";  
var ERR_PRODUCT_OPTION_VALUE_INVALID_PRICE = "<?php echo $this->Translate('Err_Product_Option_Value_Invalid_Price'); ?>";
var ERR_PRODUCT_OPTION_VALUE_INVALID_QUANTITY = "<?php echo $this->Translate('Err_Product_Option_Value_Invalid_Quantity'); ?>" ;
var ERR_PRODUCT_OPTION_VALUE_INVALID_WEIGHT = "<?php echo $this->Translate('Err_Product_Option_Value_Invalid_Weight'); ?>";
var PRODUCT_OPTION_VALUE_EDIT_SUCCESS = "<?php echo $this->Translate('Product_Option_Value_Edit_Success'); ?>";
var ERR_PRODUCT_PRIMARY_AVAILABLE_DATE = "<?php echo $this->Translate('Err_Product_Available_Date'); ?>"; 
var ERR_PRODUCT_PRIMARY_EXPIRATION_DATE = "<?php echo $this->Translate('Err_Product_Expiration_Date'); ?>"; 
var ERR_PRODUCT_PRIMARY_PROMOTION_START_DATE = "<?php echo $this->Translate('Err_Product_Promotion_Start_Date'); ?>"; 
var ERR_PRODUCT_PRIMARY_PROMOTION_END_DATE = "<?php echo $this->Translate('Err_Product_Promotion_End_Date'); ?>"; 
var ERR_PRODUCT_PRIMARY_INVALID_DATE = "<?php echo $this->Translate('Err_Product_Invalid_Date'); ?>"; 
var ERR_PRODUCT_DISCOUNT = "<?php echo $this->Translate('Err_Product_Discount'); ?>"; 
var ERR_PRODUCT_INVALID_DISCOUNT = "<?php echo $this->Translate('Err_Product_Invalid_Discount'); ?>"; 
var ERR_PRODUCT_RANGE_DISCOUNT = "<?php echo $this->Translate('Err_Product_Range_Discount'); ?>"; 

</script>


<div id="dialog-confirm" title="<?php echo $this->Translate('Confirm_Delete_Product_Option_Title'); ?>" style="display:none;">
	<div style="text-align:left;">
		<span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
		<?php echo $this->Translate('Confirm_Delete_Product_Option'); ?>
	</div>
</div>

<div id="dialog-confirm-delete-pod" title="<?php echo $this->Translate('Confirm_Delete_Product_Option_Value_Title'); ?>" style="display:none;">
	<div style="text-align:left;">
		<span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
		<?php echo $this->Translate('Confirm_Delete_Product_Option_Value'); ?>
	</div>
</div>


<div id="dialog-product-option" title="<?php echo $this->Translate('Edit_Product_Option_Value'); ?>" style="display:none;">
	<div style="text-align:left;">
		<form  method="post" action="" name="product_option_form" id="product_option_form" >
			<table class="Panel" style="margin-top:10px;">
				<tr>
					<td class="Heading2" colspan="2"><?php echo $this->Translate('Edit_Product_Option'); ?></td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="div0" style="padding-bottom:5px">
							<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
								<tr><td height="5"></td></tr>
								<tr>
									<td class="FieldLabel" width="25%">
										<?php echo $this->Translate('Product_Option_Title'); ?>
									</td>
									<td width="45%">
										<input type="text" name="prod_option_title" id="prod_option_title" value="" class="Field250 productoptval" />						
									</td>
									<td width="30%"></td>
								</tr>
								<tr><td height="5"></td></tr>
							</table>
						</div>
					</td>
				</tr>
				<tr>
					<td class="Heading2" colspan="2"><?php echo $this->Translate('Edit_Product_Option_Detail'); ?></td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="div0" style="padding-bottom:5px">
							<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
								<tr><td height="5"></td></tr>
								<tr>
									<td class="FieldLabel" width="25%">
										<?php echo $this->Translate('Product_Name'); ?>
									</td>
									<td width="45%">
										<input type="text" name="prod_option_name" id="prod_option_name" value="" class="Field250 productoptval" />						
									</td>
									<td width="30%"></td>
								</tr>
								<tr><td height="5"></td></tr>
								<tr>
									<td class="FieldLabel">
										<?php echo $this->Translate('Product_Code'); ?>
									</td>
									<td>
										<input type="text" name="prod_option_code" id="prod_option_code" value="" class="Field250 productoptval" />						
									</td>
									<td></td>
								</tr>
								<tr><td height="5"></td></tr>
								<tr>
									<td class="FieldLabel">
										<?php echo $this->Translate('Product_Weight'); ?>
									</td>
									<td>
										<input type="text" name="prod_option_weight" id="prod_option_weight" value="" class="Field250 productoptval" />		
										<select name="prod_option_weight_unit_id" id="prod_option_weight_unit_id" class="comboField productoptval">
											
											<?php if(count($this->weight) > 0) {  ?>
											<?php  		foreach($this->weight as $key => $val) { ?>	
											<?php  		   	if ( $val['weight_unit_id'] == $detail["weight_unit_id"] ) { ?>	
											<option value="<?php echo $val['weight_unit_id']; ?>" selected="selected">
											<?php 			} else {  ?>
											<option value="<?php echo $val['weight_unit_id']; ?>">
											<?php 			}  ?>		
											<?php 			echo $val["weight_unit_key"];  ?>	
											</option>
											<?php 		}  ?>
											<?php } else {  ?>
											<?php }  ?>
										</select>				
									</td>
									<td valign="top" style="padding-top:5px;"></td>
								</tr>
								<tr><td height="5"></td></tr>
								<tr>
									<td class="FieldLabel">
										<?php echo $this->Translate('Product_Price'); ?>
									</td>
									<td>
										<input type="text" name="prod_option_price" id="prod_option_price" value="" class="Field250 productoptval" />							
									</td>
									<td></td>
								</tr>
								<tr><td height="5"></td></tr>
								<tr>
									<td class="FieldLabel">
										<?php echo $this->Translate('Product_Quantity'); ?>
									</td>
									<td>
										<input type="text" name="prod_option_quantity" id="prod_option_quantity" value="" class="Field250 productoptval" />								
									</td>
									<td></td>
								</tr>
								<tr><td height="5"></td></tr>		
								<input class="productoptval" type="hidden" name="prod_product_options_detail_id" id="prod_product_options_detail_id" value="">						
								<input class="productoptval" type="hidden" name="prod_product_options_id" id="prod_product_options_id" value="">						
							</table>
						</div>
					</td>
				</tr>				
			</table>
		</form>
	</div>
</div>


<div id="dialog-product-option-add" title="<?php echo $this->Translate('Add_Product_Option_Value'); ?>" style="display:none;">
	<div style="text-align:left;">
		<form  method="post" action="" name="product_option_form_add" id="product_option_form_add" >
			<table class="Panel" style="margin-top:10px;">
				<tr>
					<td class="Heading2" colspan="2"><?php echo $this->Translate('Add_Product_Option_Detail'); ?></td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="div0" style="padding-bottom:5px">
							<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
								<tr><td height="5"></td></tr>
								<tr>
									<td class="FieldLabel" width="25%">
										<?php echo $this->Translate('Product_Name'); ?>
									</td>
									<td width="45%">
										<input type="text" name="add_prod_option_name" id="add_prod_option_name" value="" class="Field250 productoptval" />						
									</td>
									<td width="30%"></td>
								</tr>
								<tr><td height="5"></td></tr>
								<tr>
									<td class="FieldLabel">
										<?php echo $this->Translate('Product_Option_Value_Code'); ?>
									</td>
									<td>
										<input type="text" name="add_prod_option_code" id="add_prod_option_code" value="" class="Field250 productoptval" />						
									</td>
									<td></td>
								</tr>
								<tr><td height="5"></td></tr>
								<tr>
									<td class="FieldLabel">
										<?php echo $this->Translate('Product_Weight'); ?>
									</td>
									<td>
										<input type="text" name="add_prod_option_weight" id="add_prod_option_weight" value="" class="Field250 productoptval" />		
										<select name="add_prod_option_weight_unit_id" id="add_prod_option_weight_unit_id" class="comboField productoptval">
											
											<?php if(count($this->weight) > 0) {  ?>
											<?php  		foreach($this->weight as $key => $val) { ?>	
											<?php  		   	if ( $val['weight_unit_id'] == $detail["weight_unit_id"] ) { ?>	
											<option value="<?php echo $val['weight_unit_id']; ?>" selected="selected">
											<?php 			} else {  ?>
											<option value="<?php echo $val['weight_unit_id']; ?>">
											<?php 			}  ?>		
											<?php 			echo $val["weight_unit_key"];  ?>	
											</option>
											<?php 		}  ?>
											<?php } else {  ?>
											<?php }  ?>
										</select>				
									</td>
									<td  valign="top" style="padding-top:5px;"></td>
								</tr>
								<tr><td height="5"></td></tr>
								<tr>
									<td class="FieldLabel">
										<?php echo $this->Translate('Product_Price'); ?>
									</td>
									<td>
										<input type="text" name="add_prod_option_price" id="add_prod_option_price" value="" class="Field250 productoptval" />							
									</td>
									<td></td>
								</tr>
								<tr><td height="5"></td></tr>
								<tr>
									<td class="FieldLabel">
										<?php echo $this->Translate('Product_Quantity'); ?>
									</td>
									<td>
										<input type="text" name="add_prod_option_quantity" id="add_prod_option_quantity" value="" class="Field250 productoptval" />								
									</td>
									<td></td>
								</tr>
							</table>
						</div>
					</td>
				</tr>				
			</table>
		</form>
	</div>
</div>
<script>
	$(function() {
		$( ".datepicker" ).datepicker({ dateFormat: 'yy-mm-dd' });
	});
</script>
