<!--  Crumb  Start -->
<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="<?php echo SITE_URL; ?>admin/"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Products'); ?></span></li>
	</ul>
</div>
<!--  Crumb  end -->


<div class="BodyContainer DashboardContainer" style="text-align:left;">
	
	
	<!--  Page Header Start  -->
	<div class="Heading1" >
		<?php echo $this->Translate('Products_Management'); ?>
	</div>
	<!--  Page Header End  -->
	
	<!--       Success and Error Message      -->	
	<?php if($this->Admin_EMessage != '') { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
				<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
				<strong><?php echo $this->Admin_EMessage; ?></strong></p>
			</div>
		</div>
	<?php } ?>	
	
	<?php if($this->Admin_SMessage != '') { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;"> 
				<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
				<strong><?php echo $this->Admin_SMessage; ?></strong></p>
			</div>
		</div>
	<?php } ?>
	
	<!--   Main Form start     -->
	<form name="frmProduct" id="frmProduct" method="post">
	
		<!--  Buttons start -->
		<div>
			<div style="float:left; margin-top:7px; margin-bottom:10px;">
				<input type="button" id="search" show='1'  value="<?php echo $this->Translate('Search'); ?>" />
			</div>
			<div id="button" style="float:right;">
				<input type="button" id="anything" onclick="Javascript: deleteAllRecords('frmProduct','<?php echo $this->delete_all_action; ?>')"  value="<?php echo $this->Translate('M_Delete'); ?>"/>	   
				<select name="pagesize" id="pagesize" onchange="this.form.submit();">
					<?php
						foreach($this->arr_pagesize as $key => $val){
							echo "<option value='".$key."'". ($key == $this->pagesize ? ' selected ' : '') ." >" . $val . "</option>";
						}
					?>
				</select>
			</div>
		</div>
		<!--  Buttons end -->
	
		<!--  Search Form start     -->
		<div class="toggler box" style="clear:both; ">
			<div id="effect" class='ui-widget-content ui-corner-all' > 					  
				<div style="padding:20px;">	
					<table class="" width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Name'); ?>
							</td>
							<td>
								<input type="text" class="Field250" name="product_name" id="product_name"  />
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Category'); ?>
							</td>
							<td>
								<select name="category_id" id="category_id" class="Field250">
									<option value=""><?php echo $this->Translate('Product_Select_Category'); ?></option>
								<?php  echo $this->category;
									/*if(count($this->category) > 0) {
										foreach($this->category as $key => $val)
										{
											echo "<option value='".$val["category_id"]."'>".$val["category_name"]."</option>";
										}
									}*/
								?>
								</select>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_User'); ?>
							</td>
							<td>
								<select name="user_id" id="user_id" class="Field250">
									<option value="">Select User</option>
								<?php  
									if(count($this->users) > 0) {
										foreach($this->users as $key => $val)
										{
											echo "<option value='".$val["user_id"]."'>".$val["user_fname"]." ".$val["user_lname"]."</option>";
										}
									}
								?>
								</select>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Price'); ?>
							</td>
							<td>
								<?php echo $this->Translate('From'); ?> :<input style="width:90px;" type="text" class="Field250" name="range[]" id="range1"  />
								<?php echo $this->Translate('To'); ?>&nbsp;<input type="text" style="width:90px;" class="Field250" name="range[]" id="range2"  />
							</td> 
						</tr> 
						<tr><td height="15"></td></tr>
						<tr>
						   <td colspan="2">
								<input type="button" id="anything"  onclick="Javascript: SearchRecords(1,'frmProduct');"  value="<?php echo $this->Translate('Search'); ?>" />
								<input type="button" id="anything"  onclick="Javascript: SearchRecords(0,'frmProduct');"  value="<?php echo $this->Translate('Clear'); ?>" />
						   </td>
						</tr>
					</table>
				</div>								
			</div>
		</div>
		<!--  Search Form end     -->
	 
		<div class="Clear"></div>				
 	
		<!--   Records list start   -->
		<div style="margin-top:-10px;" id="table1">		
			<table width="100%" cellpadding="0" cellspacing="0" style="float:left;">
				<tr class="trclass1">
					<td width="5%" class="tdclasshome" style="text-align:left; padding-left:15px;" >
						<?php echo $this->Translate('All'); ?>
					</td>
					<td width="10%" align="center" class="tdclasshome">
						<?php echo $this->Translate('Product_Name'); ?>
					</td>
					<td width="20%" align="center" class="tdclasshome">
						<?php echo $this->Translate('Product_Desc'); ?>
					</td>
					<td width="15%" align="center" class="tdclasshome">
						<?php echo $this->Translate('Product_User'); ?>
					</td>
					<td width="15%" align="center" class="tdclasshome">
						<?php echo $this->Translate('Product_Category'); ?>
					</td>
					<td width="10%" align="center" class="tdclasshome">
						<?php echo $this->Translate('Product_Price'); ?>
					</td>
					<td width="10%" align="center" class="tdclasshome">
						<?php echo $this->Translate('Product_Weight'); ?>
					</td>					
					<td width="15%" align="center" class="tdclasshome bordernone">
						<?php echo $this->Translate('Action'); ?>
					</td>
				</tr>	
	<?php 
				if(count($this->records) > 0) 	{ 
				
					for($i = 0; $i < count($this->records); $i++)
					{
	?>
				<tr id="tr100" class="GridRow" onmouseover="this.className='GridRowOver'" onmouseout="this.className='GridRow'">
					<td class="FieldLabel2" style="padding-left:15px;" >
						<input type="checkbox" name="id[]" id="id[]" value="<?php echo $this->records[$i]['product_id']; ?>">
					</td>					  
					<td class="FieldLabel2" align="left" style="padding-left:10px;">
					<?php echo $this->records[$i]['product_name']; ?></td>
					<td class="FieldLabel2" align="left" style="padding-left:10px;"><?php if(strlen($this->records[$i]['product_description']) > 35 ) { echo substr(strip_tags($this->records[$i]['product_description']), 0, 35)."..."; } else { echo substr(strip_tags($this->records[$i]['product_description']), 0, 35); } ?></td>
					<td class="FieldLabel2" align="center">
						<?php echo $this->records[$i]['user_name']; ?>
					</td>
					<td class="FieldLabel2" align="center">
						<?php 
							$counter = 0;
							for($j = 0; $j < count($this->products); $j++)
							{
							 	if($this->records[$i]['product_id'] == $this->products[$j]['product_id'] ) {
									if($counter == 0) { echo $this->products[$j]['category_name']; }
									else { echo ", ".$this->products[$j]['category_name']; }
									$counter++;
								}
							}
							if($counter == 0) { echo "No Category"; }
						?>
					</td>
					<td class="FieldLabel2" align="center">
						<?php echo $this->records[$i]['product_price']; ?>
					</td>
					<td class="FieldLabel2" align="center">
						<?php echo $this->records[$i]['product_weight']; ?>
					</td>
					<td class="FieldLabel2" align="center">
						<ul id="icons" class="ui-widget ui-helper-clearfix" >
							<li onclick="Javascript: viewRecord(<?php echo $this->records[$i]['product_id']; ?>,'frmProduct','<?php echo $this->view_action; ?>')" class="ui-state-default ui-corner-all" title="<?php echo $this->Translate('View'); ?>">
								<span class="ui-icon ui-icon-document"></span>
							</li>
							<li class="ui-state-default ui-corner-all" onclick="Javascript: editRecord(<?php echo $this->records[$i]['product_id']; ?>,'frmProduct','<?php echo $this->edit_action; ?>')" title="<?php echo $this->Translate('Edit'); ?>">
								<span class="ui-icon ui-icon-pencil"></span>
							</li>
							<li onclick="Javascript: deleteRecord(<?php echo $this->records[$i]['product_id']; ?>,'frmProduct','<?php echo $this->delete_action; ?>')" class="ui-state-default ui-corner-all" title="<?php echo $this->Translate('Delete'); ?>">
								<span class="ui-icon ui-icon-close"></span>
							</li>
						</ul>
					</td>
				</tr>
	<?php 		}
			}	
			else {  	?>
				<tr id="tr100" class="GridRow" onmouseover="this.className='GridRowOver'" onmouseout="this.className='GridRow'">
					<td class="FieldLabel2" colspan="8" align="center"><?php echo $this->Translate('No_record'); ?></td>
				</tr>
	<?php 		 } 		?>				
			
			</table>
			
			
			
			<!--  Pagination start  	 -->
			<div class="box-footer" style="background:none; border:none; float:right; margin-top:10px;">
					<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>					
			</div>
			<!--  Pagination end 		 -->
				
			<!-- 	Hidden field	-->
			<input type="hidden" name="page_no" id="page_no" value="<?php echo $this->page_no; ?>" />
			<input type="hidden" name="is_search" id="is_search" value="<?php echo $this->user_status; ?>" />
			<input type="hidden" name="hidden_primary_id" id="hidden_primary_id" value="" />

		</div>
		<!--   Records list end   -->
	
	</form>
	<!--   Main Form end   -->
	
 	<div class="Clear"></div>	              
</div>

<!--     JS Global Variable for the language    -->

<script language="javascript" type="text/javascript">
	var siteurl = "<?php echo SITE_URL; ?>";
	var HIDE = "<?php echo $this->Translate('Hide'); ?>";  
	var SEARCH = "<?php echo $this->Translate('Search'); ?>";  
</script>


<!--     Dialoag box for the delete and delete all    -->

<div id="dialog-confirm" title="<?php echo $this->Translate('Confirm_Delete_Merchant_Title'); ?>" style="display:none;">
	<div style="text-align:left;">
		<span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
		<?php echo $this->Translate('Confirm_Delete_Merchant'); ?>
	</div>
</div>

<div id="dialog-confirm2" title="<?php echo $this->Translate('Confirm_Delete_Merchant_Title'); ?>" style="display:none;">
	<div style="text-align:left;">
		<span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
		<?php echo $this->Translate('Confirm_M_Delete_Merchant'); ?>
	</div>
</div>