<style>
	.scroll-pane,scroll-pane2
	{
		height: 270px;
		overflow: auto;
		float:left;
	}
</style>


<!--  Crumb  Start -->
<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="#"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Products'); ?></span></li>
	</ul>
</div>
<!--  Crumb  end -->

<!--       Set Record value         -->
<?php  $product_detail = $this->product_detail;  ?>

<div class="BodyContainer DashboardContainer" style="text-align:left;">
	<!--  Page Header Start  -->
	<div class="Heading1" >
		<?php echo $this->Translate('Products_Management'); ?>
	</div>
	<!--  Page Header End  -->
	
	<div class="clear"></div>
	<div style="float:left;">
		<input type="button" id="Back" onclick="window.location='<?php echo $this->site_url; ?>'" value="<?php echo $this->Translate('Back'); ?>" />
	</div>
	<div class="clear"></div>
	
	<div id="content" class="typo">
		<div class="column half fl">
			<div class="Heading2">
				Product Detail
			</div>
			<br />
			<?php $detail = $product_detail["detail"]; ?>
			<div class="box-content" >
				<table  width="100%" >
					<tr>
						<td width="40%" valign="top">
							<h5><?php echo $this->Translate('Product_Name'); ?></h5>
						</td>
						<td width="50%">
							:&nbsp;&nbsp;<?php echo $detail["product_name"]; ?>
						</td>
						
					</tr>
					<tr>
						<td width="40%" valign="top">
							<h5><?php echo $this->Translate('Product_User'); ?></h5>
						</td>
						<td width="60%">
							:&nbsp;&nbsp;<?php echo $detail["user_name"]; ?>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Price'); ?></h5>
						</td>
						<td>
							:&nbsp;&nbsp;<?php echo $detail["product_price"]; ?>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Code'); ?></h5>
						</td>
						<td>
							:&nbsp;&nbsp;<?php echo $detail["product_code"]; ?>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Weight'); ?></h5>
						</td>
						<td>	
							:&nbsp;&nbsp;<?php echo $detail["product_weight"]; ?>&nbsp;<?php echo $detail["weight_unit_key"]; ?>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Length'); ?></h5>
						</td>
						<td>
							:&nbsp;&nbsp;<?php echo $detail["length"]; ?>&nbsp;<?php echo $detail["length_unit_key"]; ?>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Width'); ?></h5>
						</td>
						<td>
							:&nbsp;&nbsp;<?php echo $detail["width"]; ?>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Depth'); ?></h5>
						</td>
						<td>
							:&nbsp;&nbsp;<?php echo $detail["depth"]; ?>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Start_Sales'); ?></h5>
						</td>
						<td>	
							:&nbsp;&nbsp;<?php if($detail["start_sales"] == "1") { echo "Yes"; } else { echo "No"; } ?>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Quantity'); ?></h5>
						</td>
						<td>
							:&nbsp;&nbsp;<?php echo $detail["available_qty"]; ?>
						</td>
					</tr>									
				</table>
			</div>
			<br />
			<div class="Heading2">
				<?php echo $this->Translate('Product_Desc'); ?>
			</div>
			<div class="box-content" >
				<p class="p_left" style="padding-left:5px;"><strong><h5><?php echo $detail["product_name"]; ?>:</h5></strong>
					<br/><?php echo $detail["product_description"]; ?>
				</p>
				<hr/>
			</div>
		</div>
	
		<div class="column half fr">
			<div id="accordion">
				<div>
					<h3><a href="#"><?php echo $this->Translate('Product_Images'); ?></a></h3>
					<?php $images = $product_detail["images"]; ?>
					<div >
						<div style="height:280px; width:395px;">
							<div class="scroll-pane" style="">
								<div class="excersice-list">
									<ul>
										<?php 
											if($images != NULL ) { 
												foreach($images as $key => $val)
												{
													$img_string = str_replace("_img","_th1",$val['image_name']);													
													echo "<li><img src='".SITE_PRODUCT_IMAGES_PATH."/p".$this->product_id."/".$img_string."' width='128' height='128'></li>";
												}
											} else {											
												echo "<li>".$this->Translate('Product_No_Images_Found')."<li>"; 
											}
										?>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div>
					<h3><a href="#"><?php echo $this->Translate('Product_Properties'); ?></a></h3>
					<div >
						<?php $category = $product_detail["category"]; ?>
						<?php $options = $product_detail["options"]; ?>
						<div class="box-content scroll-pane" style="height:270px; width:395px;" >
							
							<table  width="100%" >
								<tr>
									<td width="40%" valign="top">
										<h5><?php echo $this->Translate('Product_Category'); ?></h5>
									</td>
									<td width="60%">
										<ul class="circle width100 fl">
											<?php  
												if($category != NULL) {
													
													foreach($category as $key =>$val)
													{
														echo "<li>".$val["category_name"]."</li>";
													}
													
												} else {
													echo "<li>".$this->Translate('Product_No_Category_Found')."</li>";
												}
											
											?>						
										</ul>
									</td>
								</tr>
								<tr>
									<td width="40%" valign="top">
										<h5><?php echo $this->Translate('Product_Options'); ?></h5>
									</td>
									<td width="60%">
										<ul class="circle width100 fl">
											<?php  
												if($options != NULL) {
													$option_value = '';
													foreach($options as $key =>$val)
													{
														if($val["LNK_options_id"] != $option_value)
														{
															echo "<li>".$val["option_title"]."<ul class='circle'>";
															foreach($options as $key =>$val2)
															{
																if($val["LNK_options_id"] == $val2["LNK_options_id"]) {
																echo "<li>".$val2["option_value"]."</li>";
																}
															}
															echo "</ul></li>";
														}
														$option_value = $val["product_options_id"];
													}
													
												} else {
													echo "<li>".$this->Translate('Product_No_Options_Found')."</li>";
												}
											
											?>						
										</ul>
									</td>
								</tr>
							</table>
							
						</div>
					</div>
				</div>
				
			</div>
			
		</div>
	
       	<div class="clear"></div>
	</div>               
</div>

<script type="text/javascript">
	$(function(){
		$('.scroll-pane').jScrollPane();
		// Accordion
		$("#accordion").accordion({ header: "h3",autoHeight: false, navigation: true });
		
		
	});
</script>