 
<div id="rightColumn">
	<div class="mainColumnWidget">
		<div style="float:left">
			<img src="<?php echo IMAGES_FB_PATH ?>/Default.gif" alt="Default" height="50" width="50" style="margin:5px;" />
		</div>
		<div class="categoryHeader" style="float:left; width:85%;">
		  <?php echo $this->StoreName;?> 
		  <div style="margin-top:5px;">
		  	<iframe src="//www.facebook.com/plugins/like.php?href=<?php echo urlencode(SITE_FB_URL . "retailer/view/id/" . $this->RetailerId); ?>&amp;send=false&amp;layout=button_count&amp;width=90&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:90px; height:21px;" allowTransparency="true"></iframe>
		  </div>
		  <div style="border-top:1px solid #E2E2E2; margin-top:5px;"></div>
		  <div>
			<img alt="" src="/Puvoo/images/fb/card_graphic.png" class="sellerInfo">
			<a style="color: #000;" href="javascript:void(0)" id="btn1"><?php echo $this->Translate('SellerInfo')?></a>
          </div>
		</div>
		<div style="clear:both"></div>
		<form name="frmcatproduct" method="get" id="frmcatproduct" action="<?php echo SITE_FB_URL;?>retailer/view/id/<?php echo $this->retailerId;?>" target="_top">
		<div class="portlet">
			 <div class="bluewidgetHeader">
				   <div style="float:left;">
						<select id="sortBy" style="width:150px;" name="sortBy" onchange="this.form.submit();">
                                                                        
							<!--<option value="bestseller" <?php echo $this->bestseller;?>><?php echo $this->Translate('BestSeller')?></option>
							<option value="most_liked" <?php echo $this->most_liked;?>><?php echo $this->Translate('MostLiked')?></option>-->
							<option value="price_asc" <?php echo $this->price_asc;?>><?php echo $this->Translate('LowToHigh')?></option>
							<option value="price_desc" <?php echo $this->price_desc;?>><?php echo $this->Translate('HighToLow')?></option>
                         </select>
					</div>
					 <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_top.phtml'); ?>
					<div style="clear:both;"></div>
			</div>
		 </div>
		<div class="portlet" style="border-bottom:1px solid #E2E2E2">
				<div class="productListingNav">
				   <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_bottom.phtml'); ?>
				</div>
				<div style="clear:both"></div>
			</div>
		<div id="productGridView" class="portlet">
		<?php foreach($this->records as $prodval){?>
			<?php 
				if($prodval['ProdName'] != '')
				{
					$prodName = $prodval['ProdName'];
				}else{
					$prodName = $prodval['product_name'];
				}
			?>
			<div class="productGridItem productGridItemTopRow firstborder">
				<div class="thumbnailImage" style="margin-top:14px;">
				
					 <?php
						$SmallImg = str_replace('img','th1',$prodval['image_name']);
						$tinyImage = SITE_PRODUCT_IMAGES_PATH.$prodval['image_path']."/".$SmallImg;	
						$ThumbImage = SITE_PRODUCT_IMAGES_PATH.$prodval['image_path']."/".$prodval['image_name'];
					 ?>
				
					<a target="_top" url="<?php echo $ThumbImage;?>" class="preview" style="cursor:pointer" href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $prodval['product_id'];?>">
					
					<?php if(!$prodval['image_name']){?>
						<img class="img" src="<?php echo IMAGES_FB_PATH ?>/Default.gif" alt="Default" title="Default"/>
					<?}else{?>
					
 						<img class="img" src="<?php echo $tinyImage;?>" width="128" alt="<?php echo $prodName; ?>" title="<?php echo $prodName; ?>"/>
					<?}?>
					</a>
				</div>
				<div class="productTitle">
					<a target="_top" href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $prodval['product_id'];?>"><?php echo $prodName; ?></a> 
				</div>
				<div class="productPrice">
				  <?php echo DEFAULT_CURRENCY_SYMBOL."&nbsp;".$prodval['prod_convert_price']."&nbsp;".DEFAULT_CURRENCY_CODE;?>
				</div>
				<div class="socialbtn">
					<div class="left">
						<iframe src="//www.facebook.com/plugins/like.php?href=<?php echo urlencode(SITE_FB_URL . "product/view/id/" . $prodval['product_id']); ?>&amp;send=true&amp;layout=button_count&amp;width=90&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:90px; height:21px;" allowTransparency="true"></iframe>
					</div>
				   <div style="text-align: right;">
					   <div class="share" id="shareLinkContGrid_lls1">
							<div id="fb-root"></div>
							<script>(function(d, s, id) {
							  var js, fjs = d.getElementsByTagName(s)[0];
							  if (d.getElementById(id)) {return;}
							  js = d.createElement(s); js.id = id;
							  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
							  fjs.parentNode.insertBefore(js, fjs);
							}(document, 'script', 'facebook-jssdk'));</script>
							
							<fb:send href="<?php echo SITE_FB_URL . "product/view/id/" . $prodval['product_id']; ?>"></fb:send>
					   </div>
						<div style="clear: both;"></div>
	
					</div>
					<div style="clear: both"></div>
				 </div>    
			 </div>
		  <?php }?>   
		 </div>   
	</div>
	<div class="portlet">
		<div class="productListingNav">
		   
		<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_bottom.phtml'); ?>
		</div>
		<input type="hidden" name="page_no" id="page_no" value="<?php echo $this->page_no; ?>" />

		<div style="padding-bottom:10px; clear:both"></div>
	</div>
	</form>
	<!--<script type="text/javascript">
		$(document).ready(function(){
			$("#slider1").easySlider({
				auto: false,
				continuous: false,
				nextId: "slidernext",
				prevId: "sliderprev",
				prevText: "",
				nextText: "",
				controlsShow: false
			});

			$("#slidernext").show();
			$("#sliderprev").show();
		});
	</script>-->
   
</div>