<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="<?php echo SITE_URL; ?>admin/"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last1"><a href="<?php echo SITE_URL; ?>admin/banner"><?php echo $this->Translate('Banner'); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Edit_Banner'); ?></span></li>
	</ul>
</div>

<!--       Set Record value         -->
<?php  $edit_record = $this->records;  ?>

<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate('Manage_Facebook_Banner'); ?>
	</div>
	
	<?php if(count($this->editErrorMessage) > 0 ) { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
				<?php foreach($this->editErrorMessage as $key => $val ) { ?>
					<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
					<strong><?php echo $val; ?></strong></p>
				<?php } ?>
			</div>
		</div>
	<?php } ?>	
	
	<form method="post" name="edit_form" id="edit_form" enctype="multipart/form-data" >
		<table class="Panel" style="margin-top:10px;">
			<tr>
				<td class="Heading2" colspan="2"><?php echo $this->Translate('Edit_Banner'); ?></td>
			</tr>
			<tr>
				<td colspan="2">
				<div id="div0" style="padding-bottom:5px">
					<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
						
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Status_Value'); ?>
							</td>
							<td>
								<input type="text" name="status_value" id="status_value" class="Field250"  value="<?php echo $edit_record['status_value']; ?>"/>
								<span></span>
							</td>
						</tr>
						
						<tr><td height="15"></td></tr>
						<tr>
						   	<td colspan="2">
								<input type="submit" onclick="Javascript: return ValidateEditFrom()" value="<?php echo $this->Translate('Submit'); ?>" />
								<input type="button" value="<?php echo $this->Translate('Cancle'); ?>" onclick="window.location='<?php echo $this->site_url; ?>'"/>
						   </td>
						</tr>
					</table>
				</div>
				</td>
			</tr>
		</table>   
		
		<!--         Hidden fields                       -->
		<input type="hidden" name="order_status_id" id="order_status_id" value="<?php echo $this->order_status_id; ?>" />
		
	</form>            
</div> 

<!--     JS Global Variable for the language    -->

<script language="javascript" type="text/javascript">
var siteurl = "<?php echo SITE_URL; ?>";
var ERR_STATUS_VALUE = "<?php echo $this->Translate('Err_Status_Value'); ?>";  

function ValidateEditFrom()
{
	
	$("#edit_form").validate({
							
		rules: {
					status_value: { required: true },					
			   },
			   
		messages:{
					status_value: { required: ERR_STATUS_VALUE },					
				 },
				 
		errorPlacement: function(error, element) 
		{ 
			error.appendTo( element.next() ); 
		}
	});
}

</script>