<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="#"><?php echo $this->Translate("User_Home"); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Change_Password'); ?></span></li>
	</ul>
</div>

<div class="BodyContainer DashboardContainer" style="text-align:left;">
	<div class="Heading1">
		<?php echo $this->Translate('Change_Password'); ?>
	</div>

<!--       Success and Error Message      -->
	<?php if($this->updateError != '') { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
				<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
				<strong><?php echo $this->updateError; ?></strong></p>
			</div>
		</div>
	<?php } ?>	
	<?php if($this->updateSuccess != '') { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;"> 
				<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
				<strong><?php echo $this->updateSuccess; ?></strong></p>
			</div>
		</div>
	<?php } ?>


	<form method="post" name="changepassword_form" id="changepassword_form" >
		<table class="Panel" style="margin-top:10px;">
			<tr>
				<td class="Heading2" colspan="2"><?php echo $this->Translate('Change_Password'); ?></td>
			</tr>
			<tr>
				<td colspan="2">
					<div id="div0" style="padding-bottom:5px">
						<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
							<tr>
								<td class="FieldLabel">
									<span class="Required">*</span>&nbsp;<?php echo $this->Translate('Old_Password'); ?>:
								</td>
								<td>
									<input value="<?php echo $this->old_password; ?>" type="password" name="old_password" id="old_password" class="Field250" />
									<span></span>
								</td>
							</tr>
							<tr><td height="5"></td></tr>
							 <tr>
								<td class="FieldLabel">
									<span class="Required">*</span>&nbsp;<?php echo $this->Translate('New_Password'); ?>:
								</td>
								<td>
									<input value="<?php echo $this->new_password; ?>" type="password" name="new_password" id="new_password" class="Field250" />
									<span></span>
								</td>
							</tr>
							<tr><td height="5"></td></tr>
							 <tr>
								<td class="FieldLabel">
									<span class="Required">*</span>&nbsp;<?php echo $this->Translate('Confirm_Password'); ?>:
								</td>
								<td>
									<input value="<?php echo $this->confirm_password; ?>" type="password" name="confirm_password" id="confirm_password" class="Field250" />
									<span></span>
								</td>
							</tr>
							<tr><td height="15"></td></tr>
							<tr>
							   <td colspan="2" style="padding-left:10px;">
									<input type="submit" id="anything"  value="<?php echo $this->Translate('Update'); ?>" />
									<input type="button" id="anything"  value="<?php echo $this->Translate('Cancle'); ?>" onclick="window.location='<?php echo SITE_URL . 'user/' ?>'"/>
								</td>
							</tr> <tr><td height="15"></td></tr>
						</table>
					</div>
				</td>
			</tr>
		</table>  
	</form>             
</div>

<!--     JS Global Variable for the language    -->
<script language="javascript" type="text/javascript">
	
	var OLD_PASSWORD_NEEDED = "<?php echo $this->Translate('Err_Old_Password'); ?>";
	var PASSWORD_CHARACTER_LIMIT = "<?php echo $this->Translate('Err_Password_Character_Limit'); ?>"; 
	var EMPTY_NEW_PASSWORD = "<?php echo $this->Translate('Err_New_Password'); ?>"; 
	var EMPTY_CONFIRM_PASSWORD = "<?php echo $this->Translate('Err_Empty_Confirm_Password'); ?>";  
	var PASSWORD_MISMATCH = "<?php echo $this->Translate('Err_Confirm_Password'); ?>";   
</script>