
Coming Soon

<script language="javascript" type="text/javascript">
	
	var OLD_PASSWORD_NEEDED = "<?php echo $this->Translate('Err_Old_Password'); ?>";
	var PASSWORD_CHARACTER_LIMIT = "<?php echo $this->Translate('Err_Password_Character_Limit'); ?>"; 
	var EMPTY_NEW_PASSWORD = "<?php echo $this->Translate('Err_New_Password'); ?>"; 
	var EMPTY_CONFIRM_PASSWORD = "<?php echo $this->Translate('Err_Empty_Confirm_Password'); ?>";  
	var PASSWORD_MISMATCH = "<?php echo $this->Translate('Err_Confirm_Password'); ?>";   
</script>