<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="#"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last1"><a href="<?php echo SITE_URL; ?>admin/weightunit"><?php echo $this->Translate('Weightunit'); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Add_Weightunit'); ?></span></li>
	</ul>
</div>


<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate('Manage_Weightunit'); ?>
	</div>
	
	<?php if(count($this->addErrorMessage) > 0 ) { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
				<?php foreach($this->addErrorMessage as $key => $val ) { ?>
					<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
					<strong><?php echo $val; ?></strong></p>
				<?php } ?>
			</div>
		</div>
	<?php } ?>	
	
	<form method="post" name="add_form" id="add_form" >
		<table class="Panel" style="margin-top:10px;">
			<tr>
				<td class="Heading2" colspan="2"><?php echo $this->Translate('Add_Weightunit'); ?></td>
			</tr>
			<tr>
				<td colspan="2">
				<div id="div0" style="padding-bottom:5px">
					<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('From_Id'); ?>
							</td>
							<td>
								<select name="from_id" id="from_id" class="Field250">
									<option value="0" selected="selected">Select</option>
									<?php if(count($this->weight) > 0) {  ?>
									<?php  		foreach($this->weight as $key => $val) { ?>	
									<?php			if($this->data['from_id'] != '' && $this->data['from_id'] == $val['weight_unit_id'] )  { ?>
									<option selected="selected" value="<?php echo $val['weight_unit_id']; ?>">
									<?php 			} else { ?>
									<option value="<?php echo $val['weight_unit_id']; ?>">
									<?php 			} ?>
									<?php 			echo $val["weight_unit_name"];  ?>	
									</option>
									<?php 		}  ?>
									<?php } else {  ?>
									<?php }  ?>
								</select>
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('To_Id'); ?>
							</td>
							<td>
								<select name="to_id" id="to_id" class="Field250">
									<option value="0" selected="selected">Select</option>
									<?php if(count($this->weight) > 0) {  ?>
									<?php  		foreach($this->weight as $key => $val) { ?>	
									<?php			if($this->data['to_id'] != '' && $this->data['to_id'] == $val['weight_unit_id'] )  { ?>
									<option selected="selected" value="<?php echo $val['weight_unit_id']; ?>">
									<?php 			} else { ?>
									<option value="<?php echo $val['weight_unit_id']; ?>">
									<?php 			} ?>
									<?php 			echo $val["weight_unit_name"];  ?>	
									</option>
									<?php 		}  ?>
									<?php } else {  ?>
									<?php }  ?>
								</select>
								<span></span>
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Value'); ?>
							</td>
							<td>
								<input type="text" value="<?php echo $this->data['value']; ?>" name="value" id="value" class="Field250"  />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						<tr>
						   	<td colspan="2">
								<input type="submit" id="anything" onclick="Javascript: return ValidateAddFrom()"  value="<?php echo $this->Translate('Submit'); ?>" />
								<input type="button" id="anything"  value="<?php echo $this->Translate('Cancle'); ?>" onclick="window.location='<?php echo $this->site_url; ?>'"/>
						   </td>
						</tr>
					</table>
				</div>
				</td>
			</tr>
		</table>   
	</form>            
</div> 

<!--     JS Global Variable for the language    -->

<script language="javascript" type="text/javascript">
var siteurl = "<?php echo SITE_URL; ?>";
var ERR_WEIGHT_From_Id = "<?php echo $this->Translate('Err_Weight_From_Id'); ?>";  
var ERR_WEIGHT_To_Id = "<?php echo $this->Translate('Err_Weight_To_Id'); ?>";  
var ERR_WEIGHT_Value = "<?php echo $this->Translate('Err_Weight_Value'); ?>";  
</script>