<div class="version"><?php echo PUVOO_VERSION; ?></div>
<div>
	<img src="<?php echo IMAGES_PATH; ?>/admin/sep.png" alt="" />
</div>
<div class="footercontent">
<div>You can redistribute this program and/or modify it under the terms of <a href="http://www.opensource.org/licenses/osl-3.0.php" target="_blank">The Open Software License v. 3.0</a> as published by OSI.</div>
<div style="margin-bottom:10px;">Copyright © 2011 <a href="http://www.puvoo.com" target="_blank">Puvoo&trade;</a>. All companies and products names may be trademarks of the respective companies with which they are associated.</div>
</div>
<div>
	<img src="<?php echo IMAGES_PATH; ?>/admin/sep.png" alt="" />
</div>

<script language="javascript" type="text/javascript">
	
	var RECO_DELETE = "<?php echo $this->Translate('Delete'); ?>";  
	var RECO_DELETEALL = "<?php echo $this->Translate('Delete_All'); ?>";  
	var RECO_CANCLE = "<?php echo $this->Translate('Cancel'); ?>";  
	
	$(function() {
		$( ".button,input:button,input:submit" ).button();
	});

</script>