<div class="version">Puvoo&trade; v. 1.0.0 ALPHA</div>
<div>
	<img src="<?php echo IMAGES_PATH; ?>/admin/sep.png" alt="" />
</div>
<div class="footercontent">
	
You can redistribute this program and/or modify it under the terms of <a href="http://www.opensource.org/licenses/osl-3.0.php" target="_blank">The Open Software License v. 3.0</a> as published by OSI.<br />
<a href="http://www.puvoo.com" target="_blank">Puvoo&trade;</a> - Copyright © 2011. All companies and products names may be trademarks of the respective companies with which they are associated.<br />
	
</div>
<div>
	<img src="<?php echo IMAGES_PATH; ?>/admin/sep.png" alt="" />
</div>

<script language="javascript" type="text/javascript">
	
	$(function() {
		$( ".button,input:button,input:submit" ).button();
	});

</script>
