<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="<?php echo SITE_URL; ?>admin/"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last1"><a href="<?php echo SITE_URL; ?>admin/languages"><?php echo $this->Translate('Languages'); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Add_Language'); ?></span></li>
	</ul>
</div>


<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate('Manage_Languages'); ?>
	</div>
	
	<?php if(count($this->addErrorMessage) > 0 ) { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
				<?php foreach($this->addErrorMessage as $key => $val ) { ?>
					<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
					<strong><?php echo $val; ?></strong></p>
				<?php } ?>
			</div>
		</div>
	<?php } ?>	
	
	<form method="post" name="add_form" id="add_form" >
		<table class="Panel" style="margin-top:10px;">
			<tr>
				<td class="Heading2" colspan="2"><?php echo $this->Translate('Add_Language'); ?></td>
			</tr>
			<tr>
				<td colspan="2">
				<div id="div0" style="padding-bottom:5px">
					<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Language_Name'); ?>
							</td>
							<td>
								<input type="text" name="name" id="name" class="Field250" value="<?php echo $this->data['name']; ?>" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Code'); ?>:
							</td>
							<td>
								<input type="text" name="code" id="code" class="Field250" value="<?php echo $this->data['code']; ?>" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Characterset'); ?>:
							</td>
							<td>
								<input type="text" name="charset" id="charset" class="Field250" value="<?php echo $this->data['charset']; ?>" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Short_Date_Format'); ?>:
							</td>
							<td>
								<select name="date_format_short" id="date_format_short" class="Field250" >
									<option value="m/d/Y" <?php echo ($this->data['date_format_short'] == 'm/d/Y' ? 'selected' : '' ); ?> ><?php echo date('m/d/Y'); ?></option>
									<option value="d/m/Y" <?php echo ($this->data['date_format_short'] == 'd/m/Y' ? 'selected' : '' ); ?> ><?php echo date('d/m/Y'); ?></option>
								</select>
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Long_Date_Format'); ?>:
							</td>
							<td>
								<select name="date_format_long" id="date_format_long" class="Field250" >
									<option value="D M j, Y" <?php echo ($this->data['date_format_long'] == 'D M j, Y' ? 'selected' : '' ); ?>><?php echo date('D M j, Y'); ?></option>
									<option value="D F j, Y" <?php echo ($this->data['date_format_long'] == 'D M j, Y' ? 'selected' : '' ); ?>><?php echo date('D F j, Y'); ?></option>
								</select>
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Time_Format'); ?>:
							</td>
							<td>
								<select name="time_format" id="time_format" class="Field250" >
									<option value="H:m:s" <?php echo ($this->data['time_format'] == 'H:m:s' ? 'selected' : '' ); ?> ><?php echo date('H:m:s'); ?></option>
									<option value="h:i:s A" <?php echo ($this->data['time_format'] == 'h:i:s A' ? 'selected' : '' ); ?> ><?php echo date('h:i:s A'); ?></option>
								</select>
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Text_Direction'); ?>:
							</td>
							<td>
								<select name="text_direction" id="text_direction" class="Field250" >
									<option value="ltr" <?php echo ($this->data['text_direction'] == 'ltr' ? 'selected' : '' ); ?> >ltr</option>
									<option value="rtl" <?php echo ($this->data['text_direction'] == 'rtl' ? 'selected' : '' ); ?>>rtl</option>
								</select>
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Decimal_Numeric_Separator'); ?>:
							</td>
							<td>
								<input type="text" name="numeric_separator_decimal" id="numeric_separator_decimal" class="Field250" maxlength="1" value="<?php echo $this->data['numeric_separator_decimal']; ?>" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Thousands_Numeric_Separator'); ?>:
							</td>
							<td>
								<input type="text" name="numeric_separator_thousands" id="numeric_separator_thousands" class="Field250" maxlength="1" value="<?php echo $this->data['numeric_separator_thousands']; ?>" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Country'); ?>:
							</td>
							<td>
								<select name="country_id" id="country_id" class="Field250">
									<option selected="selected" value=""><?php echo $this->Translate("Select_Country"); ?></option>
		<?php 						foreach( $this->country as $key => $val ) 
									{ 
										if( $val["country_id"] ==  $this->data['country_id'] )	{
		?>
											<option selected="selected" value="<?php echo $val['country_id']; ?>"><?php echo $val["country_name"]; ?></option>
		<?php							} else {
		?>
											<option value="<?php echo $val['country_id']; ?>"><?php echo $val["country_name"]; ?></option>								
		<?php 							}		
									} 								
		?>
								</select>
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Currency'); ?>:
							</td>
							<td>
								<select name="currency_id" id="currency_id" class="Field250">
									<option selected="selected" value=""><?php echo $this->Translate("Select_Currency"); ?></option>
		<?php 						foreach( $this->currency as $key => $val ) 
									{ 
										if( $val["currency_id"] ==  $this->data['currency_id'] )	{
		?>
											<option selected="selected" value="<?php echo $val['currency_id']; ?>"><?php echo $val["currency_name"]." (".$val["currency_code"].")"; ?></option>
		<?php							} else {
		?>
											<option value="<?php echo $val['currency_id']; ?>"><?php echo $val["currency_name"]." (".$val["currency_code"].")"; ?></option>								
		<?php 							}		
									} 								
		?>
								</select>
								
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Vat'); ?>:
							</td>
							<td>
								<input type="text" name="vat" id="vat" class="Field250" value="<?php echo $this->records['vat']; ?>" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Is_Default'); ?>:
							</td>
							<td>
								<span>
									<input type="radio" name="is_default" id="is_default" class="" value="1" <?php echo (($this->data['is_default'] == '1' || $this->data['is_default'] == '') ? 'checked' : '' ); ?> />
									<?php echo $this->Translate('L_Yes'); ?>&nbsp;
									<input type="radio" name="is_default"  value="0" <?php echo ($this->data['is_default'] == '0' ? 'checked' : '' ); ?> />
									<?php echo $this->Translate('L_No'); ?>
								</span>
								<span></span>
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('User_Status'); ?>:
							</td>
							<td>
								<span>
									<input type="radio" name="status" id="status" class="" value="1" <?php echo (($this->data['status'] == '1' || $this->data['status'] == '') ? 'checked' : '' ); ?> />
									<?php echo $this->Translate('Admin_User_Status_Active'); ?>&nbsp;
									<input type="radio" name="status"  value="0" <?php echo ($this->data['status'] == '0' ? 'checked' : '' ); ?> />
									<?php echo $this->Translate('Admin_User_Status_Inactive'); ?>
								</span>
								<span></span>
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						<tr>
						   	<td colspan="2">
								<input type="submit" id="anything" onclick="Javascript: return ValidateAddForm()"  value="<?php echo $this->Translate('Submit'); ?>" />
								<input type="button" id="anything"  value="<?php echo $this->Translate('Cancle'); ?>" onclick="window.location='<?php echo $this->site_url; ?>'"/>
						   </td>
						</tr>
					</table>
				</div>
				</td>
			</tr>
		</table>   
	</form>            
</div> 

<!--     JS Global Variable for the language    -->

<script language="javascript" type="text/javascript">
var siteurl = "<?php echo SITE_URL; ?>";
var ERR_LANGUAGE_NAME = "<?php echo $this->Translate('Err_Language_Name'); ?>";  
var ERR_LANGUAGE_CODE = "<?php echo $this->Translate('Err_Language_Code'); ?>";  
var ERR_LANGUAGE_CHARSET = "<?php echo $this->Translate('Err_Language_Charset'); ?>";  
var ERR_LANGUAGE_DECIMAL = "<?php echo $this->Translate('Err_Language_Decimal'); ?>";  
var ERR_LANGUAGE_THOUSANDS = "<?php echo $this->Translate('Err_Language_Thousands'); ?>";
var ERR_LANGUAGE_COUNTRY = "<?php echo $this->Translate('Err_Language_Country'); ?>";
var ERR_LANGUAGE_CURRENCY = "<?php echo $this->Translate('Err_Language_Currency'); ?>";  

</script>