<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="#"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Languages'); ?></span></li>
	</ul>
</div>

<!--       Set Record value         -->
<?php  $edit_record = $this->records;  ?>

<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate('Manage_Languages'); ?>
	</div>
	
	<?php if(count($this->editErrorMessage) > 0 ) { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
				<?php foreach($this->editErrorMessage as $key => $val ) { ?>
					<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
					<strong><?php echo $val; ?></strong></p>
				<?php } ?>
			</div>
		</div>
	<?php } ?>	
	
	<form method="post" name="edit_form" id="edit_form" >
		<table class="Panel" style="margin-top:10px;">
			<tr>
				<td class="Heading2" colspan="2"><?php echo $this->Translate('Edit_Language'); ?></td>
			</tr>
			<tr>
				<td colspan="2">
				<div id="div0" style="padding-bottom:5px">
					<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Language_Name'); ?>
							</td>
							<td>
								<input type="text" name="name" id="name" class="Field250" value="<?php echo $this->records['name']; ?>" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Code'); ?>:
							</td>
							<td>
								<input type="text" name="code" id="code" class="Field250" value="<?php echo $this->records['code']; ?>" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Characterset'); ?>:
							</td>
							<td>
								<input type="text" name="charset" id="charset" class="Field250" value="<?php echo $this->records['charset']; ?>" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Short_Date_Format'); ?>:
							</td>
							<td>
								<select name="date_format_short" id="date_format_short" class="Field250" >
									<option value="m/d/Y" <?php echo ($this->records['date_format_short'] == "m/d/Y" ? "selected" : ""); ?> ><?php echo date('m/d/Y'); ?></option>
									<option value="d/m/Y" <?php echo ($this->records['date_format_short'] == "d/m/Y" ? "selected" : ""); ?> ><?php echo date('d/m/Y'); ?></option>
								</select>
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Long_Date_Format'); ?>:
							</td>
							<td>
								<select name="date_format_long" id="date_format_long" class="Field250" >
									<option value="D M j, Y" <?php echo ($this->records['date_format_long'] == "D M j, Y" ? "selected" : ""); ?> ><?php echo date('D M j, Y'); ?></option>
									<option value="D F j, Y" <?php echo ($this->records['date_format_long'] == "D F j, Y" ? "selected" : ""); ?> ><?php echo date('D F j, Y'); ?></option>
								</select>
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Time_Format'); ?>:
							</td>
							<td>
								<select name="time_format" id="time_format" class="Field250" >
									<option value="H:m:s" <?php echo ($this->records['time_format'] == "H:m:s" ? "selected" : ""); ?> ><?php echo date('H:m:s'); ?></option>
									<option value="h:i:s A" <?php echo ($this->records['time_format'] == "h:i:s A" ? "selected" : ""); ?> ><?php echo date('h:i:s A'); ?></option>
								</select>
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Text_Direction'); ?>:
							</td>
							<td>
								<select name="text_direction" id="text_direction" class="Field250" >
									<option value="ltr" <?php echo ($this->records['text_direction'] == "ltr" ? "selected" : ""); ?> >ltr</option>
									<option value="rtl" <?php echo ($this->records['text_direction'] == "rtl" ? "selected" : ""); ?> >rtl</option>
								</select>
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Decimal_Numeric_Separator'); ?>:
							</td>
							<td>
								<input type="text" name="numeric_separator_decimal" id="numeric_separator_decimal" class="Field250" maxlength="1" value="<?php echo $this->records['numeric_separator_decimal']; ?>" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Thousands_Numeric_Separator'); ?>:
							</td>
							<td>
								<input type="text" name="numeric_separator_thousands" id="numeric_separator_thousands" class="Field250" maxlength="1" value="<?php echo $this->records['numeric_separator_thousands']; ?>" />
								<span></span>
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('User_Status'); ?>:
							</td>
							<td>
								<span>
									<input type="radio" name="status" id="status" class="" value="1" <?php echo ($this->records["status"] == 1 ? "checked" : ""); ?> />
									<?php echo $this->Translate('Admin_User_Status_Active'); ?>&nbsp;
									<input type="radio" name="status"  value="0" <?php echo ($this->records["status"] == 0 ? "checked" : ""); ?> />
									<?php echo $this->Translate('Admin_User_Status_Inactive'); ?>
								</span>
								<span></span>
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						<tr>
						   	<td colspan="2">
								<input type="submit" onclick="Javascript: return ValidateEditFrom()" value="<?php echo $this->Translate('Submit'); ?>" />
								<input type="button" value="<?php echo $this->Translate('Cancle'); ?>" onclick="window.location='<?php echo $this->site_url; ?>'"/>
						   </td>
						</tr>
					</table>
				</div>
				</td>
			</tr>
		</table>   
		
		<!--         Hidden fields                       -->
		<input type="hidden" name="language_id" id="language_id" value="<?php echo $this->language_id; ?>" />
		
	</form>            
</div> 

<script language="javascript" type="text/javascript">
var siteurl = "<?php echo SITE_URL; ?>";
var ERR_LANGUAGE_NAME = "<?php echo $this->Translate('Err_Language_Name'); ?>";  
var ERR_LANGUAGE_CODE = "<?php echo $this->Translate('Err_Language_Code'); ?>";  
var ERR_LANGUAGE_CHARSET = "<?php echo $this->Translate('Err_Language_Charset'); ?>";  
var ERR_LANGUAGE_DECIMAL = "<?php echo $this->Translate('Err_Language_Decimal'); ?>";  
var ERR_LANGUAGE_THOUSANDS = "<?php echo $this->Translate('Err_Language_Thousands'); ?>";  

</script>