 
<div id="rightColumn">
	<div class="mainColumnWidget">
		<?php if($this->parentcat_id == '0'){?>
			<div id="breadCrumb">
				<ul>
					<li>
						<a target="_top" href="<?php echo SITE_FB_URL;?>">
							<img title="home" alt="home" src="<?php echo IMAGES_FB_PATH ?>/home.png"/>
						</a>
					</li>
					<li>
						<a target="_top" href="<?php echo SITE_FB_URL;?>category/subcat/id/<?php echo $this->cat_id ?>"><?php echo $this->catname?></a>
					</li>
				</ul>
			</div>
		<?php }else{?>
			<div id="breadCrumb">
				<ul>
					<li>
						<a target="_top" href="<?php echo SITE_FB_URL;?>">
							<img title="home" alt="home" src="<?php echo IMAGES_FB_PATH ?>/home.png"/>
						</a>
					</li>
					<li>
						<a target="_top" href="<?php echo SITE_FB_URL;?>category/subcat/id/<?php echo $this->parentcat_id ?>"><?php echo $this->parentcat_name?></a>
					</li>
					<li>
						<a target="_top" href="<?php echo SITE_FB_URL;?>category/subcat/id/<?php echo $this->cat_id ?>"><?php echo $this->catname?></a>
					</li>
 				</ul>
			</div>
		<?php }?>
		<div class="categoryHeader">
		   <?php echo $this->Translate('Category')?>: <?php echo $this->catname?> 
		</div>
		<form name="frmcatproduct" method="post" id="frmcatproduct" action="">
		<?php if(count($this->records) > 0){?>
		<div class="portlet">
			 <div class="bluewidgetHeader">
				   <div style="float:left;">
						<select id="sortBy" style="width:150px;" name="sortBy" onchange="this.form.submit();">
                                                                        
							<option value="bestseller" <?php echo $this->bestseller;?>><?php echo $this->Translate('BestSeller')?></option>
							<option value="most_liked" <?php echo $this->most_liked;?>><?php echo $this->Translate('MostLiked')?></option>
							<option value="price_asc" <?php echo $this->price_asc;?>><?php echo $this->Translate('LowToHigh')?></option>
							<option value="price_desc" <?php echo $this->price_desc;?>><?php echo $this->Translate('HighToLow')?></option>
                         </select>
					</div>
					 <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_top.phtml'); ?>
					<div style="clear:both;"></div>
			</div>
		 </div>
		<div class="portlet" style="border-bottom:1px solid #E2E2E2">
				<div class="productListingNav">
				   <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_bottom.phtml'); ?>
				</div>
				<div style="clear:both"></div>
		</div>
		<?php }else{?>
							<div style="font-size:12px; padding: 8px 10px 9px; border-bottom: 1px solid #E2E2E2;">
								<p>"<?php echo $this->Translate('NoProduct')?>"</p>
							</div>
						<?php }?> 
		<div id="productGridView" class="portlet">
		<?php foreach($this->records as $prodval){?>
			<div class="productGridItem productGridItemTopRow firstborder">
				<div class="thumbnailImage" style="margin-top:14px;">
					<a target="_top" href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $prodval['product_id'];?>">
					
					<?php if(!$prodval['image_name']){?>
						<img class="img" src="<?php echo IMAGES_FB_PATH ?>/Default.gif"/>
					<?}else{?>
 						<img class="img" src="<?php echo SITE_PRODUCT_IMAGES_PATH.$prodval['image_path'] ?>/<?php echo $prodval['image_name'] ?>" width="128"/>
					<?}?>
					</a>
				</div>
				<div class="productTitle">
					<a target="_top" href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $prodval['product_id'];?>"><?php echo $prodval['product_name'];?></a> 
				</div>
				<div class="productPrice">
				   <?php echo "$".$prodval['product_price']." (USD)";?>
				</div>
				<div class="socialbtn">
					<div class="left">
						<iframe src="//www.facebook.com/plugins/like.php?href=<?php echo urlencode(SITE_FB_URL . "product/view/id/" . $prodval['product_id']); ?>&amp;send=true&amp;layout=button_count&amp;width=90&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:90px; height:21px;" allowTransparency="true"></iframe>
					</div>
				   <div style="text-align: right;">
					   <div class="share" id="shareLinkContGrid_lls1">
							<div id="fb-root"></div>
							<script>(function(d, s, id) {
							  var js, fjs = d.getElementsByTagName(s)[0];
							  if (d.getElementById(id)) {return;}
							  js = d.createElement(s); js.id = id;
							  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
							  fjs.parentNode.insertBefore(js, fjs);
							}(document, 'script', 'facebook-jssdk'));</script>
							
							<fb:send href="<?php echo SITE_FB_URL . "product/view/id/" . $prodval['product_id']; ?>"></fb:send>

					   </div>
						<div style="clear: both;"></div>
	
					</div>
					<div style="clear: both"></div>
				 </div>    
			 </div>
		  <?php }?>   
		 </div>   
	</div>
	<?php if(count($this->records) > 0){?>
	<div class="portlet">
		<div class="productListingNav">
		   
		<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_bottom.phtml'); ?>
		</div>
		<input type="hidden" name="page_no" id="page_no" value="<?php echo $this->page_no; ?>" />

		<div style="padding-bottom:10px; clear:both"></div>
	</div>
	<?php }?>
	</form>
	<!--<script type="text/javascript">
		$(document).ready(function(){
			$("#slider1").easySlider({
				auto: false,
				continuous: false,
				nextId: "slidernext",
				prevId: "sliderprev",
				prevText: "",
				nextText: "",
				controlsShow: false
			});

			$("#slidernext").show();
			$("#sliderprev").show();
		});
	</script>-->
   
</div>