
<div id="rightColumn">
	<div class="mainColumnWidget">
		<?php if($this->parentcat_id == '0'){?>
			<div id="breadCrumb">
				<ul>
					<li>
						<a target="_top" href="<?php echo SITE_FB_URL;?>">
							<img title="home" alt="home" src="<?php echo IMAGES_FB_PATH ?>/home.png"/>
						</a>
					</li>
					<li>
						<a target="_top" href="<?php echo SITE_FB_URL;?>category/subcat/id/<?php echo $this->cat_id ?>"><?php echo $this->catname?></a>
					</li>
				</ul>
			</div>
		<?php }else{?>
			<div id="breadCrumb">
				<ul>
					<li>
						<a target="_top" href="<?php echo SITE_FB_URL;?>">
							<img title="home" alt="home" src="<?php echo IMAGES_FB_PATH ?>/home.png"/>
						</a>
					</li>
					<li>
						<a target="_top" href="<?php echo SITE_FB_URL;?>category/subcat/id/<?php echo $this->parentcat_id ?>"><?php echo $this->parentcat_name?></a>
					</li>
					<li>
						<a target="_top" href="<?php echo SITE_FB_URL;?>category/subcat/id/<?php echo $this->cat_id ?>"><?php echo $this->catname?></a>
					</li>
 				</ul>
			</div>
		<?php }?>
		<div class="categoryHeader">
		   <?php echo $this->Translate('Category')?>: <?php echo $this->catname?> 
		</div>
		<form name="frmcatproduct" method="get" id="frmcatproduct" action="<?php echo SITE_FB_URL;?>category/subcat/id/<?php echo $this->cat_id ?>" target="_top">
		<?php if(count($this->records) > 0){?>
		<div class="portlet">
			 <div class="bluewidgetHeader">
				   <div style="float:left;">
						<select id="sortBy" style="width:150px;" name="sortBy" onchange="this.form.submit();">
                                                                        
							<option value="bestseller" <?php echo $this->bestseller;?>><?php echo $this->Translate('BestSeller')?></option>
							<option value="most_liked" <?php echo $this->most_liked;?>><?php echo $this->Translate('MostLiked')?></option>
							<option value="price_asc" <?php echo $this->price_asc;?>><?php echo $this->Translate('LowToHigh')?></option>
							<option value="price_desc" <?php echo $this->price_desc;?>><?php echo $this->Translate('HighToLow')?></option>
                         </select>
					</div>
					 <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_top.phtml'); ?>
					<div style="clear:both;"></div>
			</div>
		 </div>
		<div class="portlet" style="border-bottom:1px solid #E2E2E2">
				<div class="productListingNav">
				   <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_bottom.phtml'); ?>
				</div>
				<div style="clear:both"></div>
		</div>
		<?php }else{?>
							<div style="font-size:12px; padding: 8px 10px 9px; border-bottom: 1px solid #E2E2E2;">
								<p>"<?php echo $this->Translate('NoProduct')?>"</p>
							</div>
						<?php }?> 
		<div id="productGridView" class="portlet">
		<?php foreach($this->records as $prodval){?>
			<?php 
				if($prodval['ProdName'] != '')
				{
					$prodName = $prodval['ProdName'];
				}else{
					$prodName = $prodval['product_name'];
				}
			?>
			<div class="productGridItem productGridItemTopRow firstborder">
			
			<?php
						$SmallImg = str_replace('img','th1',$prodval['image_name']);
						$tinyImage = SITE_PRODUCT_IMAGES_PATH.$prodval['image_path']."/".$SmallImg;	
						$ThumbImage = SITE_PRODUCT_IMAGES_PATH.$prodval['image_path']."/".$prodval['image_name'];
					 ?>
				<div class="thumbnailImage" style="margin-top:14px;">
					<a target="_top" url="<?php echo $ThumbImage;?>" class="preview" style="cursor:pointer"  href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $prodval['product_id'];?>/sid/<?php echo $this->cat_id; ?>">
					
					<?php if(!$prodval['image_name']){?>
						<img class="img" alt="Default" title="Default" src="<?php echo IMAGES_FB_PATH ?>/Default.gif"/>
					<?}else{?>
					
					 
 						<img class="img" src="<?php echo $tinyImage; ?>" width="128" alt="<?php echo $prodName; ?>" title="<?php echo $prodName; ?>"/>
					<?}?>
					</a>
				</div>
				<div class="productTitle">
					<a target="_top" style="cursor:pointer" href="<?php echo SITE_FB_URL;?>product/view/id/<?php echo $prodval['product_id'];?>/sid/<?php echo $this->cat_id; ?>"><?php echo $prodName; ?></a> 
				</div>
				<div class="productPrice">
				   <?php echo DEFAULT_CURRENCY_SYMBOL."&nbsp;".$prodval['prod_convert_price']."&nbsp;".DEFAULT_CURRENCY_CODE;?>
				</div>
				<div class="socialbtn">
					<script>(function(d, s, id) {
						  var js, fjs = d.getElementsByTagName(s)[0];
						  if (d.getElementById(id)) {return;}
						  js = d.createElement(s); js.id = id;
						  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<?php echo FACEBOOK_APP_API_ID; ?>";
						  fjs.parentNode.insertBefore(js, fjs);
						}(document, 'script', 'facebook-jssdk'));</script>
						<fb:like href="<?php echo SITE_FB_URL . "product/view/id/" . $prodval['product_id']; ?>" send="true" layout="button_count" width="181" show_faces="false"></fb:like>
				   
					<div style="clear: both"></div>
				 </div>    
			 </div>
		  <?php }?>   
		 </div>   
	</div>
	<?php if(count($this->records) > 0){?>
	<div class="portlet">
		<div class="productListingNav">
		   
		<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_bottom.phtml'); ?>
		</div>
		<input type="hidden" name="page_no" id="page_no" value="<?php echo $this->page_no; ?>" />
		<input type="hidden" name="subcategory_id" id="subcategory_id" value="<?php echo $this->cat_id; ?>" />
		<div style="padding-bottom:10px; clear:both"></div>
	</div>
	<?php }?>
	</form>
</div>