<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="<?php echo SITE_URL; ?>admin/"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last1"><a href="<?php echo SITE_URL; ?>admin/lengthunit"><?php echo $this->Translate('Lengthunit'); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Edit_Lengthunit'); ?></span></li>
	</ul>
</div>

<!--       Set Record value         -->
<?php  $edit_record = $this->records;  ?>

<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate('Manage_Lengthunit'); ?>
	</div>
	
	<?php if(count($this->editErrorMessage) > 0 ) { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
				<?php foreach($this->editErrorMessage as $key => $val ) { ?>
					<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
					<strong><?php echo $val; ?></strong></p>
				<?php } ?>
			</div>
		</div>
	<?php } ?>	
	
	<form method="post" name="edit_form" id="edit_form" >
		<table class="Panel" style="margin-top:10px;">
			<tr>
				<td class="Heading2" colspan="2"><?php echo $this->Translate('Edit_Lengthunit'); ?></td>
			</tr>
			<tr>
				<td colspan="2">
				<div id="div0" style="padding-bottom:5px">
					<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Lengthunit_From_Id'); ?>
							</td>
							<td>
								<select name="from_id" id="from_id" class="Field250">
									<option value="0" ><?php echo $this->Translate('Lengthunit_Select'); ?></option>
									<?php if(count($this->length) > 0) {  ?>
									<?php  		foreach($this->length as $key => $val) { ?>	
									<?php  		   	if ( $val['length_unit_id'] == $edit_record["from_id"] ) { ?>	
									<option value="<?php echo $val['length_unit_id']; ?>" selected="selected">
									<?php 			} else {  ?>
									<option value="<?php echo $val['length_unit_id']; ?>">
									<?php 			}  ?>		
									<?php 			echo $val["length_unit_name"];  ?>	
									</option>
									<?php 		}  ?>
									<?php } else {  ?>
									<?php }  ?>
								</select>
								<span></span>
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('To_Id'); ?>
							</td>
							<td>
								<select name="to_id" id="to_id" class="Field250">
									<option value="0" ><?php echo $this->Translate('Lengthunit_Select'); ?></option>
									<?php if(count($this->length) > 0) {  ?>
									<?php  		foreach($this->length as $key => $val) { ?>	
									<?php  		   	if ( $val['length_unit_id'] == $edit_record["to_id"] ) { ?>	
									<option value="<?php echo $val['length_unit_id']; ?>" selected="selected">
									<?php 			} else {  ?>
									<option value="<?php echo $val['length_unit_id']; ?>">
									<?php 			}  ?>		
									<?php 			echo $val["length_unit_name"];  ?>	
									</option>
									<?php 		}  ?>
									<?php } else {  ?>
									<?php }  ?>
								</select>
								<span></span>
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Lengthunit_Value'); ?>
							</td>
							<td>
								<input type="text" name="value" id="value" class="Field250" value=<?php echo $edit_record["value"] ?> />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						<tr>
						   	<td colspan="2">
								<input type="submit" onclick="Javascript: return ValidateEditFrom()" value="<?php echo $this->Translate('Submit'); ?>" />
								<input type="button" value="<?php echo $this->Translate('Cancle'); ?>" onclick="window.location='<?php echo $this->site_url; ?>'"/>
						   </td>
						</tr>
					</table>
				</div>
				</td>
			</tr>
		</table>   
		
		<!--         Hidden fields                       -->
		<input type="hidden" name="from_id_p" id="from_id_p" value="<?php echo $this->from_id_p; ?>" />
		<input type="hidden" name="to_id_p" id="to_id_p" value="<?php echo $this->to_id_p; ?>" />
		
	</form>            
</div> 

<!--     JS Global Variable for the language    -->

<script language="javascript" type="text/javascript">
var siteurl = "<?php echo SITE_URL; ?>";
var ERR_LENGTH_FROM_ID = "<?php echo $this->Translate('Err_Lengthunit_Id'); ?>";  
var ERR_LENGTH_TO_ID = "<?php echo $this->Translate('Err_Lengthunit_Id'); ?>";  
var ERR_LENGTH_VALUE = "<?php echo $this->Translate('Err_Lengthunit_Value'); ?>";  
var ERR_LENGTH_INVALID_VALUE = "<?php echo $this->Translate('Err_Lengthunit_Invalid_Value'); ?>";  
</script>