<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="#"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last1"><a href="<?php echo SITE_URL; ?>admin/country"><?php echo $this->country_data["country_name"]; ?></a></li>
	   <li class="Last1"><a href="<?php echo SITE_URL; ?>admin/country/statelist/cid/<?php echo $this->country_id; ?>"><?php echo $this->Translate('State'); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Edit_State'); ?></span></li>
	</ul>
</div>

<!--       Set Record value         -->
<?php  $edit_record = $this->records;  ?>

<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate('Manage_State'); ?>
	</div>
	
	<?php if(count($this->editErrorMessage) > 0 ) { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
				<?php foreach($this->editErrorMessage as $key => $val ) { ?>
					<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
					<strong><?php echo $val; ?></strong></p>
				<?php } ?>
			</div>
		</div>
	<?php } ?>	
	
	<form method="post" name="edit_state_form" id="edit_state_form" >
		<table class="Panel" style="margin-top:10px;">
			<tr>
				<td class="Heading2" colspan="2"><?php echo $this->Translate('Edit_State'); ?></td>
			</tr>
			<tr>
				<td colspan="2">
				<div id="div0" style="padding-bottom:5px">
					<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
						<tr><td height="15"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('State_Name'); ?>
							</td>
							<td>
								<input type="text" value="<?php echo $this->records['state_name']; ?>" name="state_name" id="state_name" class="Field250" />
								<span></span>
							</td>
						</tr>
						<tr><td height="25"></td></tr>
						 <tr>
						   	<td colspan="2">
								<input type="submit" onclick="Javascript: return ValidateEditStateForm()" value="<?php echo $this->Translate('Submit'); ?>" />
								<input type="button" id="anything"  value="<?php echo $this->Translate('Cancle'); ?>" onclick="window.location='<?php echo $this->site_url."/cid/".$this->country_id; ?>'"/>
						   </td>
						</tr>
					</table>
				</div>
				</td>
			</tr>
		</table>   
		
		<!--         Hidden fields                       -->
		<input type="hidden" name="state_id" id="state_id" value="<?php echo $this->state_id; ?>" />
		<input type="hidden" name="country_id" id="country_id" value="<?php echo $this->country_id; ?>" />
		
	</form>            
</div> 

<!--     JS Global Variable for the language    -->

<script language="javascript" type="text/javascript">
var siteurl = "<?php echo SITE_URL; ?>";
var ERR_STATE_NAME = "<?php echo $this->Translate('Err_State_Name'); ?>";  
</script>