<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	    <li class="Home SecondLast"><a href="<?php echo SITE_URL; ?>user"><?php echo $this->Translate("User_Home"); ?></a></li>
	    <li class="Last1"><a href="<?php echo SITE_URL; ?>user/products"><?php echo $this->Translate("Products"); ?></a></li>
		<li class="Last"><span><?php echo $this->Translate("Product_Add_Detail"); ?></span></li>
	</ul>
</div>


<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate("Products_Management"); ?>
	</div>
	
	<?php if(count($this->addErrorMessage) > 0 ) { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
				<?php foreach($this->addErrorMessage as $key => $val ) { ?>
					<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
					<strong><?php echo $val; ?></strong></p>
				<?php } ?>
			</div>
		</div>
	<?php } ?>	
	
	<form method="post" name="add_form" id="add_form" >
		<table class="Panel" style="margin-top:10px;">
			<tr>
				<td class="Heading2" colspan="2"><?php echo $this->Translate("Product_Add_Detail"); ?></td>
			</tr>
			<tr>
				<td colspan="2">
				<div id="div0" style="padding-bottom:5px">
					<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate("Product_Name"); ?>
							</td>
							<td>
								<input value="<?php echo $this->data['product_name']; ?>" type="text" name="product_name" id="product_name"  class="Field250" />
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						
						
						<!--       Add Category Language        -->
						<?php foreach( $this->language as $key => $val ) { ?>
						<?php 	if($val['language_id'] != DEFAULT_LANGUAGE ) { ?>
						<tr>
							<td class="FieldLabel"></td>
							<td>
								<?php $lagn_index = 'product_name_'.$val['language_id']; ?>
								<input  type="text" value="<?php  echo $this->langdata[$val['language_id']]['product_name'] ?>" name="product_name_<?php echo $val['language_id']; ?>" id="product_name_<?php echo $val['language_id']; ?>" class="Field250" />
								<span></span>
								&nbsp;&nbsp;&nbsp;<?php echo $val['name']." ( ".$val['code']." )"; ?>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						<?php 	}?>
						<?php } ?>
						
						
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate("Product_Desc"); ?>
							</td>
							<td>
								<textarea name="product_description" cols="30" id="product_description"><?php echo $this->data['product_description']; ?></textarea>
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>		
						
						<!--       Add Category Language        -->
						<?php foreach( $this->language as $key => $val ) { ?>
						<?php 	if($val['language_id'] != DEFAULT_LANGUAGE ) { ?>
						<tr>
							<td class="FieldLabel"></td>
							<td>
								<?php $lagn_index = 'product_description_'.$val['language_id']; ?>
								
								<textarea name="product_description_<?php echo $val['language_id']; ?>" id="product_description_<?php echo $val['language_id']; ?>" cols="30" ><?php  echo $this->langdata[$val['language_id']]['product_description'] ?></textarea>
								<span></span>
								&nbsp;&nbsp;&nbsp;<?php echo $val['name']." ( ".$val['code']." )"; ?>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						<?php 	}?>
						<?php } ?>
						
										
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate("Product_Price"); ?>
							</td>
							<td>
								<input value="<?php echo $this->data['product_price']; ?>" type="text" name="product_price" id="product_price"  class="Field250" />								
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate("Product_Code"); ?>
							</td>
							<td>
								<input value="<?php echo $this->data['product_code']; ?>" type="text" name="product_code" id="product_code"  class="Field250" />
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate("Product_Category"); ?>
							</td>
							<td>
								<select name="product_category" id="product_category" multiple="multiple"  >
									<!--<?php $category_array = $this->category; ?>-->
									<?php echo $this->cateTree; ?>
									
									
<!--<?php if(count($category_array) > 0) {  
		for( $i = 0; $i < count($category_array); $i++) { 
		
			if ($category_array[$i]["parent_id"] == 0 ) {
				
				echo "<optgroup label='".$category_array[$i]["category_name"]."'>";
				
					for( $j = 0; $j < count($category_array); $j++)
					{
						if($category_array[$j]["parent_id"] == $category_array[$i]["category_id"]) 	
						{
							
							echo "<option value='".$category_array[$j]["category_id"]."'>".$category_array[$j]["category_name"]."</option>";
							
						}
					}
				
				echo "</optgroup>";
					
			}
		 }  
	}
?>-->
									
								</select>
								<input type="hidden" name="multiselect_product_category_value" id="multiselect_product_category_value" value="">
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate("Product_Weight"); ?>
							</td>
							<td>
								<input type="text" name="product_weight" id="product_weight" class="Field250" />
								
								<select name="weight_unit_id" id="weight_unit_id" class="comboField">
									<option value=""  ><?php echo $this->Translate("Product_Select_Weight_Unit"); ?></option>
									<?php if(count($this->weight) > 0) {  ?>
									<?php  		foreach($this->weight as $key => $val) { ?>	
									<?php  			if($this->data['product_code'] == $val["weight_unit_id"] ) { ?>
									<option value="<?php echo $val["weight_unit_id"]; ?>" selected="selected">
									<?php 			} else { ?>
									<option value="<?php echo $val["weight_unit_id"]; ?>">
									<?php 			}?>
									<?php 			echo $val["weight_unit_key"];  ?>	
									</option>
									<?php 		}  ?>
									<?php } else {  ?>
									<?php }  ?>
								</select>
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate("Product_Length"); ?>
							</td>
							<td>
								<input type="text" name="length" id="length"  class="Field250" />
								<select name="length_unit_id" id="length_unit_id" class="comboField">
									<option value="" ><?php echo $this->Translate("Product_Select_Length_Unit"); ?></option>
									<?php if(count($this->length) > 0) {  ?>
									<?php  		foreach($this->length as $key => $val) { ?>	
									<?php  			if($this->data['length_unit_id'] == $val["length_unit_id"] ) { ?>
									<option value="<?php echo $val["length_unit_id"]; ?>" selected="selected">
									<?php 			} else { ?>
									<option value="<?php echo $val['length_unit_id']; ?>">
									<?php 			}?>
									<?php 			echo $val["length_unit_key"];  ?>	
									</option>
									<?php 		}  ?>
									<?php } else {  ?>
									<?php }  ?>
								</select>
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate("Product_Tax_Class"); ?>
							</td>
							<td>
								<select name="tax_rate_class_id" id="tax_rate_class_id" class="Field250" >
									<option value="" ><?php echo $this->Translate("Product_Select_Tax_Class"); ?></option>
									<?php if(count($this->taxrate_class) > 0) {  ?>
									<?php  		foreach($this->taxrate_class as $key => $val) { ?>	
									<?php  			if($this->data['tax_rate_class_id'] == $val["tax_rate_class_id"] ) { ?>
									<option value="<?php echo $val["tax_rate_class_id"]; ?>" selected="selected">
									<?php 			} else { ?>
									<option value="<?php echo $val['tax_rate_class_id']; ?>">
									<?php 			}?>
									<?php 			echo $val["tax_rate_name"];  ?>	
									</option>
									<?php 		}  ?>
									<?php } else {  ?>
									<?php }  ?>
								</select>
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate("Product_Width"); ?>
							</td>
							<td>
								<input value="<?php echo $this->data['width']; ?>" type="text" name="width" id="width"  class="Field250" />
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate("Product_Depth"); ?>
							</td>
							<td>
								<input value="<?php echo $this->data['depth']; ?>" type="text" name="depth" id="depth"  class="Field250" />
							</td>
							<td></td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate("Product_Quantity"); ?>
							</td>
						  <td>
							  <input value="<?php echo $this->data['available_qty']; ?>" type="text" name="available_qty" id="available_qty"  class="Field250" />
						  </td>
						  <td></td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Discount'); ?>
							</td>
						  <td>
							  <input type="text" name="discount" id="discount" value="<?php echo $this->data['discount'];  ?>" class="Field250" />
						  </td>
						  <td></td>
						</tr>
						<tr><td height="5"></td></tr>						
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Available_Date'); ?>
							</td>
							<td>
								<input type="text" value="<?php if(strtotime($this->data['available_date']) > 0 ) { echo $this->data['available_date']; } ?>" name="available_date" id="available_date" class="Field250 datepicker" />		
							</td>
							 <td></td>
						</tr>	
						<tr><td height="5"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Expiration_Date'); ?>
							</td>
							<td>
								<input type="text" value="<?php if(strtotime($this->data['expiration_date']) > 0 ) { echo $this->data['expiration_date']; } ?>" name="expiration_date" id="expiration_date" class="Field250 datepicker" />		
							</td>
							 <td></td>
						</tr>	
						<tr><td height="5"></td></tr>	
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Promotion_Start_Date'); ?>
							</td>
							<td>
								<input type="text" value="<?php if(strtotime($this->data['promotion_start_date']) > 0 ) { echo $this->data['promotion_start_date']; } ?>" name="promotion_start_date" id="promotion_start_date" class="Field250 datepicker" />		
							</td>
							 <td></td>
						</tr>	
						<tr><td height="5"></td></tr>	
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Product_Promotion_End_Date'); ?>
							</td>
							<td>
								<input type="text" value="<?php if(strtotime($this->data['promotion_end_date']) > 0 ) { echo $this->data['promotion_end_date']; }  ?>" name="promotion_end_date" id="promotion_end_date"  class="Field250 datepicker" />		
							</td>
							 <td></td>
						</tr>		
						<tr><td height="5"></td></tr>	
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate("Product_Start_Sales"); ?>
							</td>
							<td>
								<?php if($this->data['start_sales'] == "1") { ?>
										<input type="radio" name="start_sales" checked="checked" class="" value="1" />			
										<?php echo $this->Translate("Product_Status_Active"); ?>&nbsp;
										<input type="radio" name="start_sales"  value="0" />
										<?php echo $this->Translate("Product_Status_Inactive"); ?>
									<?php } elseif($this->data['start_sales'] == "0") {  ?>
										<input type="radio" name="start_sales" id="start_sales" class="" value="1" />			
										<?php echo $this->Translate("Product_Status_Active"); ?>&nbsp;
										<input type="radio" name="start_sales"  value="0" checked="checked" />
										<?php echo $this->Translate("Product_Status_Inactive"); ?>
									<?php } else { ?>
										<input type="radio" name="start_sales" id="start_sales" class="" value="1" />			
										<?php echo $this->Translate("Product_Status_Active"); ?>&nbsp;
										<input type="radio" name="start_sales"  value="0" />
										<?php echo $this->Translate("Product_Status_Inactive"); ?>
									<?php } ?>  
							</td>
							<td></td>
						</tr>
					</table>
				</div>
				</td>
			</tr>
		</table>   
		
		<!--         Hidden fields                       -->
		<input type="hidden" name="product_id" id="product_id" value="<?php echo $this->product_id; ?>" />
		<input type="hidden" name="product_edit_type" id="product_edit_type" value="Detail" />
		
		<table>		
			<tr><td height="15"></td></tr>
			<tr>
				<td colspan="2">
					<input type="submit" onclick="Javascript: return ValidateProductAddForm()" value="<?php echo $this->Translate('Submit'); ?>" />
					<input type="button" value="<?php echo $this->Translate('Back'); ?>" onclick='window.location="<?php echo $this->site_url; ?>"'/>
			   </td>
			</tr>
			<tr><td height="15"></td></tr>		
		</table>
	</form>            
</div> 

<!--     JS Global Variable for the language    -->

<script language="javascript" type="text/javascript">

$(function(){
   $("#product_category").multiselect({
   		header: false,
		noneSelectedText: "<?php echo $this->Translate('Product_Select_MCategory'); ?>"
	}); 
});


var siteurl = "<?php echo SITE_URL; ?>";
var image_path = "<?php echo IMAGES_PATH; ?>/user/";
var product_id = "<?php echo $this->product_id; ?>";
var EDIT = "<?php echo $this->Translate('Edit'); ?>"; 
var ADD = "<?php echo $this->Translate('Add'); ?>";  
var DELETE = "<?php echo $this->Translate('Delete'); ?>"; 
var UPDATE = "<?php echo $this->Translate('Update'); ?>"; 
var CANCEL = "<?php echo $this->Translate('Cancel'); ?>"; 
var ERR_PRODUCT_NAME = "<?php echo $this->Translate('Err_Product_Name'); ?>";  
var ERR_PRODUCT_DESC = "<?php echo $this->Translate('Err_Product_Desc'); ?>";  
var ERR_PRODUCT_PRICE = "<?php echo $this->Translate('Err_Product_Price'); ?>";
var ERR_PRODUCT_INVALID_PRICE = "<?php echo $this->Translate('Err_Product_Invalid_Price'); ?>";
var ERR_PRODUCT_CODE = "<?php echo $this->Translate('Err_Product_Code'); ?>";
var ERR_PRODUCT_WEIGHT = "<?php echo $this->Translate('Err_Product_Weight'); ?>";
var ERR_PRODUCT_INVALID_WEIGHT = "<?php echo $this->Translate('Err_Product_Invalid_Weight'); ?>";
var ERR_PRODUCT_WEIGHT_UNIT = "<?php echo $this->Translate('Err_Product_Weight_Unit'); ?>" ; 
var ERR_PRODUCT_LENGTH = "<?php echo $this->Translate('Err_Product_Length'); ?>" ; 
var ERR_PRODUCT_INVALID_LENGTH = "<?php echo $this->Translate('Err_Product_Invalid_Length'); ?>" ; 
var ERR_PRODUCT_LENGTH_UNIT = "<?php echo $this->Translate('Err_Product_Length_Unit'); ?>" ; 
var ERR_PRODUCT_WIDTH = "<?php echo $this->Translate('Err_Product_Width'); ?>" ; 
var ERR_PRODUCT_INVALID_WIDTH = "<?php echo $this->Translate('Err_Product_Invalid_Width'); ?>" ; 
var ERR_PRODUCT_DEPTH = "<?php echo $this->Translate('Err_Product_Depth'); ?>" ; 
var ERR_PRODUCT_INVALID_DEPTH = "<?php echo $this->Translate('Err_Product_Invalid_Depth'); ?>" ; 
var ERR_PRODUCT_QUANTITY = "<?php echo $this->Translate('Err_Product_Quantity'); ?>" ; 
var ERR_PRODUCT_INVALID_QUANTITY = "<?php echo $this->Translate('Err_Product_Invalid_Quantity'); ?>" ; 
var ERR_PRODUCT_START_SALE = "<?php echo $this->Translate('Err_Product_Start_Sales'); ?>" ; 
var ERR_PRODUCT_OPTION_TITLE = "<?php echo $this->Translate('Err_Product_Option_Title'); ?>";
var ERR_PRODUCT_OPTION_DETAIL = "<?php echo $this->Translate('Err_Product_Option_Detail'); ?>";
var ERR_PRODUCT_PRIMARY_IMAGE = "<?php echo $this->Translate('Err_Product_Primary_Image'); ?>";
var ERR_PRODUCT_PRIMARY_IMAGE_OTHER = "<?php echo $this->Translate('Err_Product_Primary_Image_Other'); ?>"; 
var ERR_PRODUCT_PRIMARY_AVAILABLE_DATE = "<?php echo $this->Translate('Err_Product_Available_Date'); ?>"; 
var ERR_PRODUCT_PRIMARY_EXPIRATION_DATE = "<?php echo $this->Translate('Err_Product_Expiration_Date'); ?>"; 
var ERR_PRODUCT_PRIMARY_PROMOTION_START_DATE = "<?php echo $this->Translate('Err_Product_Promotion_Start_Date'); ?>"; 
var ERR_PRODUCT_PRIMARY_PROMOTION_END_DATE = "<?php echo $this->Translate('Err_Product_Promotion_End_Date'); ?>"; 
var ERR_PRODUCT_PRIMARY_INVALID_DATE = "<?php echo $this->Translate('Err_Product_Invalid_Date'); ?>"; 
var ERR_PRODUCT_DISCOUNT = "<?php echo $this->Translate('Err_Product_Discount'); ?>"; 
var ERR_PRODUCT_INVALID_DISCOUNT = "<?php echo $this->Translate('Err_Product_Invalid_Discount'); ?>"; 
var ERR_PRODUCT_RANGE_DISCOUNT = "<?php echo $this->Translate('Err_Product_Range_Discount'); ?>"; 

</script>


<div id="dialog-confirm" title="<?php echo $this->Translate('Confirm_Delete_Product_Option_Title'); ?>" style="display:none;">
	<div style="text-align:left;">
		<span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
		<?php echo $this->Translate('Confirm_Delete_Product_Option'); ?>
	</div>
</div>

<script>
	$(function() {
		$( ".datepicker" ).datepicker({ dateFormat: 'yy-mm-dd' });
	});
</script>