<style>
	.scroll-pane,scroll-pane2
	{
		height: 370px;
		overflow: auto;
		float:left;
		padding-bottom:50px;
	}
</style>


<!--  Crumb  Start -->
<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="#"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last1"><a href="<?php echo SITE_URL; ?>user/products"><?php echo $this->Translate("Products"); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate("Product_View_Detail"); ?></span></li>
	</ul>
</div>
<!--  Crumb  end -->

<!--       Set Record value         -->
<?php  $product_detail = $this->product_detail;  ?>

<div class="BodyContainer DashboardContainer" style="text-align:left;">
	<!--  Page Header Start  -->
	<div class="Heading1" >
		<?php echo $this->Translate('Products_Management'); ?>
	</div>
	<!--  Page Header End  -->
	
	<div class="clear"></div>
	<div style="float:left;">
		<input type="button" id="Back" onclick="window.location='<?php echo $this->site_url; ?>'" value="<?php echo $this->Translate('Back'); ?>" />
	</div>
	<div class="clear"></div>
	
	<div id="content" class="typo">
		<div class="column half fl">
			<div class="Heading2">
				<?php echo $this->Translate('Product_Detail'); ?>
			</div>
			<br />
			<?php $detail = $product_detail["detail"]; ?>
			<div class="box-content" >
				<table  width="100%" >
					<tr>
						<td width="40%" valign="top">
							<h5><?php echo $this->Translate('Product_Name'); ?></h5>
						</td>
						<td width="50%">
							:&nbsp;&nbsp;<?php echo $detail["product_name"]; ?>
						</td>
						
					</tr>
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Price'); ?></h5>
						</td>
						<td>
							:&nbsp;&nbsp;<?php echo $detail["product_price"]; ?>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Code'); ?></h5>
						</td>
						<td>
							:&nbsp;&nbsp;<?php echo $detail["product_code"]; ?>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Weight'); ?></h5>
						</td>
						<td>	
							:&nbsp;&nbsp;<?php echo $detail["product_weight"]; ?>&nbsp;<?php echo $detail["weight_unit_key"]; ?>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Length'); ?></h5>
						</td>
						<td>
							:&nbsp;&nbsp;<?php echo $detail["length"]; ?>&nbsp;<?php echo $detail["length_unit_key"]; ?>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Width'); ?></h5>
						</td>
						<td>
							:&nbsp;&nbsp;<?php echo $detail["width"]; ?>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Depth'); ?></h5>
						</td>
						<td>
							:&nbsp;&nbsp;<?php echo $detail["depth"]; ?>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Start_Sales'); ?></h5>
						</td>
						<td>	
							:&nbsp;&nbsp;<?php if($detail["start_sales"] == "1") { echo "Yes"; } else { echo "No"; } ?>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Quantity'); ?></h5>
						</td>
						<td>
							:&nbsp;&nbsp;<?php echo $detail["available_qty"]; ?>
						</td>
					</tr>	
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Category'); ?></h5>
						</td>
						<td>
							:&nbsp;&nbsp;
							<select name="product_category" id="product_category" multiple="multiple"  >
								<?php echo $this->cateTree; ?>		
							</select>
						</td>
					</tr>				
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Available_Date'); ?></h5>
						</td>
						<td>
							:&nbsp;&nbsp;<?php echo date("F j, Y", strtotime($detail["available_date"])); ?>
						</td>
					</tr>	
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Expiration_Date'); ?></h5>
						</td>
						<td>
							:&nbsp;&nbsp;<?php echo date("F j, Y", strtotime($detail["expiration_date"])); ?>
						</td>
					</tr>	
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Promotion_Start_Date'); ?></h5>
						</td>
						<td>
							:&nbsp;&nbsp;<?php echo date("F j, Y", strtotime($detail["promotion_start_date"])); ?>
						</td>
					</tr>	
					<tr>
						<td valign="top">
							<h5><?php echo $this->Translate('Product_Promotion_End_Date'); ?></h5>
						</td>
						<td>
							:&nbsp;&nbsp;<?php echo date("F j, Y", strtotime($detail["promotion_end_date"])); ?>
						</td>
					</tr>							
				</table>
			</div>
			<br />
			<div class="Heading2">
				<?php echo $this->Translate('Product_Desc'); ?>
			</div>
			<div class="box-content" >
				<p class="p_left" style="padding-left:5px;"><strong><h5><?php echo $detail["product_name"]; ?>:</h5></strong>
					<br/><?php echo $detail["product_description"]; ?>
				</p>
				<hr/>
			</div>
		</div>
	
		<div class="column half fr">
			<div id="accordion">
				<div>
					<h3><a href="#"><?php echo $this->Translate('Product_Images'); ?></a></h3>
					<?php $images = $product_detail["images"]; ?>
					<div >
						<div >
							<div class="scroll-pane" style="width:395px;">
								<div class="excersice-list">
									<ul>
										<?php 
											if($images != NULL ) { 
												foreach($images as $key => $val)
												{
													$img_string = str_replace("_img","_th1",$val['image_name']);													
													echo "<li><img src='".SITE_PRODUCT_IMAGES_PATH."/p".$this->product_id."/".$img_string."' width='128' height='128'></li>";
												}
											} else {											
												echo "<li>".$this->Translate('Product_No_Images_Found')."<li>"; 
											}
										?>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div>
					<h3><a href="#"><?php echo $this->Translate('Product_Options'); ?></a></h3>
					<div >
						<?php $category = $product_detail["category"]; ?>
						<?php $options = $product_detail["options"]; ?>
						<div class="box-content scroll-pane" style="width:395px;" >
							<?php 
								if($options != NULL) {
									$option_value = '';
									foreach($options as $key =>$val) { 
										if($val["LNK_options_id"] != $option_value) {
							?>	
											<div class="Heading2">
												<?php echo $val["option_title"]; ?>
											</div>
							<?php			foreach($options as $key =>$val2)
											{
												if($val["LNK_options_id"] == $val2["LNK_options_id"]) {
							?>
													<div class="box-content" >
														<p class="p_left" style="padding-left:5px;">
															<strong><h5><?php echo $val2["option_name"]; ?>:</h5></strong>
															<table  width="100%" >
																<tr>
																	<td width="30%">
																		<strong><?php echo $this->Translate('Product_Option_Value_Code'); ?>:</strong>
																	</td>
																	<td width="20%"><?php echo $val2["option_code"]; ?></td>
																	<td width="30%">
																		<strong><?php echo $this->Translate('Product_Price'); ?>:</strong>
																	</td >
																	<td width="20%"><?php echo $val2["option_price"]; ?></td>
																</tr>
																<tr>
																	<td>
																		<strong><?php echo $this->Translate('Product_Weight'); ?>:</strong>
																	</td>
																	<td><?php echo $val2["option_weight"]."&nbsp;&nbsp;".$val2["weight_unit_key"]; ?></td>
																	<td>
																		<strong><?php echo $this->Translate('Product_Quantity'); ?>:</strong>
																	</td>
																	<td><?php echo $val2["option_quantity"]; ?></td>
																</tr>
															</table>
														</p>
														<hr/>
													</div>
							<?php				}
											}
										}
										$option_value = $val["product_options_id"];
									}
													
								} else {
									echo $this->Translate('Product_No_Options_Found');
								}
							?>
						</div>
					</div>
				</div>
			</div>
		</div>
	
       	<div class="clear"></div>
	</div>               
</div>
<script type="text/javascript">
	$(function(){
		$('.scroll-pane').jScrollPane();
		// Accordion
		$("#accordion").accordion({ header: "h3",autoHeight: false, navigation: true });
		
		$("#product_category").multiselect({
		   header: false,
		   noneSelectedText: "<?php echo $this->Translate('Product_Select_MCategory'); ?>",
		});	
	});
	
</script>