<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="#"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Category'); ?></span></li>
	</ul>
</div>


<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate('Manage_Categories'); ?>
	</div>
	
	<div >
		<?php echo $this->addErrorMessage; ?>
	</div>
	
	<form method="post" name="add_form" id="add_form" >
		<table class="Panel" style="margin-top:10px;">
			<tr>
				<td class="Heading2" colspan="2"><?php echo $this->Translate('Add_Categories'); ?></td>
			</tr>
			<tr>
				<td colspan="2">
				<div id="div0" style="padding-bottom:5px">
					<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Category_Name'); ?>
							</td>
							<td>
								<input type="text" name="category_name" id="category_name" class="Field250" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Category_Parent'); ?>:
							</td>
							<td>
								<select name="parent_category" id="parent_category" class="comboField">
									<option value="0" selected="selected">Select parent category</option>
									<?php if(count($this->categories) > 0) {  ?>
									<?php  		foreach($this->categories as $key => $val) { ?>	
									<option value="<?php echo $val['category_id']; ?>">
									<?php 			echo $val["category_name"];  ?>	
									</option>
									<?php 		}  ?>
									<?php } else {  ?>
									<?php }  ?>
								</select>
								<span></span>
							</td>
						</tr>						
						<tr><td height="15"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('User_Status'); ?>:
							</td>
							<td>
								<span>
									<input type="radio" name="is_active" id="is_active" class="" value="1" />
									<?php echo $this->Translate('Admin_User_Status_Active'); ?>&nbsp;
									<input type="radio" name="is_active"  value="0" />
									<?php echo $this->Translate('Admin_User_Status_Inactive'); ?>
								</span>
								<span></span>
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						<tr>
						   	<td colspan="2">
								<input type="submit" id="anything" onclick="Javascript: return ValidateAddFrom()"  value="<?php echo $this->Translate('Submit'); ?>" />
								<input type="button" id="anything"  value="<?php echo $this->Translate('Cancle'); ?>" onclick="window.location='<?php echo $this->site_url; ?>'"/>
						   </td>
						</tr>
					</table>
				</div>
				</td>
			</tr>
		</table>   
		<input type="hidden" name="parent_id" id="parent_id" value="<?php echo $this->parent_id; ?>" />
	</form>            
</div> 

<!--     JS Global Variable for the language    -->

<script language="javascript" type="text/javascript">
var siteurl = '<?php echo SITE_URL; ?>';
var ERR_CATEGORY_NAME = '<?php echo $this->Translate("Err_Category_Name"); ?>';  
var ERR_IS_ACTIVE = '<?php echo $this->Translate("Err_Is_Active"); ?>' ; 
</script>