<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="<?php echo $this->site_url ?>"><?php echo $this->Translate("Administration"); ?></a></li>
	   <?php if($this->parent_id == 0){ ?>
	   <li class="Last1"><a href="<?php echo $this->site_url ?>"><?php echo $this->Translate('Category'); ?></a></li>
	   <?php } ?>
	   <?php if($this->parent_id > 0){ ?>
	   <li class="Last1"><a href="<?php echo $this->site_url ?>"><?php echo $this->Translate('Category'); ?></a></li>
	   <?php for($i = count($this->path_array)-1; $i >= 0; $i--){ 
	   	if($i == 0)
		{
	   ?>
	   <li class="Last1"><span><?php echo $this->path_array[$i]['category_name']; ?></span></li>
	   <?php 
	   }else{ 
	   
	   ?>
	   <li class="Last1"><a href="<?php echo $this->site_url . '/index/parent_id/' . $this->path_array[$i]['category_id']; ?>"><?php echo $this->path_array[$i]['category_name']; ?></a></li>
	   <?php }}} ?>
	   <li class="Last"><span><?php echo $this->Translate('Add_Categories'); ?></span></li>
	</ul>
</div>


<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate('Manage_Categories'); ?>
	</div>
	
	<?php if(count($this->addErrorMessage) > 0 ) { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
				<?php foreach($this->addErrorMessage as $key => $val ) { ?>
					<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
					<strong><?php echo $val; ?></strong></p>
				<?php } ?>
			</div>
		</div>
	<?php } ?>	
	
	<form method="post" name="add_form" id="add_form" enctype="multipart/form-data" >
		<table class="Panel" style="margin-top:10px;">
			<tr>
				<td class="Heading2" colspan="2"><?php echo $this->Translate('Add_Categories'); ?></td>
			</tr>
			<tr>
				<td colspan="2">
				<div id="div0" style="padding-bottom:5px">
					<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Category_Name'); ?>
							</td>
							<td>
								<input  type="text" value="<?php echo $this->data['category_name']; ?>" name="category_name" id="category_name" class="Field250" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						
						
						<!--       Add Category Language        -->
						<?php foreach( $this->language as $key => $val ) { ?>
						<?php 	if($val['language_id'] != DEFAULT_LANGUAGE ) { ?>
						<tr>
							<td class="FieldLabel"></td>
							<td>
								<?php $lagn_index = 'category_name_'.$val['language_id']; ?>
								<input  type="text" value="<?php  echo $this->langdata[$val['language_id']]['category_name'] ?>" name="category_name_<?php echo $val['language_id']; ?>" id="category_name_<?php echo $val['language_id']; ?>" class="Field250" />
								<span></span>
								&nbsp;&nbsp;&nbsp;<?php echo $val['name']." ( ".$val['code']." )"; ?>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						<?php 	}?>
						<?php } ?>
						
						
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Category_Parent'); ?>:
							</td>
							<td>
								<select name="parent_category"  id="parent_category" class="comboField">
									<option value="0" selected="selected"><?php echo $this->Translate('Admin_Select_Parent_Category'); ?></option>
									<?php echo $this->cateTree; ?>
								</select>
								<span></span>
							</td>
						</tr>				
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Category_Icon'); ?>:
							</td>
							<td>
								<input type="file" name="icon_image" id="icon_image">
								<span></span>
							</td>
						</tr>						
						<tr><td height="15"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('User_Status'); ?>:
							</td>
							<td>
								<span>
									<?php if($this->data['is_active'] == "1") { ?>
										<input type="radio" name="is_active" checked="checked" id="is_active" class="" value="1" />
										<?php echo $this->Translate('Admin_User_Status_Active'); ?>&nbsp;
										<input type="radio" name="is_active"  value="0" />
										<?php echo $this->Translate('Admin_User_Status_Inactive'); ?>
									<?php } elseif($this->data['is_active'] == "0") {  ?>
										<input type="radio" name="is_active" id="is_active" class="" value="1" />
										<?php echo $this->Translate('Admin_User_Status_Active'); ?>&nbsp;
										<input type="radio" checked="checked" name="is_active"  value="0" />
										<?php echo $this->Translate('Admin_User_Status_Inactive'); ?>
									<?php } else { ?>
										<input type="radio" name="is_active" id="is_active" class="" value="1" />
										<?php echo $this->Translate('Admin_User_Status_Active'); ?>&nbsp;
										<input type="radio" name="is_active"  value="0" />
										<?php echo $this->Translate('Admin_User_Status_Inactive'); ?>
									<?php } ?> 
								</span>
								<span></span>
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						<tr>
						   	<td colspan="2">
								<input type="submit" id="anything" onclick="Javascript: return ValidateAddFrom()"  value="<?php echo $this->Translate('Submit'); ?>" />
								<input type="button" id="anything"  value="<?php echo $this->Translate('Cancle'); ?>" onclick="window.location='<?php echo $this->site_url; ?>'"/>
						   </td>
						</tr>
					</table>
				</div>
				</td>
			</tr>
		</table>   
		<input type="hidden" name="parent_id" id="parent_id" value="<?php echo $this->parent_id; ?>" />
	</form>            
</div> 




<!--     JS Global Variable for the language    -->

<script language="javascript" type="text/javascript">
var siteurl = '<?php echo SITE_URL; ?>';
var ERR_CATEGORY_NAME = '<?php echo $this->Translate("Err_Category_Name"); ?>';  
var ERR_IS_ACTIVE = '<?php echo $this->Translate("Err_Is_Active"); ?>' ; 



</script>