<!--  Crumb  Start -->
<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="<?php echo SITE_URL; ?>user/"><?php echo $this->Translate("User_Home"); ?></a></li>
	   <li class="Last1"><a href="<?php echo SITE_URL; ?>user/apihelp/"><?php echo $this->Translate("Api_Help"); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate("Delete_Product_Api_Help"); ?></span></li>
	</ul>
</div>
<!--  Crumb  end -->

<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate('Delete_Product_Api_Help'); ?>
	</div>
<div style="margin-top:20px;"><h4><?php echo $this->Translate('Api_Delete_Product_Rest_Url'); ?> : <?php echo SITE_URL."rest/deleteproduct"; ?></h4> </div>
<div style="margin-top:20px;"><h4><?php echo $this->Translate('Api_Delete_Product_Input'); ?></h4></div>
<div style="margin-top:20px;"><?php echo $this->Translate('Api_Delete_Product_Title'); ?></div>
<pre style="background-color:#E0E0E0;  font-size:12px">

&lt;?xml version="1.0" encoding="utf-8"?&gt;

&lt;Products&gt;
	&lt;Product&gt;
		&lt;pid&gt; INT &lt;/pid&gt;
	&lt;/Product&gt;
	&lt;!-- ... <?php echo $this->Translate('Api_Delete_Product_Comment'); ?> ... --&gt;
&lt;/Products&gt;
</pre>
<div style="margin-top:20px;">
<h4><?php echo $this->Translate('Api_Delete_Product_Input_Detail'); ?></h4>
</div>
<table border="1" cellspacing="2" cellpadding="4" width="100%">
	<tr>
		<th ><?php echo $this->Translate('Api_Delete_Product_Input_Argument'); ?></th>
		<th ><?php echo $this->Translate('Api_Delete_Product_Input_Type'); ?></th>
 		<th><?php echo $this->Translate('Api_Delete_Product_Input_Occurrence'); ?></th>
		<th><?php echo $this->Translate('Api_Delete_Product_Input_Meaning'); ?></th>
	</tr>
	<tr>
		<td valign="top">Products</td>
		<td valign="top">XML Node</td>
		<td valign="top"><?php echo $this->Translate('Api_Delete_Product_Input_O_Products'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Delete_Product_Input_M_Products'); ?></td>
	</tr>
	<tr>
		<td valign="top">Product</td>
		<td valign="top">XML Node</td>
		<td valign="top"><?php echo $this->Translate('Api_Delete_Product_Input_O_Product'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Delete_Product_Input_M_Product'); ?></td>
	</tr>
	<tr>
		<td valign="top">pid</td>
		<td valign="top">INT</td>
		<td valign="top"><?php echo $this->Translate('Api_Delete_Product_Input_O_Pid'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Delete_Product_Input_M_Pid'); ?></td>
	</tr>
</table>
<div style="margin-top:20px;">
<h4><?php echo $this->Translate('Api_Delete_Product_Output'); ?></h4>
</div>
<pre style="background-color:#E0E0E0;  font-size:12px">
&lt;?xml version="1.0" encoding="utf-8" ?&gt;

&lt;response&gt;
	&lt;result&gt; TEXT &lt;/result&gt;
	&lt;error&gt; TEXT &lt;/error&gt;
	&lt;message&gt; TEXT &lt;/message&gt;
&lt;/response&gt;
</pre>
<div style="margin-top:20px;">
<h4><?php echo $this->Translate('Api_Delete_Product_Output_Detail'); ?></h4>
</div>
<table border="1" cellspacing="2" cellpadding="4" width="100%">
	<tr>
		<th><?php echo $this->Translate('Api_Delete_Product_Output_Return_Value'); ?></th>
		<th><?php echo $this->Translate('Api_Delete_Product_Output_Type'); ?></th>
 		<th><?php echo $this->Translate('Api_Delete_Product_Output_Occurrence'); ?></th>
		<th><?php echo $this->Translate('Api_Delete_Product_Output_Meaning'); ?></th>
	</tr>
	<tr>
		<td >response</td>
		<td >XML Node</td>
		<td><?php echo $this->Translate('Api_Delete_Product_Output_O_Response'); ?></td>
		<td><?php echo $this->Translate('Api_Delete_Product_Output_M_Response'); ?></td>
	</tr>
	<tr>
		<td >result</td>
		<td >TEXT</td>
		<td><?php echo $this->Translate('Api_Delete_Product_Output_O_Result'); ?></td>
		<td><?php echo $this->Translate('Api_Delete_Product_Output_M_Result'); ?>
		</td>
	</tr>
	<tr>
		<td >error</td>
		<td >TEXT</td>
		<td ><?php echo $this->Translate('Api_Delete_Product_Output_O_Error'); ?></td>
		<td><?php echo $this->Translate('Api_Delete_Product_Output_M_Error'); ?></td>
	</tr>
	<tr>
		<td >message</td>
		<td >TEXT</td>
		<td ><?php echo $this->Translate('Delete_Product_Api_Help'); ?></td>
		<td ><?php echo $this->Translate('Delete_Product_Api_Help'); ?></td>
	</tr>
	
</table>

<div style="margin-top: 20px;">
	<h4><?php echo $this->Translate('Api_Delete_Product_Php_Code'); ?></h4>
</div>
<pre style="background-color:#E0E0E0;  font-size:12px">
&lt;?php

$rest_url = "<?php echo SITE_URL.'rest/product'; ?>";
$api_key = "<b>your_api_key</b>";

$data = "&lt;Products&gt;\r\n"
	. "&lt;Product&gt;\r\n"
	. "&lt;pid&gt;46&lt;/pid&gt;\r\n"
	. "&lt;/Product&gt;\r\n"
	. "&lt;/Products&gt;";

$arr_header = array();
$arr_header[] = "Content-Type: text/xml;charset=UTF-8";
$arr_header[] = "Accept: text/xml";
$arr_header[] = "apikey: " . $api_key;

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $rest_url);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
curl_setopt($ch, CURLOPT_HTTPHEADER, $arr_header);

$result = curl_exec($ch);

if(curl_errno($ch)){
   echo 'Curl error: ' . curl_error($ch);
}

curl_close($ch);
echo $result;
?&gt;
</pre>
</div> 