<!--  Crumb  Start -->
<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="<?php echo SITE_URL; ?>user/"><?php echo $this->Translate("User_Home"); ?></a></li>
	   <li class="Last1"><a href="<?php echo SITE_URL; ?>user/apihelp/"><?php echo $this->Translate("Api_Help"); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate("Edit_Product_Api_Help"); ?></span></li>
	</ul>
</div>
<!--  Crumb  end -->

<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate('Edit_Product_Api_Help'); ?>
	</div>
<div style="margin-top:20px;"><h4><?php echo $this->Translate("Api_Edit_Product_Rest_Url"); ?> : <?php echo SITE_URL."rest/product"; ?></h4> </div>
<div style="margin-top:20px;"><h4><?php echo $this->Translate("Api_Edit_Product_Input"); ?></h4></div>
<div style="margin-top:20px;"><?php echo $this->Translate("Api_Edit_Product_Title"); ?></div>
<pre style="background-color:#E0E0E0;  font-size:12px">

&lt;?xml version="1.0" encoding="utf-8"?&gt;

&lt;Products&gt;
	&lt;Product&gt;

		&lt;pid&gt; INT &lt;/pid&gt;
		&lt;name&gt; &lt;![CDATA[TEXT]]&gt; &lt;/name&gt;
		&lt;description&gt; &lt;![CDATA[TEXT]]&gt; &lt;/description&gt;
		&lt;price&gt; DECIMAL &lt;/price&gt;
		&lt;code&gt; &lt;![CDATA[TEXT]]&gt; &lt;/code&gt;
		&lt;weight&gt; DECIMAL &lt;/weight&gt;
		&lt;length&gt; DECIMAL &lt;/length&gt;
		&lt;width&gt; DECIMAL &lt;/width&gt;
		&lt;depth&gt; DECIMAL &lt;/depth&gt;
		&lt;weight_unit&gt; &lt;![CDATA[TEXT]]&gt; &lt;/weight_unit&gt;
		&lt;length_unit&gt; &lt;![CDATA[TEXT]]&gt; &lt;/length_unit&gt;
		&lt;start_sales&gt; BOOLEAN &lt;/start_sales&gt;
		&lt;available_qty&gt; INT &lt;/available_qty&gt;
		&lt;main_image&gt; URL &lt;/main_image&gt;
		&lt;discount&gt; INT &lt;/discount&gt;
		&lt;available_date&gt; DATETIME &lt;/available_date&gt;
		&lt;expiration_date&gt; DATETIME &lt;/expiration_date&gt;
		&lt;promotion_start_date&gt; DATETIME &lt;/promotion_start_date&gt;
		&lt;promotion_end_date&gt; DATETIME &lt;/promotion_end_date&gt;
		
		&lt;categories&gt;
		  &lt;id&gt; INT &lt;/id&gt;
		  &lt;!-- ... <?php echo $this->Translate("Api_Add_Product_Category_Comment"); ?> ... --&gt;
		&lt;/categories&gt;
		
		&lt;images&gt;
		  &lt;image&gt; URL &lt;/image&gt;
		  &lt;!-- ... <?php echo $this->Translate("Api_Add_Product_Image_Comment"); ?> ... --&gt;
		&lt;/images&gt;
		
		&lt;attributes&gt;
		  &lt;attribute&gt;
			&lt;name&gt; &lt;![CDATA[TEXT]]&gt; &lt;/name&gt;
			&lt;options&gt;
				&lt;value&gt;
					&lt;name&gt; &lt;![CDATA[TEXT]]&gt; &lt;/name&gt;
					&lt;sku&gt; &lt;![CDATA[TEXT]]&gt; &lt;/sku&gt;
					&lt;weight&gt; DECIMAL &lt;/weight&gt;
					&lt;weight_unit&gt; &lt;![CDATA[TEXT]]&gt; &lt;/weight_unit&gt;
					&lt;price&gt; DECIMAL &lt;/price&gt;
					&lt;available_qty&gt; &lt;![CDATA[TEXT]]&gt; &lt;/available_qty&gt;
				&lt;/value&gt;
				&lt;!-- ... <?php echo $this->Translate("Api_Add_Product_Options_Comment"); ?> ... --&gt;
			&lt;/options&gt;
		  &lt;/attribute&gt;
		  &lt;!-- ... <?php echo $this->Translate("Api_Add_Product_Attribute_Comment"); ?> ... --&gt;
		&lt;/attributes&gt;
		
		&lt;languages&gt;
			&lt;language&gt;
				&lt;code&gt; &lt;![CDATA[TEXT]]&gt; &lt;/code&gt;
				&lt;name&gt; &lt;![CDATA[TEXT]]&gt; &lt;/name&gt;
				&lt;description&gt; &lt;![CDATA[TEXT]]&gt; &lt;/description&gt;
			&lt;/language&gt;
			&lt;!-- ...<?php echo $this->Translate("Api_Add_Product_Language_Comment"); ?> ... --&gt;
		&lt;/languages&gt;
		
	&lt;/Product&gt;
&lt;/Products&gt;
</pre>
<div style="margin-top:20px;">
<h4><?php echo $this->Translate("Api_Add_Product_Input_Detail"); ?></h4>
</div>
<table border="1" cellspacing="2" cellpadding="4" width="100%">
	<tr>
		<th ><?php echo $this->Translate("Api_Add_Product_Input_Argument"); ?></th>
		<th ><?php echo $this->Translate("Api_Add_Product_Input_Type"); ?></th>
 		<th><?php echo $this->Translate("Api_Add_Product_Input_Occurrence"); ?></th>
		<th><?php echo $this->Translate("Api_Add_Product_Input_Meaning"); ?></th>
	</tr>
	<tr>
		<td valign="top">Products</td>
		<td valign="top">XML Node</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Products"); ?></td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_M_Products"); ?></td>
	</tr>
	<tr>
		<td valign="top">Product</td>
		<td valign="top">XML Node</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Product"); ?></td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_M_Product"); ?></td>
	</tr>
	<tr>
		<td valign="top">pid</td>
		<td valign="top">INT</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Pid"); ?></td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_M_Pid"); ?></td>
	</tr>
	<tr>
		<td valign="top">name</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Name"); ?></td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_M_Name"); ?></td>
	</tr>
	<tr>
		<td valign="top">description</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Description"); ?></td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_M_Description"); ?></td>
	</tr>
	<tr>
		<td valign="top">price</td>
		<td valign="top">DECIMAL</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Price"); ?></td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_M_Price"); ?></td>
	</tr>
	<tr>
		<td valign="top">code</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Code"); ?></td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_M_Code"); ?></td>
	</tr>
	<tr>
		<td valign="top">weight</td>
		<td valign="top">DECIMAL</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Weight"); ?></td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_M_Weight"); ?></td>
	</tr>
	<tr>
		<td valign="top">length</td>
		<td valign="top">DECIMAL</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Length"); ?></td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_M_Length"); ?></td>
	</tr>
	<tr>
		<td valign="top">width</td>
		<td valign="top">DECIMAL</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Width"); ?></td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_M_Width"); ?></td>
	</tr>
	<tr>
		<td valign="top">depth</td>
		<td valign="top">DECIMAL</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Depth"); ?></td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_M_Depth"); ?></td>
	</tr>
	<tr>
		<td valign="top" >weightunit</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Weight_Unit"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Weight_Unit"); ?></td>
	</tr>
	<tr>
		<td valign="top" >lengthunit</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Length_Unit"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Length_Unit"); ?></td>
	</tr>
	<tr>
		<td valign="top" >start_sales</td>
		<td valign="top">BOOLEAN</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Start_Sale"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Start_Sale"); ?></td>
	</tr>
	<tr>
		<td valign="top" >available_qty</td>
		<td valign="top">INT</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Available_Qty"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Available_Qty"); ?></td>
	</tr>
	<tr>
		<td valign="top" >main_image</td>
		<td valign="top">URL</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Main_Image"); ?>Optional,Single</td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Main_Image"); ?></td>
	</tr>
	<tr>
		<td valign="top" >discount</td>
		<td valign="top">INT</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Discount"); ?>Optional,Single</td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Discount"); ?></td>
	</tr>
	<tr>
		<td valign="top" >available_date</td>
		<td valign="top">DATETIME</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Available_Date"); ?>Optional,Single</td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Available_Date"); ?></td>
	</tr>
	<tr>
		<td valign="top" >expiration_date</td>
		<td valign="top">DATETIME</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Expiration_Date"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Expiration_Date"); ?></td>
	</tr>
	<tr>
		<td valign="top" >promotion_start_date</td>
		<td valign="top">DATETIME</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Promo_Start_Date"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Promo_Start_Date"); ?></td>
	</tr>
	<tr>
		<td valign="top" >promotion_end_date</td>
		<td valign="top">DATETIME</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Promo_End_Date"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Promo_End_Date"); ?></td>
	</tr>
	
	<tr>
		<td valign="top" >categories</td>
		<td valign="top">XML node</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Categories"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Categories"); ?></td>
	</tr>
	<tr>
		<td valign="top" >id</td>
		<td valign="top">INT</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Id"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Id"); ?></td>
	</tr>
	<tr>
		<td valign="top">images</td>
		<td valign="top">XML Node</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Images"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Images"); ?></td>
	</tr>
	<tr>
		<td valign="top">image</td>
		<td valign="top">URL</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Image"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Image"); ?></td>
	</tr>
	<tr>
		<td valign="top">attributes</td>
		<td valign="top">XML Node</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Atrbs"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Atrbs"); ?></td>
	</tr>
	<tr>
		<td valign="top">attribute</td>
		<td valign="top">XML Node</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Atrbs_Attribute"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Atrbs_Attribute"); ?></td>
	</tr>
	<tr>
		<td valign="top">name</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Atrbs_Attribute_Name"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Atrbs_Attribute_Name"); ?></td>
	</tr>
	<tr>
		<td valign="top">options</td>
		<td valign="top">XML Node</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Atrbs_Attribute_Opt"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Atrbs_Attribute_Opt"); ?></td>
	</tr>
	<tr>
		<td valign="top">value</td>
		<td valign="top">XML Node</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Atrbs_Attribute_Opt_Val"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Atrbs_Attribute_Opt_Val"); ?></td>
	</tr>
	<tr>
		<td valign="top">name</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Atrbs_Attribute_Opt_Val_Name"); ?></td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_M_Atrbs_Attribute_Opt_Val_Name"); ?></td>
	</tr>
	<tr>
		<td valign="top">sku</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Atrbs_Attribute_Opt_Val_Sku"); ?></td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_M_Atrbs_Attribute_Opt_Val_Sku"); ?></td>
	</tr>
	<tr>
		<td valign="top">weight</td>
		<td valign="top">DECIMAL</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Atrbs_Attribute_Opt_Val_Weight"); ?></td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_M_Atrbs_Attribute_Opt_Val_Weight"); ?></td>
	</tr>
	<tr>
		<td valign="top">weight_unit</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Atrbs_Attribute_Opt_Val_Weight_Unit"); ?></td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_M_Atrbs_Attribute_Opt_Val_Weight_Unit"); ?></td>
	</tr>
	<tr>
		<td valign="top">price</td>
		<td valign="top">DECIMAL</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Atrbs_Attribute_Opt_Val_Price"); ?></td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_M_Atrbs_Attribute_Opt_Val_Price"); ?></td>
	</tr>
	<tr>
		<td valign="top">available_qty</td>
		<td valign="top">INT</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Atrbs_Attribute_Opt_Val_Avalible_Qty"); ?></td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_M_Atrbs_Attribute_Opt_Val_Avalible_Qty"); ?></td>
	</tr>
	<tr>
		<td valign="top">languages</td>
		<td valign="top">XML Node</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Langs"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Langs"); ?></td>
	</tr>
	<tr>
		<td valign="top">language</td>
		<td valign="top">XML Node</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Langs_Language"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Langs_Language"); ?></td>
	</tr>
	<tr>
		<td valign="top">code</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Langs_Language_Code"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Langs_Language_Code"); ?></td>
	</tr>
	<tr>
		<td valign="top">name</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Langs_Language_Name"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Langs_Language_Name"); ?></td>
	</tr>
	<tr>
		<td valign="top">description</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate("Api_Edit_Product_Input_O_Langs_Language_Desc"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Input_M_Langs_Language_Desc"); ?></td>
	</tr>
</table>
<div style="margin-top:20px;">
<h4><?php echo $this->Translate("Api_Edit_Product_Output"); ?></h4>
</div>
<pre style="background-color:#E0E0E0;  font-size:12px">
&lt;?xml version="1.0" encoding="utf-8" ?&gt;

&lt;response&gt;
	&lt;result&gt; TEXT &lt;/result&gt;
	&lt;error&gt; TEXT &lt;/error&gt;
	&lt;warning&gt; TEXT &lt;/warning&gt;
&lt;/response&gt;
</pre>
<div style="margin-top:20px;">
<h4><?php echo $this->Translate("Api_Edit_Product_Output_Detail"); ?></h4>
</div>
<table border="1" cellspacing="2" cellpadding="4" width="100%">
	<tr>
		<th ><?php echo $this->Translate("Api_Edit_Product_Output_Return_Value"); ?></th>
		<th ><?php echo $this->Translate("Api_Edit_Product_Output_Type"); ?></th>
 		<th><?php echo $this->Translate("Api_Edit_Product_Output_Occurrence"); ?></th>
		<th><?php echo $this->Translate("Api_Edit_Product_Output_Meaning"); ?></th>
	</tr>
	<tr>
		<td >response</td>
		<td >XML Node</td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Output_O_Response"); ?></td>
		<td><?php echo $this->Translate("Api_Edit_Product_Output_M_Response"); ?></td>
	</tr>
	<tr>
		<td >result</td>
		<td >TEXT</td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Output_O_Result"); ?></td>
		<td><?php echo $this->Translate("Api_Edit_Product_Output_M_Result"); ?>	</td>
	</tr>
	<tr>
		<td >error</td>
		<td >TEXT</td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Output_O_Error"); ?></td>
		<td><?php echo $this->Translate("Api_Edit_Product_Output_M_Error"); ?></td>
	</tr>
	<tr>
		<td >warning</td>
		<td >TEXT</td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Output_O_Warning"); ?></td>
		<td ><?php echo $this->Translate("Api_Edit_Product_Output_M_Warning"); ?></td>
	</tr>
	
</table>

<div style="margin-top: 20px;">
	<h4><?php echo $this->Translate("Api_Edit_Product_Php_Code"); ?></h4>
</div>
<pre style="background-color:#E0E0E0;  font-size:12px">
&lt;?php

$rest_url = "<?php echo SITE_URL.'rest/product'; ?>";
$api_key = "<b>your_api_key</b>";

$data = "&lt;Products&gt;\r\n"
	. "&lt;Product&gt;\r\n"
	. "&lt;pid&gt;46&lt;/pid&gt;\r\n"
	. "&lt;name&gt;&lt;![CDATA[first product]]&gt;&lt;/name&gt;\r\n"
	. "&lt;description&gt;&lt;![CDATA[first product description]]&gt;&lt;/description&gt;\r\n"
	. "&lt;price&gt;10.10&lt;/price&gt;\r\n"
	. "&lt;code&gt;&lt;![CDATA[first1]]&gt;&lt;/code&gt;\r\n"
	. "&lt;weight&gt;2&lt;/weight&gt;\r\n"
	. "&lt;length&gt;10&lt;/length&gt;\r\n"
	. "&lt;width&gt;5&lt;/width&gt;\r\n"
	. "&lt;depth&gt;10&lt;/depth&gt;\r\n"
	. "&lt;weight_unit&gt;&lt;![CDATA[Kgs]]&gt;&lt;/weight_unit&gt;\r\n"
	. "&lt;length_unit&gt;&lt;![CDATA[Mt]]&gt;&lt;/length_unit&gt;\r\n"
	. "&lt;start_sales&gt;0&lt;/start_sales&gt;\r\n"
	. "&lt;available_qty&gt;10&lt;/available_qty&gt;\r\n"
	. "&lt;main_image&gt;http://c69282.r82.cf3.rackcdn.com/PALLINE.jpg&lt;/main_image&gt;\r\n"
	. "&lt;discount&gt;2&lt;/discount&gt;\r\n"
	. "&lt;available_date&gt;2011-10-07&lt;/available_date&gt;"
	. "&lt;expiration_date&gt;2011-10-31&lt;/expiration_date&gt;"
	. "&lt;promotion_start_date&gt;2011-10-07&lt;/promotion_start_date&gt;"
	. "&lt;promotion_end_date&gt;2011-10-31&lt;/promotion_end_date&gt;"
	. "&lt;categories&gt;\r\n"
	. "&lt;id&gt;3&lt;/id&gt;\r\n"
	. "&lt;id&gt;4&lt;/id&gt;\r\n"
	. "&lt;/categories&gt;\r\n"
	. "&lt;images&gt;\r\n"
	. "&lt;image&gt;http://c69282.r82.cf3.rackcdn.com/business_1.jpg&lt;/image&gt;\r\n"
	. "&lt;/images&gt;\r\n"
	. "&lt;attributes&gt;\r\n"
	. "&lt;attribute&gt;\r\n"
	. "&lt;name&gt;&lt;![CDATA[colors]]&gt;&lt;/name&gt;\r\n"
	. "&lt;options&gt;\r\n"
	. "&lt;value&gt;"
	. "&lt;name&gt;&lt;![CDATA[sizeM]]&gt;&lt;/name&gt;\r\n"
	. "&lt;sku&gt;&lt;![CDATA[product1_red_m]]&gt;&lt;/sku&gt;\r\n"
	. "&lt;weight&gt;1&lt;/weight&gt;\r\n"
	. "&lt;weight_unit&gt;&lt;![CDATA[Kgs]]&gt;&lt;/weight_unit&gt;\r\n"
	. "&lt;price&gt;2&lt;/price&gt;\r\n"
	. "&lt;available_qty&gt;10&lt;/available_qty&gt;\r\n"
	. "&lt;/value&gt;\r\n"
	. "&lt;/options&gt;\r\n"
	. "&lt;/attribute&gt;\r\n"
	. "&lt;/attributes&gt;\r\n"
	. "&lt;/Product&gt;\r\n"
	. "&lt;/Products&gt;";

$arr_header = array();
$arr_header[] = "Content-Type: text/xml;charset=UTF-8";
$arr_header[] = "Accept: text/xml";
$arr_header[] = "apikey: " . $api_key;

$fp = fopen('php://temp/', 'w');
if (!$fp) {
    die('<?php echo $this->Translate("Api_Edit_Product_Err_Temp_Data"); ?>');
}
$data = urlencode($data);

fwrite($fp, $data);
fseek($fp, 0); 

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $rest_url);
curl_setopt($ch, CURLOPT_PUT, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_BINARYTRANSFER, true);
curl_setopt($ch, CURLOPT_INFILE, $fp); // file pointer
curl_setopt($ch, CURLOPT_INFILESIZE, strlen($data));    
curl_setopt($ch, CURLOPT_HTTPHEADER, $arr_header);

$result = curl_exec($ch);

if(curl_errno($ch)){
   echo 'Curl error: ' . curl_error($ch);
}


// <?php echo $this->Translate("Api_Edit_Product_Err_Temp_Data"); ?>
fclose($fp);

curl_close($ch);
echo $result;
?&gt;
</pre>
</div> 

