<!--  Crumb  Start -->
<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="<?php echo SITE_URL; ?>user/"><?php echo $this->Translate("User_Home"); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate("Api_Help"); ?></span></li>
	</ul>
</div>
<!--  Crumb  end -->


<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate('Api_List'); ?>
	</div>
	
	<div style="margin-top:20px;"><a href="<?php echo SITE_URL . 'user/apihelp/addproduct'; ?>"><?php echo $this->Translate("Add_Product_API"); ?></a></div>
	<div style="margin-top:20px;"><a href="<?php echo SITE_URL . 'user/apihelp/editproduct'; ?>"><?php echo $this->Translate("Edit_Product_API"); ?></a></div>
	<div style="margin-top:20px;"><a href="<?php echo SITE_URL . 'user/apihelp/deleteproduct'; ?>"><?php echo $this->Translate("Delete_Product_API"); ?></a></div>
	<div style="margin-top:20px;"><a href="<?php echo SITE_URL . 'user/apihelp/inventory'; ?>"><?php echo $this->Translate("Product_Inventory_API"); ?></a></div>
	<div style="margin-top:20px;"><a href="<?php echo SITE_URL . 'user/apihelp/setstore'; ?>"><?php echo $this->Translate("Set_Store_API"); ?></a></div>	         
</div>