<!--  Crumb  Start -->
<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="<?php echo SITE_URL; ?>user/"><?php echo $this->Translate("User_Home"); ?></a></li>
	   <li class="Last1"><a href="<?php echo SITE_URL; ?>user/apihelp/"><?php echo $this->Translate("Api_Help"); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate("Set_Store_Api_Help"); ?></span></li>
	</ul>
</div>
<!--  Crumb  end -->

<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate('Set_Store_Api_Help'); ?>
	</div>
<div style="margin-top:20px;"><h4><?php echo $this->Translate('Api_Set_Store_Rest_Url'); ?> : <?php echo SITE_URL."rest/inventory"; ?></h4> </div>
<div style="margin-top:20px;"><h4><?php echo $this->Translate('Api_Set_Store_Input'); ?></h4></div>
<div style="margin-top:20px;"><?php echo $this->Translate('Api_Set_Store_Title'); ?></div>
<pre style="background-color:#E0E0E0;  font-size:12px">

&lt;?xml version="1.0" encoding="utf-8"?&gt;

&lt;store_info&gt;
	
	&lt;store_name&gt; &lt;![CDATA[TEXT]]&gt; &lt;/store_name&gt;
	&lt;store_description&gt; &lt;![CDATA[TEXT]]&gt; &lt;/store_description&gt;
	&lt;store_terms_policy&gt; &lt;![CDATA[TEXT]]&gt; &lt;/store_terms_policy&gt;
	&lt;return_policy&gt; &lt;![CDATA[TEXT]]&gt; &lt;/return_policy&gt;
	&lt;store_address&gt; &lt;![CDATA[TEXT]]&gt; &lt;/store_address&gt;
	&lt;store_country&gt; &lt;![CDATA[TEXT]]&gt; &lt;/store_country&gt;
	&lt;store_state&gt; &lt;![CDATA[TEXT]]&gt; &lt;/store_state&gt;
	&lt;store_city&gt; &lt;![CDATA[TEXT]]&gt; &lt;/store_city&gt;
	&lt;store_zipcode&gt; &lt;![CDATA[TEXT]]&gt; &lt;/store_zipcode&gt;
	&lt;paypal_address&gt; &lt;![CDATA[TEXT]]&gt; &lt;/paypal_address&gt;
	&lt;currency&gt; &lt;![CDATA[TEXT]]&gt; &lt;/currency&gt;
	
	&lt;shipping_table&gt;
		&lt;shipping_name&gt; &lt;![CDATA[TEXT]]&gt; &lt;/shipping_name&gt;	
		&lt;shipping_zone&gt; &lt;![CDATA[TEXT]]&gt; &lt;/shipping_zone&gt;	
		&lt;shipping_cost&gt; &lt;![CDATA[TEXT]]&gt; &lt;/shipping_cost&gt;	
		&lt;languages&gt;
			&lt;language&gt;
				&lt;shipping_name&gt; &lt;![CDATA[TEXT]]&gt; &lt;/shipping_name&gt;	
			&lt;/language&gt;
		&lt;!-- ... <?php echo $this->Translate('Api_Add_Product_Language_Comment'); ?> ... --&gt;
	&lt;/languages&gt;
	&lt;/shipping_table&gt;
	&lt;!-- ... more shipping table nodes here ... --&gt;
	&lt;languages&gt;
		&lt;language&gt;
			&lt;store_description&gt; &lt;![CDATA[TEXT]]&gt; &lt;/store_description&gt;
			&lt;store_terms_policy&gt; &lt;![CDATA[TEXT]]&gt; &lt;/store_terms_policy&gt;
			&lt;return_policy&gt; &lt;![CDATA[TEXT]]&gt; &lt;/return_policy&gt;
		&lt;/language&gt;
		&lt;!-- ... <?php echo $this->Translate('Api_Add_Product_Language_Comment'); ?> ... --&gt;
	&lt;/languages&gt;
	
&lt;/store_info&gt;
</pre>
<div style="margin-top:20px;">
<h4><?php echo $this->Translate('Api_Set_Store_Input_Detail'); ?></h4>
</div>
<table border="1" cellspacing="2" cellpadding="4" width="100%">
	<tr>
		<th><?php echo $this->Translate('Api_Set_Store_Input_Argument'); ?></th>
		<th><?php echo $this->Translate('Api_Set_Store_Input_Type'); ?></th>
 		<th><?php echo $this->Translate('Api_Set_Store_Input_Occurrence'); ?></th>
		<th><?php echo $this->Translate('Api_Set_Store_Input_Meaning'); ?></th>
	</tr>
	<tr>
		<td valign="top">store_info</td> 
		<td valign="top">XML Node</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Store_Info'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Store_Info'); ?></td>
	</tr>
	<tr>
		<td valign="top">store_name</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Store_Name'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Store_Name'); ?></td>
	</tr>
	<tr>
		<td valign="top">store_description</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Store_Desc'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Store_Desc'); ?></td>
	</tr>
	<tr>
		<td valign="top">store_terms_policy</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Store_Term_Policy'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Store_Term_Policy'); ?></td>
	</tr>
	<tr>
		<td valign="top">return_policy</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Return_Policy'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Return_Policy'); ?></td>
	</tr>
	<tr>
		<td valign="top">store_address</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Store_Address'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Store_Address'); ?></td>
	</tr>
	<tr>
		<td valign="top">store_country</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Store_Country'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Store_Country'); ?></td>
	</tr>
	<tr>
		<td valign="top">store_state</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Store_State'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Store_State'); ?></td>
	</tr>
	<tr>
		<td valign="top">store_city</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Store_City'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Store_City'); ?></td>
	</tr>
	<tr>
		<td valign="top">store_zipcode</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Store_Zipcode'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Store_Zipcode'); ?></td>
	</tr>
	<tr>
		<td valign="top">paypal_address</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Paypal_Address'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Paypal_Address'); ?></td>
	</tr>
	<tr>
		<td valign="top">currency</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Currency'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Currency'); ?></td>
	</tr>
	
	<tr>
		<td valign="top">shipping_table</td>
		<td valign="top">XML Node</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Shipping_Table'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Shipping_Table'); ?></td>
	</tr>
	<tr>
		<td valign="top">shipping_name</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Shipping_Table_Name'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Shipping_Table_Name'); ?></td>
	</tr>
	<tr>
		<td valign="top">shipping_zone</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Shipping_Table_Zone'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Shipping_Table_Zone'); ?></td>
	</tr>
	<tr>
		<td valign="top">shipping_cost</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Shipping_Table_Cost'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Shipping_Table_Cost'); ?></td>
	</tr>
	<tr>
		<td valign="top">languages</td>
		<td valign="top">XML Node</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Shipping_Table_Langs'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Shipping_Table_Langs'); ?></td>
	</tr>
	<tr>
		<td valign="top">language</td>
		<td valign="top">XML Node</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Shipping_Table_Langs_Language'); ?></td>
		<td ><?php echo $this->Translate('Api_Set_Store_Input_M_Shipping_Table_Langs_Language'); ?></td>
	</tr>
	<tr>
		<td valign="top">code</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Shipping_Table_Langs_Language_Code'); ?></td>
		<td ><?php echo $this->Translate('Api_Set_Store_Input_M_Shipping_Table_Langs_Language_Code'); ?></td>
	</tr>
	<tr>
		<td valign="top">name</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Shipping_Table_Langs_Language_Shipp_Name'); ?></td>
		<td ><?php echo $this->Translate('Api_Set_Store_Input_M_Shipping_Table_Langs_Language_Shipp_Name'); ?></td>
	</tr>
	<tr>
		<td valign="top">languages</td>
		<td valign="top">XML Node</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Langs'); ?></td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_M_Langs'); ?></td>
	</tr>
	<tr>
		<td valign="top">language</td>
		<td valign="top">XML Node</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Langs_Language'); ?></td>
		<td ><?php echo $this->Translate('Api_Set_Store_Input_M_Langs_Language'); ?></td>
	</tr>
	<tr>
		<td valign="top">code</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Langs_Language_Code'); ?></td>
		<td ><?php echo $this->Translate('Api_Set_Store_Input_M_Langs_Language_Code'); ?></td>
	</tr>
	<tr>
		<td valign="top">store_description</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Langs_Language_Store_Desc'); ?></td>
		<td ><?php echo $this->Translate('Api_Set_Store_Input_M_Langs_Language_Store_Desc'); ?></td>
	</tr>
	<tr>
		<td valign="top">store_terms_policy</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Langs_Language_Store_Term_Policy'); ?></td>
		<td ><?php echo $this->Translate('Api_Set_Store_Input_M_Langs_Language_Store_Term_Policy'); ?></td>
	</tr>
	<tr>
		<td valign="top">return_policy</td>
		<td valign="top">TEXT</td>
		<td valign="top"><?php echo $this->Translate('Api_Set_Store_Input_O_Langs_Language_Return_Policy'); ?></td>
		<td ><?php echo $this->Translate('Api_Set_Store_Input_M_Langs_Language_Return_Policy'); ?></td>
	</tr>
</table>
<div style="margin-top:20px;">
<h4><?php echo $this->Translate('Api_Set_Store_Output'); ?></h4>
</div>
<pre style="background-color:#E0E0E0;  font-size:12px">
&lt;?xml version="1.0" encoding="utf-8" ?&gt;

&lt;response&gt;
	&lt;result&gt; TEXT &lt;/result&gt;
	&lt;error&gt; TEXT &lt;/error&gt;
	&lt;message&gt;
		&lt;warning&gt; TEXT &lt;/warning&gt;
	&lt;/message&gt;
&lt;/response&gt;
</pre>
<div style="margin-top:20px;">
<h4><?php echo $this->Translate('Set_Store_Api_Help'); ?></h4>
</div>
<table border="1" cellspacing="2" cellpadding="4" width="100%">
	<tr>
		<th><?php echo $this->Translate('Api_Set_Store_Output_Return_Value'); ?></th>
		<th><?php echo $this->Translate('Api_Set_Store_Output_Type'); ?></th>
 		<th><?php echo $this->Translate('Api_Set_Store_Output_Occurrence'); ?></th>
		<th><?php echo $this->Translate('Api_Set_Store_Output_Meaning'); ?></th>
	</tr>
	<tr>
		<td >response</td>
		<td >XML Node</td>
		<td ><?php echo $this->Translate('Api_Set_Store_Output_O_Response'); ?></td>
		<td><?php echo $this->Translate('Api_Set_Store_Output_M_Response'); ?></td>
	</tr>
	<tr>
		<td >result</td>
		<td >TEXT</td>
		<td ><?php echo $this->Translate('Api_Set_Store_Output_O_Result'); ?></td>
		<td><?php echo $this->Translate('Api_Set_Store_Output_M_Result'); ?>
		</td>
	</tr>
	<tr>
		<td >error</td>
		<td >TEXT</td>
		<td ><?php echo $this->Translate('Api_Set_Store_Output_O_Error'); ?></td>
		<td><?php echo $this->Translate('Api_Set_Store_Output_M_Error'); ?></td>
	</tr>
	<tr>
		<td >message</td>
		<td >TEXT</td>
		<td ><?php echo $this->Translate('Api_Set_Store_Output_O_Message'); ?></td>
		<td ><?php echo $this->Translate('Api_Set_Store_Output_M_Message'); ?></td>
	</tr>
	<tr>
		<td >warning</td>
		<td >TEXT</td>
		<td ><?php echo $this->Translate('Api_Set_Store_Output_O_Warning'); ?></td>
		<td ><?php echo $this->Translate('Api_Set_Store_Output_M_Warning'); ?></td>
	</tr>
</table>

<div style="margin-top: 20px;">
	<h4><?php echo $this->Translate('Set_Store_Api_Help'); ?></h4>
</div>
<pre style="background-color:#E0E0E0;  font-size:12px">
&lt;?php

$rest_url = "<?php echo SITE_URL.'rest/store'; ?>";
$api_key = "<b>your_api_key</b>";

$data = "&lt;store_info&gt;\r\n"
	. "&lt;store_name&gt;&lt;![CDATA[Store name]]&gt;&lt;/store_name&gt;\r\n"
	. "&lt;store_description&gt;&lt;![CDATA[Description of store]]&gt;&lt;/store_description&gt;\r\n"
	. "&lt;store_terms_policy&gt;&lt;![CDATA[Store terms policy]]&gt;&lt;/store_terms_policy&gt;\r\n"
	. "&lt;return_policy&gt;&lt;![CDATA[Store return policy]]&gt;&lt;/return_policy&gt;\r\n"
	. "&lt;store_address&gt;&lt;![CDATA[Address of store]]&gt;&lt;/store_address&gt;\r\n"
	. "&lt;store_country&gt;&lt;![CDATA[US]]&gt;&lt;/store_country&gt;\r\n"
	. "&lt;store_state&gt;&lt;![CDATA[New York]]&gt;&lt;/store_state&gt;\r\n"
	. "&lt;store_city&gt;&lt;![CDATA[New York]]&gt;&lt;/store_city&gt;\r\n"
	. "&lt;store_zipcode&gt;&lt;![CDATA[12345]]&gt;&lt;/store_zipcode&gt;\r\n"
	. "&lt;paypal_address&gt;&lt;![CDATA[paypal@xyz.com]]&gt;&lt;/paypal_address&gt;\r\n"
	. "&lt;currency&gt;&lt;![CDATA[USD]]&gt;&lt;/currency&gt;\r\n"
	. "&lt;shipping_table&gt;\r\n"
	. "&lt;shipping_name&gt;&lt;![CDATA[shipping_method]]&gt;&lt;/shipping_name&gt;\r\n"
	. "&lt;shipping_zone&gt;&lt;![CDATA[US,IT,UK]]&gt;&lt;/shipping_zone&gt;\r\n"
	. "&lt;shipping_cost&gt;&lt;![CDATA[5:5.5,10:11,15:20]]&gt;&lt;/shipping_cost&gt;\r\n"
	. "&lt;languages&gt;\r\n"
	. "&lt;language&gt;\r\n"
	. "&lt;code&gt;&lt;![CDATA[it_IT]]&gt;&lt;/code&gt;\r\n"
	. "&lt;shipping_name&gt;&lt;![CDATA[shipping_name in it]]&gt;&lt;/shipping_name&gt;\r\n"
	. "&lt;/language&gt;\r\n"
	. "&lt;/languages&gt;\r\n"
	. "&lt;/shipping_table&gt;\r\n"
	. "&lt;languages&gt;\r\n"
	. "&lt;language&gt;\r\n"
	. "&lt;code&gt;&lt;![CDATA[it_IT]]&gt;&lt;/code&gt;\r\n"
	. "&lt;store_description&gt;&lt;![CDATA[store desc in it]]&gt;&lt;/store_description&gt;\r\n"
	. "&lt;store_terms_policy&gt;&lt;![CDATA[terms policy in it]]&gt;&lt;/store_terms_policy&gt;\r\n"
	. "&lt;return_policy&gt;&lt;![CDATA[return policy in it]]&gt;&lt;/return_policy&gt;\r\n"
	. "&lt;/language&gt;\r\n"
	. "&lt;/languages&gt;\r\n"
	. "&lt;/store_info&gt;";

$arr_header = array();
$arr_header[] = "Content-Type: text/xml;charset=UTF-8";
$arr_header[] = "Accept: text/xml";
$arr_header[] = "apikey: " . $api_key;


$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $rest_url);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, urlencode($data));
curl_setopt($ch, CURLOPT_HTTPHEADER, $arr_header);

$result = curl_exec($ch);

if(curl_errno($ch)){
   echo 'Curl error: ' . curl_error($ch);
}

curl_close($ch);
echo $result;
?&gt;
</pre>
</div> 

