<div id="storeFooter">
            	<div><img src='<?php echo IMAGES_FB_PATH ?>/sep.jpg' alt="" /></div>
                <div class="footer">
                	<div class="grid_190">
                    	<div class="footerhead"><a class="footerhead" href="#"><?php echo $this->Translate('NewArrivals')?></a></div>
                      <div class="footerhead"><a class="footerhead" href="#"><?php echo $this->Translate('Clothing')?></a></div>
                        <div class="footerhead"><a class="footerhead" href="#"><?php echo $this->Translate('Shoes')?></a></div>
                        <div class="footerhead"><a class="footerhead" href="#"><?php echo $this->Translate('BagAccessories')?></a></div>
                        <div class="footerhead"><a class="footerhead" href="#"><?php echo $this->Translate('Apartment')?></a></div>
					</div>
                    <div class="grid_190">
                    	<div class="footerhead"><?php echo $this->Translate('MyAccount')?></div>
                        <div class="footercontent">
							<ul>
                            	<li><a href="#"><?php echo $this->Translate('MyInfo')?></a></li>
                                <li><a href="#"><?php echo $this->Translate('MyLovedItem')?></a></li>
                                <li><a href="#"><?php echo $this->Translate('Wishlists')?></a></li>
                                <li><a href="#"><?php echo $this->Translate('Notifications')?></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="grid_190">
                    	<div class="footerhead"><?php echo $this->Translate('AboutUs')?></div>
                        <div class="footercontent">
							<ul>
                            	<li><a href="#"><?php echo $this->Translate('SusanStory')?></a></li>
                                <li><a href="#"><?php echo $this->Translate('Testimonials')?></a></li>
                                <li><a href="#"><?php echo $this->Translate('Careers')?>Careers</a></li>
                                <li><a href="#"><?php echo $this->Translate('Press')?></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="grid_190" style="background:none;">
                    	<div class="footerhead"><?php echo $this->Translate('Help')?></div>
                        <div class="footercontent">
                        	<ul>
                            	<li><a href="#"><?php echo $this->Translate('CustomerCare')?></a></li>
                                <li><a href="#"><?php echo $this->Translate('ModStylists')?></a></li>
                                <li><a href="#"><?php echo $this->Translate('FAQ')?></a></li>
                                <li><a href="#"><?php echo $this->Translate('ShippingInfo')?></a></li>
                                <li><a href="#"><?php echo $this->Translate('ReturnExchange')?></a></li>
                                <li><a href="#"><?php echo $this->Translate('SizeFit')?></a></li>
                                <li><a href="#"><?php echo $this->Translate('SiteFeedback')?></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
              <div><img src='<?php echo IMAGES_FB_PATH ?>/sep.jpg' alt="" /></div>
              
                <div class="right">
                	<a href="#"><img src="<?php echo IMAGES_FB_PATH ?>/poweredby_puvoo.png" alt="" style="margin-top:8px; margin-bottom:8px;" /></a>
                </div>
            </div>
			