<div id="storeFooter">
            	<div><img src='<?php echo IMAGES_FB_PATH ?>/sep.jpg' alt="" /></div>
                <div class="footer">
                	<div class="grid_190">
                    	<div class="footerhead"><a class="footerhead" href="#">New Arrivals</a></div>
                      <div class="footerhead"><a class="footerhead" href="#">Clothing</a></div>
                        <div class="footerhead"><a class="footerhead" href="#">Shoes</a></div>
                        <div class="footerhead"><a class="footerhead" href="#">Bags & Accessories</a></div>
                        <div class="footerhead"><a class="footerhead" href="#">Apartment</a></div>
					</div>
                    <div class="grid_190">
                    	<div class="footerhead">My Account</div>
                        <div class="footercontent">
							<ul>
                            	<li><a href="#">My Info</a></li>
                                <li><a href="#">My Loved Items</a></li>
                                <li><a href="#">Wishlists</a></li>
                                <li><a href="#">Notifications</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="grid_190">
                    	<div class="footerhead">About Us</div>
                        <div class="footercontent">
							<ul>
                            	<li><a href="#">Susan's Story</a></li>
                                <li><a href="#">Testimonials</a></li>
                                <li><a href="#">Careers</a></li>
                                <li><a href="#">press</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="grid_190" style="background:none;">
                    	<div class="footerhead">help</div>
                        <div class="footercontent">
                        	<ul>
                            	<li><a href="#">Customer Care</a></li>
                                <li><a href="#">ModStylists</a></li>
                                <li><a href="#">FAQ</a></li>
                                <li><a href="#">Shipping Information</a></li>
                                <li><a href="#">Returns & Exchanges</a></li>
                                <li><a href="#">Size & Fit</a></li>
                                <li><a href="#">Site Feedback</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
              <div><img src='<?php echo IMAGES_FB_PATH ?>/sep.jpg' alt="" /></div>
              
                <div class="right">
                	<a href="#"><img src="<?php echo IMAGES_FB_PATH ?>/poweredby_puvoo.png" alt="" style="margin-top:8px; margin-bottom:8px;" /></a>
                </div>
            	<!--<div><img src='images/sep.jpg' alt="" /></div>
                <div class="storeFooter">
                    <table cellspacing="0" cellpadding="0" border="0" width="100%">
                        <tbody>
                            <tr><td height="10"></td></tr>
                            <tr>
                                <td nowrap="nowrap">
                                    <a href="#">
                                        <img border="0" width="104" height="30" src="images/truste_2.png" alt="" />
                                    </a>
                                </td>
                                <td nowrap="nowrap">
                                    <a href="#">
                                        <img id="flagImage" border="0" src="images/flag_en_US.png" alt="" />
                                    </a>
                                </td>
                                <td nowrap="nowrap">
                                    <div align="center">
                                        <a id="clicktosellfooterlink" href="#" target="external"> Click Here to Sell on Facebook </a>
                                    </div>
                                </td>
                                <td nowrap="nowrap">
                                    <div align="right">
                                        <a target="blank" href="#">
                                            <img border="0" alt="Powered By puvoo" src="images/poweredby_puvoo.png" />
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            <tr><td height="10"></td></tr>
                        </tbody>
                    </table>
                </div>
                <div><img src='images/sep.jpg' alt="" /></div>-->
            </div>