<script src="http://www.thomcurtis.co.uk/facebook/scripts/jquery-1.3.2.min.js" type="text/javascript"></script>

<script language="javascript" type="text/javascript">
function loadPopup()
{
	$('#sellerarea').hide();
	$('#cartarea').show();
	ShowTab(1);
 $("#backgroundPopup").css({"opacity": "0.1"});
 $("#backgroundPopup").fadeIn("fast");
 $("#popupContact").slideDown("slow");
 
 
}

function loadPopup1()
{
	$('#cartarea').hide();
	$('#sellerarea').show();
 $("#backgroundPopup").css({"opacity": "0.1"});
 $("#backgroundPopup").fadeIn("fast");
 $("#popupContact").slideDown("slow");
 
 
}

function disablePopup()
{
 $("#backgroundPopup").fadeOut("slow");
 $("#popupContact").slideUp("slow");
}
function centerPopup()
{
/* $("#popupContact").height('auto');	*/
  
 var windowWidth = document.documentElement.clientWidth;
 var windowHeight = document.documentElement.clientHeight;
 //var popupHeight = $("#innerDIV").height();
 var popupWidth = $("#popupContact").width();
 $("#popupContact").css({"position": "absolute","top": windowHeight/2 - 410/2,"left": windowWidth/2-popupWidth/2});
 $("#backgroundPopup").css({"height": windowHeight});

}

$(document).ready(function()
{
 $(".cart_wrapper").click(function()
 {
  centerPopup();
  loadPopup();
 });

 $("#btn1").click(function()
 {
  centerPopup();
  loadPopup1();
 });
 $("#popupContactClose, .c_btn").click(function()
 {
  disablePopup();
 });
  
 $(document).keypress(function(e)
 {
  if(e.keyCode==27)//Disable popup on pressing `ESC`
  {
   disablePopup();
  }
 });
});
</script>
		
<div id="header">
        	<div class="left" style="width:250px;">
            	<a href="<?php echo SITE_FB_URL ?>index/"><img src="<?php echo IMAGES_FB_PATH ?>/logo.png" width="239" height="79" alt="" /></a>
            </div>
            <div class="right">
            	<div align="right" style="margin-bottom:10px; margin-top:10px;">
                	<table cellspacing="0" cellpadding="0" border="0">
                        <tbody>
                            <tr>
                            	<td><input type="button" value="" class="join_marketplace" /></td>
                                <td style="padding-left:10px;">
									
                                	<select id="cid" style="height:26px; width:120px; " name="cid" class="inputtext">
                                      <option   value="0" selected="selected"><?php echo $this->Translate('SelectCountry')?></option>
                                        <?php foreach($this->CountryCombo as $value){?>
											<option class="flag flag-<?php echo strtolower($value['country_iso2']); ?>" value="<?php echo $value['country_id']; ?>">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['country_name']; ?></option>
											<?php }?>
                                    </select>
                                </td>
                            </tr>
                         </tbody>
                    </table>
                </div>
            	<?php echo $this->render('search.phtml') ?>
            </div>
            <div class="clear"></div>
        </div>