
<script language="javascript" type="text/javascript">

var produImagePath = "<?php echo SITE_PRODUCT_IMAGES_PATH;?>";
</script>
		
<div id="header">
        	<div class="left" style="width:250px;">
            	<a href="<?php echo SITE_FB_URL ?>" target="_top"><img src="<?php echo IMAGES_FB_PATH ?>/logo.png" width="239" height="79" alt="" /></a>
            </div>
            <div class="right">
            	<div align="right" style="margin-bottom:10px; margin-top:10px;margin-right:3px;">
                	<table cellspacing="0" cellpadding="0" border="0">
                        <tbody>
                            <tr>
                            	<td><a href="http://www.puvoo.com/marketplace.php" target="_blank"><input type="button" value="" class="join_marketplace" /></a></td>
                                <td style="padding-left:10px;">
									
                                	<select id="cid" style="height:26px; width:190px;" name="cid" onchange="javascript:changelang(this.value);" class="mydds" >
                                      
                                        <?php foreach($this->CountryCombo as $value){?>
											<option title="<?php echo IMAGES_PATH; ?>/fb/countryflag/<?php echo $value['country_iso2'];?>.png" class="flag flag-<?php echo strtolower($value['country_iso2']); ?>"  value="<?php echo $value['country_id']; ?>" <?php if($value['country_id'] == $this->sel_country){?> selected="selected" <?php }?>><?php echo $value['country_name']; ?></option>
											<?php }?>
                                    </select>
                                </td>
                            </tr>
                         </tbody>
                    </table>
                </div>
            	<?php echo $this->render('search.phtml') ?>
            </div>
            <div class="clear"></div>
</div>

<script type="text/javascript">
$(document).ready(function() {

try {
		oHandler = $("#cid").msDropDown().data("dd");
		//oHandler.visible(true);
		//alert($.msDropDown.version);
		//$.msDropDown.create("body select");
		$("#ver").html($.msDropDown.version);
		} catch(e) {
			alert("Error: "+e.message);
		}
})

</script>