<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link rel="stylesheet" href="<?php echo CSS_FB_PATH ?>/style.css" />
<link rel="stylesheet" href="<?php echo CSS_FB_PATH ?>/menu.css" />
<link rel="stylesheet" href="<?php echo CSS_FB_PATH ?>/popup.css" />
<link rel="stylesheet" href="<?php echo CSS_FB_PATH ?>/jquery.jscrollpane.css" />
<link rel="stylesheet" href="<?php echo CSS_FB_PATH ?>/demo.css" />
<link rel="stylesheet" href="<?php echo CSS_FB_PATH ?>/flag.css" />
<link rel="stylesheet" href="<?php echo CSS_FB_PATH ?>/nivo-slider.css" />
<![if  IE 6]> <link href="<?php echo CSS_FB_PATH ?>/ie6.css" rel="stylesheet" type="text/css" />  <![endif]>
<script type = "text/javascript" src = "<?php echo JS_PATH ?>/jquery-1.5.1.min.js"></script>
<script type="text/javascript" src="<?php echo JS_FB_PATH ?>/jquery.mousewheel.js"></script>
<script type="text/javascript" src="<?php echo JS_FB_PATH ?>/script.js"></script>
<script type="text/javascript" src="<?php echo JS_FB_PATH ?>/jquery.nivo.slider.js"></script>
<style type="text/css" id="page-css">
			/* Styles specific to this particular page */
			.scroll-pane
			{
				width: 100%;
				height: 255px;
				overflow: auto;
			}
			.horizontal-only
			{
				height: auto;
				max-height: 255px;
			}
		</style> 

<title>Puvoo</title>
</head>
<body id="body">
	<?php echo $this->render('cart/index.phtml') ?>
	<div class="width">
    	<?php echo $this->render('header.phtml') ?>
		<?php echo $this->render('menu.phtml') ?>
         <div id="mainbody">
			<div id="mainwhitebg">
				<?php echo $this->render('leftMenu.phtml') ?>
				<?php echo $this->layout()->content;?>
				<div class="clear"></div>
			</div>
			<?php echo $this->render('footer.phtml')?>
         </div>
		
    </div>
	<div id="fb-root"></div>

<script type="text/javascript" src="<?php echo JS_FB_PATH ?>/functions.js"></script>
<script type="text/javascript" src="<?php echo JS_FB_PATH ?>/search.js"></script>
<script type="text/javascript">
	var site_url = '<?php echo SITE_FB_URL;?>';

	window.fbAsyncInit = function() {
	
	FB.Canvas.setSize({ height: 1478 });
	
	}
	
	// Do things that will sometimes call sizeChangeCallback()
	
	function sizeChangeCallback() {
	
	FB.Canvas.setSize({ height: 1478 });
	
	}
</script>

<script type="text/javascript" src="http://connect.facebook.net/en_US/all.js"></script>

<script type="text/javascript">

FB.init({

appId : '236169479754038',

status : true, // check login status

cookie : true, // enable cookies to allow the server to access the session

xfbml : true // parse XFBML

});

</script>
</body>
</html>
