<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<link rel="stylesheet" href="<?php echo CSS_FB_PATH ?>/style.css" />
<link rel="stylesheet" href="<?php echo CSS_FB_PATH ?>/menu.css" />
<link rel="stylesheet" href="<?php echo CSS_FB_PATH ?>/popup.css" />
<link rel="stylesheet" href="<?php echo CSS_FB_PATH ?>/jquery.jscrollpane.css" />
<link rel="stylesheet" href="<?php echo CSS_FB_PATH ?>/demo.css" />
<link rel="stylesheet" href="<?php echo CSS_FB_PATH ?>/flag.css" />
<link rel="stylesheet" href="<?php echo CSS_FB_PATH ?>/nivo-slider.css" />
<link rel="stylesheet" href="<?php echo CSS_FB_PATH ?>/nivostyle.css" />
<link rel="stylesheet" href="<?php echo CSS_FB_PATH ?>/themes/default/default.css" type="text/css" media="screen" />
<![if  IE 6]> <link href="<?php echo CSS_FB_PATH ?>/ie6.css" rel="stylesheet" type="text/css" />  <![endif]>
<script type="text/javascript" src="<?php echo JS_FB_PATH ?>/jquery-1.6.1.min.js?r=<?php echo $this->random;?>"></script>
<script type="text/javascript" src="<?php echo JS_FB_PATH ?>/jquery.nivo.slider.pack.js?r=<?php echo $this->random;?>"></script>
<script type ="text/javascript" src = "<?php echo JS_PATH ?>/jquery.validate.js?r=<?php echo $this->random;?>"></script>
<script type="text/javascript" src="http://connect.facebook.net/en_US/all.js?r=<?php echo $this->random;?>"></script>
<script type="text/javascript" src="<?php echo JS_FB_PATH ?>/jquery.mousewheel.js?r=<?php echo $this->random;?>"></script>
<script type="text/javascript" src="<?php echo JS_FB_PATH ?>/script.js?r=<?php echo $this->random;?>"></script>
<script type="text/javascript" src="<?php echo JS_FB_PATH ?>/functions.js?r=<?php echo $this->random;?>"></script>
<script type="text/javascript" src="<?php echo JS_FB_PATH ?>/search.js?r=<?php echo $this->random;?>"></script>

<style type="text/css" id="page-css">
			/* Styles specific to this particular page */
			.scroll-pane
			{
				width: 100%;
				height: 255px;
				overflow: auto;
			}
			.horizontal-only
			{
				height: auto;
				max-height: 255px;
			}
		</style> 

<title>Puvoo</title>
</head>
<body id="body">
<input type="hidden" name="facebook_userid" id="facebook_userid" value="<?php echo $this->facebook_user_numeric_id; ?>">
<input type="hidden" name="facebook_user_numeric_id" id="facebook_user_numeric_id" value="<?php echo $this->facebook_user_numeric_id; ?>">
<input type="hidden" name="cart_userId" id="cart_userId" value="<?php echo $this->cartuserId; ?>">
	<?php echo $this->render('cart/index.phtml') ?>
	<div class="width">
    	<?php echo $this->render('header.phtml') ?>
		<?php echo $this->render('menu.phtml') ?>
         <div id="mainbody">
			<div id="mainwhitebg">
				<?php echo $this->render('leftMenu.phtml') ?>
				<?php echo $this->layout()->content;?>
				<div class="clear"></div>
			</div>
			
         </div>
		<?php echo $this->render('footer.phtml')?>
    </div>
	<div id="fb-root"></div>


<script type="text/javascript">
	var site_url = '<?php echo SITE_AJX_URL;?>';
	var site_fb_url = '<?php echo SITE_FB_URL;?>';
	var def_curr_symbol = '<?php echo DEFAULT_CURRENCY_SYMBOL;?>';
	var def_curr_code = '<?php echo DEFAULT_CURRENCY_CODE;?>';
	var request_url = '<?php echo FB_REDIRECT_URL;?>';
	

	/*window.fbAsyncInit = function() {
	
	FB.Canvas.setSize({ height: 1078 });
	
	}
	
	// Do things that will sometimes call sizeChangeCallback()
	
	function sizeChangeCallback() {
	
	FB.Canvas.setSize({ height: 1078 });
	
	}*/
	
	$(document).ready(function(){
			setTimeout("test()",3000); 
    });

function test()
{	
	FB.Canvas.setAutoResize();
}

</script>


<script type="text/javascript">

FB.init({

appId : '<?php echo FACEBOOK_APP_API_ID; ?>',

status : true, // check login status

cookie : true, // enable cookies to allow the server to access the session

xfbml : true // parse XFBML


});

FB.Event.subscribe('edge.create', function(href, widget) {
 // Do something, e.g. track the click on the "Like" button here
 	
	/*alert(widget);
 	FB.Event.subscribe('auth.authResponseChange', function(response) {
		
		alert("b");
		for(tmp in response)
		{
			alert(tmp +" = "+ response[tmp] );
		}
		
	});
	*/
	var user_id = $("#facebook_userid").val();
	
	if(user_id == '') {
		window.top.location.href = '<?php echo FB_REDIRECT_URL; ?>';
	} else {
		addUserLike(href, widget);	
	}
	
	//addUserLike(href, widget);	
});

 
 FB.Event.subscribe('edge.remove', function(href, widget) {
 // Do something, e.g. track the click on the "Like" button here
 	removeUserLike(href, widget);
 });

/*FB.Event.subscribe('auth.login', function(response) {
	// Do something, e.g. track the click on the "Like" button here 	
	//removeUserLike(href, widget);
});*/
 
FB.Event.subscribe('auth.login', function(href) {
	if( $("#facebook_user_numeric_id").val() == '' ) {
		window.top.location.href = '<?php echo FB_REDIRECT_URL; ?>';
	}
}); 
 
FB.Event.subscribe('auth.authResponseChange', function(response) {
	// Do something, e.g. track the click on the "Like" button here
	//alert("authResponseChange = " + response);
	//removeUserLike(href, widget);
});
 
 
function sendRequestToManyRecipients() 
{

	$.ajax({
 	    type: "POST",
		url:site_url+"page/invitefriend",
		dataType:'html',
		success:function(data)
		{ 
			FB.ui({
				method: 'apprequests',
				message: '<?php echo $this->Translate("Invite_Friend_Send_Request_Msg"); ?>',
				exclude_ids: [data]
			}, requestCallback);
		}
	});	
	
}
  
function requestCallback(response) 
{
	if(response != null) {
		alert("<?php echo $this->Translate("Invite_Friend_Send_Request_Success_Msg"); ?>");
	}
}
 
</script>

</body>
</html>
