<div id="leftColumn">
                	<div class="widget1">
                    	<div class="ulclass">
                            <ul>
                            	<li><a href="#"><img src="<?php echo IMAGES_FB_PATH ?>/frnd_like.jpg" alt="" style="vertical-align:middle; margin-right:6px;" /><?php echo $this->Translate('YouLike')?></a></li>
                                <li><a href="#"><img src="<?php echo IMAGES_FB_PATH ?>/frnd_like.jpg" alt="" style="vertical-align:middle; margin-right:6px;" /><?php echo $this->Translate('FrndsLike')?></a></li>
                                <li class="cart_wrapper" style="border-bottom:none;"><a href="javascript:void(0)"><img src="<?php echo IMAGES_FB_PATH ?>/cart.png" alt="" style="vertical-align:middle; margin-right:6px;" /><?php echo $this->Translate('YourCart')?><span id="cartCounterNumber" class="payvmentButtonNumber" style="padding-left:5px;"><?if($this->CartCnt){?><?php echo $this->CartCnt;?><?}else{?>0<?php }?></span></a></li>
                            </ul>
                        </div>
                    </div>
                	<div align="center" style="margin-bottom:10px; margin-top:10px;">
                        <img src="<?php echo IMAGES_FB_PATH ?>/like_shoppingmall.jpg" alt="" />
                       
                    </div>
                    <div class="navCategory portlet">
                        <!--<div class="widgetHeader"> Popular Categories </div>-->
                        <div class="widgetHeader_menu"><?php echo $this->Translate('PopularCategory')?></div>
                        <ul class="sf-menu sf-vertical sf-js-enabled sf-shadow">
							<?php echo $this->Category; ?>
                        </ul>
                    </div>
                    
                    
                    <div class="clear"></div>
                    <div id="productMostLikedWidget" style="display: block;">
                        <div class="widgetHeader_menu"><?php echo $this->Translate('TopTradingLike')?></div>
                        <div class="widget">
							<?php foreach($this->frndstoplike as $val){?>
								<div class="productWidgetLineItem">
									<div class="productWidgetThumbnail">
										<div>
										<?php
											$SmallImg = explode('_',$val['image_name']);
											$tinyImage = SITE_PRODUCT_IMAGES_PATH.$val['image_path']."/".$SmallImg[0]."_th3.jpg";	
										?>
											<a href="<?php echo SITE_FB_URL?>product/view/id/<?php echo $val['product_id'];?>" target="_top">
											<?php if($val['image_name']){?>
												<img src="<?php echo $tinyImage; ?>" alt="" />
											<?php }else{?>
												<img src="<?php echo IMAGES_FB_PATH ?>/coming.jpg" alt="" />
											<?php }?>
											</a>
										</div>
									</div>
									<div class="productWidgetDesc">
									<a title="" href="<?php echo SITE_FB_URL?>product/view/id/<?php echo $val['product_id'];?>" target="_top"><?php echo $val['product_name'];?></a>
									</div>
									<div style="clear:both;"></div>
								</div>
                          <?php }?>  
                        </div>
                    </div>
                </div>