<div id="menu">
            <div class="topNav">
                <ul>
                    <li><a href="<?php echo SITE_FB_URL ?>"><?php echo $this->Translate('Home')?></a></li>
                    <li class="brands"><a href="<?php echo SITE_FB_URL ?>category/"><?php echo $this->Translate('AllCategory')?></a>
                    	<div class="shadow">
                            <div>
								<?php $record = $this->Mycategory; ?>
								<?php for($i = 0; $i<count($record); $i++ ) { ?>
									<ul>
										<?php foreach($record[$i] as $key => $val ) { ?>
											<li>
												<a href="#"><?php echo $val["category_name"]; ?></a>
											</li>	
										<?php } ?>
									</ul>
								<?php } ?>                                   
                                <p class="clear"></p>
                            </div>
                        </div>
                    </li>
                    <li><a href="#"><?php echo $this->Translate('InviteFriends')?></a></li>
                    <li><a href="<?php echo SITE_FB_URL ?>page/aboutus/"><?php echo $this->Translate('AboutUs')?></a></li>
                    <li><a href="<?php echo SITE_FB_URL ?>page/contactus/"><?php echo $this->Translate('ContactUs')?></a></li>
                 </ul>
            </div>
        </div>
        <div class="clear"></div>
		<div id="headerRowTwo">
        	<img src='<?php echo IMAGES_FB_PATH ?>/sep.jpg' alt="" />
        </div>
        <div class="clear"></div>