<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="#"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Language_Definitions'); ?></span></li>
	</ul>
</div>

<!--       Set Record value         -->
<?php  $edit_record = $this->records;  ?>

<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate('Manage_Language_Definitions'); ?>
	</div>
	
	<?php if(count($this->editErrorMessage) > 0 ) { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
				<?php foreach($this->editErrorMessage as $key => $val ) { ?>
					<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
					<strong><?php echo $val; ?></strong></p>
				<?php } ?>
			</div>
		</div>
	<?php } ?>	
	
	<form method="post" name="edit_form" id="edit_form" >
		<table class="Panel" style="margin-top:10px;">
			<tr>
				<td class="Heading2" colspan="2"><?php echo $this->Translate('Edit_Language'); ?></td>
			</tr>
			<tr>
				<td colspan="2">
				<div id="div0" style="padding-bottom:5px">
					<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Language'); ?>
							</td>
							<td>
								<select name="language_id" id="language_id">
									<?php for($i = 0; $i < count($this->languages); $i++){ ?>
										<option value="<?php echo $this->languages[$i]['language_id'] ?>" <?php echo ($this->records["language_id"] == $this->languages[$i]['language_id'] ? "selected" : ""); ?> ><?php echo $this->languages[$i]['name'] . " - " .  $this->languages[$i]['code']?></option>
									<?php } ?>
								</select>
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Group'); ?>:
							</td>
							<td>
								<select name="content_group" id="content_group">
									<option value="ADMIN" <?php echo ($this->records["content_group"] == 'ADMIN' ? "selected" : ""); ?> >ADMIN</option>
									<option value="DEFAULT" <?php echo ($this->records["content_group"] == 'DEFAULT' ? "selected" : ""); ?> >DEFAULT</option>
									<option value="USER" <?php echo ($this->records["content_group"] == 'USER' ? "selected" : ""); ?> >USER</option>
									<option value="FB" <?php echo ( $this->records['content_group'] == 'FB' ? "selected" : "" ); ?> >FB STORE</option>
								</select>
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Key'); ?>:
							</td>
							<td>
								<input type="text" name="definition_key" id="definition_key" class="Field250" value="<?php echo $this->records['definition_key']; ?>" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Value'); ?>:
							</td>
							<td>
								<input type="text" name="definition_value" id="definition_value" class="Field250" value="<?php echo $this->records['definition_value']; ?>" />
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Is_Active'); ?>:
							</td>
							<td>
								<input type="radio" name="status" class="" value="1" <?php echo ($this->records["status"] == 1 ? "checked" : ""); ?> />
								<?php echo $this->Translate('L_Yes'); ?>&nbsp;
								<input type="radio" name="status"  value="0" <?php echo ($this->records["status"] == 0 ? "checked" : ""); ?> />
								<?php echo $this->Translate('L_No'); ?>
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						<tr>
						   	<td colspan="2">
								<input type="submit" onclick="Javascript: return ValidateEditFrom()" value="<?php echo $this->Translate('Submit'); ?>" />
								<input type="button" value="<?php echo $this->Translate('Cancle'); ?>" onclick="window.location='<?php echo $this->site_url; ?>'"/>
						   </td>
						</tr>
					</table>
				</div>
				</td>
			</tr>
		</table>   
		
		<!--         Hidden fields                       -->
		<input type="hidden" name="definition_id" id="definition_id" value="<?php echo $this->definition_id; ?>" />
		
	</form>            
</div> 

<script language="javascript" type="text/javascript">
var siteurl = "<?php echo SITE_URL; ?>";
var ERR_DEFINITION_KEY = "<?php echo $this->Translate('Err_Definition_Key'); ?>";  
var ERR_DEFINITION_VALUE = "<?php echo $this->Translate('Err_Definition_Value'); ?>";  
</script>