<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="#"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Language_Definitions'); ?></span></li>
	</ul>
</div>


<div class="BodyContainer DashboardContainer" style="text-align:left;"> 
	<div class="Heading1">
		<?php echo $this->Translate('Manage_Language_Definitions'); ?>
	</div>
	
	<?php if(count($this->ErrorMessage) > 0 ) { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
				<?php foreach($this->ErrorMessage as $key => $val ) { ?>
					<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
					<strong><?php echo $val; ?></strong></p>
				<?php } ?>
			</div>
		</div>
	<?php } ?>
	
	<?php if($this->SuccessMessage != '') { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;"> 
				<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
				<strong><?php echo $this->SuccessMessage; ?></strong></p>
			</div>
		</div>
	<?php } ?>	
	
	<form method="post" name="import_form" id="import_form" enctype="multipart/form-data" >
		<table class="Panel" style="margin-top:10px;">
			<tr>
				<td class="Heading2" colspan="2"><?php echo $this->Translate('Import_Language_Definition'); ?></td>
			</tr>
			<tr>
				<td colspan="2">
				<div id="div0" style="padding-bottom:5px">
					<table class="Panel" width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Language'); ?>:
							</td>
							<td>
								<select name="language_id" id="language_id">
									<?php for($i = 0; $i < count($this->languages); $i++){ ?>
										<option value="<?php echo $this->languages[$i]['language_id'] ?>" <?php echo ($this->data["language_id"] == $this->languages[$i]['language_id'] ? "selected" : ""); ?> ><?php echo $this->languages[$i]['name'] . " - " .  $this->languages[$i]['code']?></option>
									<?php } ?>
								</select>
								<span></span>
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Definition_File'); ?>:
							</td>
							<td>
								<input type="file" name="definition_file" id="definition_file" class="Field250"  />
								<span></span>
								<div style="margin-top:10px;"><?php echo $this->Translate('Import_Upload_Text1'); ?></div>
								<div style="margin-top:10px;"><?php echo $this->Translate('Import_Upload_Text2'); ?></div>
								<div style="margin-top:10px;"><a href="<?php echo SITE_UPLOAD_FOLDER_PATH . '/language.txt'; ?>" target="_blank" ><?php echo $this->Translate('Example_File'); ?></a></div>
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						<tr>
						   	<td colspan="2">
								<input type="submit" id="anything" onclick="Javascript: return ValidateImportForm()"  value="<?php echo $this->Translate('Submit'); ?>" />
								<input type="button" id="anything"  value="<?php echo $this->Translate('Cancle'); ?>" onclick="window.location='<?php echo $this->site_url; ?>'"/>
						   </td>
						</tr>
					</table>
				</div>
				</td>
			</tr>
		</table>   
	</form>            
</div> 

<!--     JS Global Variable for the language    -->

<script language="javascript" type="text/javascript">
var siteurl = "<?php echo SITE_URL; ?>";
var ERR_DEFINITION_FILE = "<?php echo $this->Translate('Err_Definition_File'); ?>";  
</script>