<!--  Crumb  Start -->
<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="<?php echo SITE_URL; ?>admin/"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Orders'); ?></span></li>
	</ul>
</div>
<!--  Crumb  end -->


<div class="BodyContainer DashboardContainer" style="text-align:left;">
	
	
	<!--  Page Header Start  -->
	<div class="Heading1" >
		<?php echo $this->Translate('Order_Management'); ?>
	</div>
	<!--  Page Header End  -->
	
	<!--       Success and Error Message      -->	
	<?php if($this->Admin_EMessage != '') { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
				<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
				<strong><?php echo $this->Admin_EMessage; ?></strong></p>
			</div>
		</div>
	<?php } ?>	
	
	<?php if($this->Admin_SMessage != '') { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;"> 
				<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
				<strong><?php echo $this->Admin_SMessage; ?></strong></p>
			</div>
		</div>
	<?php } ?>
	
	<!--   Main Form start     -->
	<form name="frmOrders" id="frmOrders" method="post">
	
		<!--  Buttons start -->
		<div>
			<div style="float:left; margin-top:7px; margin-bottom:10px;">
				<input type="button" id="search" show='1'  value="<?php echo $this->Translate('Search'); ?>" />
			</div>
			<div id="button" style="float:right;">
				<input type="button" id="anything" onclick="Javascript: deleteAllRecords('frmOrders','<?php echo $this->delete_all_action; ?>')"  value="<?php echo $this->Translate('M_Delete'); ?>"/>	   
				<select name="pagesize" id="pagesize" onchange="this.form.submit();">
					<?php
						foreach($this->arr_pagesize as $key => $val){
							echo "<option value='".$key."'". ($key == $this->pagesize ? ' selected ' : '') ." >" . $val . "</option>";
						}
					?>
				</select>
			</div>
		</div>
		<!--  Buttons end -->
	
		<!--  Search Form start     -->
		<div class="toggler box" style="clear:both; ">
			<div id="effect" class='ui-widget-content ui-corner-all' > 					  
				<div style="padding:20px;">	
					<table class="" width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Order_Search_Product_Name'); ?>: 
							</td>
							<td style="padding-left:25px;">
								<input type="text" class="Field250" name="product_name" id="user_name" /> 
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Order_Search_User_Name'); ?>: 
							</td>
							<td style="padding-left:25px;">
								<input type="text" class="Field250" name="user_name" id="user_name" /> 
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Order_Date'); ?>: 
							</td>
							<td >
								<?php echo $this->Translate('From'); ?> 
								<input type="text" class="Field250" name="order_date_from" id="order_date_from" />&nbsp;&nbsp;
								<?php echo $this->Translate('To'); ?> 
								<input type="text" class="Field250" name="order_date_to" id="order_date_to" /> 
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Order_Status'); ?>: 
							</td>
							<td style="padding-left:25px;">
								<select name="order_status" id="order_status" class="Field250">
									<option value=""><?php echo $this->Translate('Order_Status_Select'); ?></option>
									<?php	foreach( $this->order_status["order_status"] as $key => $val ) { ?>	
									<option value="<?php echo $key; ?>"><?php 	echo $val;  ?></option>
									<?php 	}  ?>
								</select>
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						<tr>
						   <td colspan="2">
								<input type="button" id="anything"  onclick="Javascript: SearchRecords(1,'frmOrders');"  value="<?php echo $this->Translate('Search'); ?>" />
								<input type="button" id="anything"  onclick="Javascript: SearchRecords(0,'frmOrders');"  value="<?php echo $this->Translate('Clear'); ?>" />
						   </td>
						</tr>
					</table>
				</div>								
			</div>
		</div>
		<!--  Search Form end     -->
	 
		<div class="Clear"></div>				
 	
		<!--   Records list start   -->
		<div style="margin-top:-10px;" id="table1">		
			<table width="100%" cellpadding="0" cellspacing="0" style="float:left;">
				<tr style="" class="trclass">
					<td  class="tdclasshome"><?php echo $this->Translate('All'); ?></td>
                	<td  class="tdclasshome"><?php echo $this->Translate('Order_Order_No'); ?></td>
                    <td  class="tdclasshome"><?php echo $this->Translate('Order_Date'); ?></td>
                    <td   class="tdclasshome" align="center">
                    	<table width="100%" align="center" cellpadding="0" cellspacing="0" >
                        	<tr>
                            	<td colspan="2" align="center" height="18px" valign="top"  class="borderbottom" ><?php echo $this->Translate('Order_Client'); ?></td>
							</tr>
							<tr>
								<td width="50%" align="center"  class="tdclasshome"><?php echo $this->Translate('Order_SU'); ?></td>
								<td width="50%" align="center" class="style10"><?php echo $this->Translate('Order_BU'); ?></td>
							</tr>
						</table>
					</td>
					<td class="tdclasshome"><?php echo $this->Translate('Order_Amount'); ?></td>
					<td class="tdclasshome"><?php echo $this->Translate('Order_Status'); ?></td>
					<td class="tdclasshome"><?php echo $this->Translate('Action'); ?></td>
				</tr>
				
				<?php if(count($this->records) > 0 ) { ?>
				<?php 	foreach($this->records as $key => $val) { ?>
				<tr id="tr100" class="GridRow" onmouseover="this.className='GridRowOver'" onmouseout="this.className='GridRow'">
					<td class="FieldLabel2">
						<input type="checkbox" name="id[]" id="id[]" value="<?php echo $val['order_id']; ?>">
					</td>
					<td class="FieldLabel2">#<?php echo $val["order_id"]; ?></td>
					<td class="FieldLabel2"><?php echo $val["order_creation_date"]; ?></td>
					<td class="FieldLabel2">
					  <table  width="100%" cellpadding="0" cellspacing="0" align="center" >
							<tr>
								<td  width="50%" style="border-bottom:none"><?php echo $val["shipping_user_fname"]." ".$val["shipping_user_lname"]; ?></td>
								<td width="50%" style="border-bottom:none"><?php echo $val["billing_user_fname"]." ".$val["billing_user_lname"]; ?></td>
							</tr>
					  </table>
					</td>
				   	<td class="FieldLabel2"><?php echo $val["currency_symbol"]." ".$val["total_order_amount"]; ?></td>
				   	<td align="center" class="FieldLabel2">
						<?php	foreach( $this->order_status as $key1 => $val1 ) { ?>	
						
							<?php 		if($val["order_status"] == $val1["order_status_id"] ) { ?>
											<span class="OrderStatus OrderStatus<?php echo $val1["order_status_id"]; ?> OrderDetails">
												<?php echo $val1["status_value"]; ?>
											</span>								
							<?php   	} 	?>
							
						<?php 	}  ?>		
					</td>
				   	<td class="FieldLabel2">
				   		<ul id="icons" class="ui-widget ui-helper-clearfix" >
							<li onclick="Javascript: viewRecord(<?php echo $val['order_id']; ?>,'frmOrders','<?php echo $this->view_action; ?>')" class="ui-state-default ui-corner-all" title="<?php echo $this->Translate('View'); ?>">
								<span class="ui-icon ui-icon-document"></span>
							</li>
							<li class="ui-state-default ui-corner-all" onclick="Javascript: editRecord(<?php echo $val['order_id']; ?>,'frmOrders','<?php echo $this->edit_action; ?>')" title="<?php echo $this->Translate('Edit'); ?>">
								<span class="ui-icon ui-icon-pencil"></span>
							</li>
							<li onclick="Javascript: deleteRecord(<?php echo $val['order_id']; ?>,'frmOrders','<?php echo $this->delete_action; ?>')" class="ui-state-default ui-corner-all" title="<?php echo $this->Translate('Delete'); ?>">
								<span class="ui-icon ui-icon-close"></span>
							</li>
				   		</ul>
				   	</td>
				</tr>	
				<?php    }?>			
				<?php } else {  ?>
					<tr id="tr100" class="GridRow" onmouseover="this.className='GridRowOver'" onmouseout="this.className='GridRow'">
						<td class="FieldLabel2" colspan="8" align="center"><?php echo $this->Translate('No_record'); ?></td>
					</tr>
				<?php } ?>				
			</table>
			
			
			<!--  Pagination start  	 -->
			<div class="box-footer" style="background:none; border:none; float:right; margin-top:10px;">
				<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>					
			</div>
			<!--  Pagination end 		 -->
				
			<!-- 	Hidden field	-->
			<input type="hidden" name="page_no" id="page_no" value="<?php echo $this->page_no; ?>" />
			<input type="hidden" name="is_search" id="is_search" value="<?php echo $this->user_status; ?>" />
			<input type="hidden" name="hidden_primary_id" id="hidden_primary_id" value="" />

		</div>
		<!--   Records list end   -->
	
	</form>
	<!--   Main Form end   -->
	
 	<div class="Clear"></div>	              
</div>

<!--     JS Global Variable for the language    -->

<script language="javascript" type="text/javascript">
	var siteurl = "<?php echo SITE_URL; ?>";
	var HIDE = "<?php echo $this->Translate('Hide'); ?>";  
	var SEARCH = "<?php echo $this->Translate('Search'); ?>";  
	
	$(function() {
		$( "#order_date_from" ).datepicker({ dateFormat: 'yy-mm-dd' });
		$( "#order_date_to" ).datepicker({ dateFormat: 'yy-mm-dd' });
	});

</script>


<!--     Dialoag box for the delete and delete all    -->

<div id="dialog-confirm" title="<?php echo $this->Translate('Confirm_Delete_Order_Title'); ?>" style="display:none;">
	<div style="text-align:left;">
		<span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
		<?php echo $this->Translate('Confirm_Delete_Order'); ?>
	</div>
</div>

<div id="dialog-confirm2" title="<?php echo $this->Translate('Confirm_Delete_Order_Title'); ?>" style="display:none;">
	<div style="text-align:left;">
		<span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
		<?php echo $this->Translate('Confirm_M_Delete_Order'); ?>
	</div>
</div>