<!--  Crumb  Start -->
<div class="Breadcrumb" id="PageBreadcrumb">
	<ul>
	   <li class="Home SecondLast"><a href="<?php echo SITE_URL; ?>admin/"><?php echo $this->Translate("Administration"); ?></a></li>
	   <li class="Last"><span><?php echo $this->Translate('Merchants'); ?></span></li>
	</ul>
</div>
<!--  Crumb  end -->


<div class="BodyContainer DashboardContainer" style="text-align:left;">
	
	
	<!--  Page Header Start  -->
	<div class="Heading1" >
		<?php echo $this->Translate('Merchant_Management'); ?>
	</div>
	<!--  Page Header End  -->
	
	
	<!--       Success and Error Message      -->	
	<?php if($this->Admin_EMessage != '') { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
				<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
				<strong><?php echo $this->Admin_EMessage; ?></strong></p>
			</div>
		</div>
	<?php } ?>	
	
	<?php if($this->Admin_SMessage != '') { ?>	
		<div class="ui-widget" style="margin-top:10pt; width:99%;">
			<div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;"> 
				<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
				<strong><?php echo $this->Admin_SMessage; ?></strong></p>
			</div>
		</div>
	<?php } ?>
	
	
	<!--   Main Form start     -->
	<form name="frmMerchants" id="frmMerchants" method="post">
	
		<!--  Buttons start -->
		<div>
			<div style="float:left; margin-top:7px; margin-bottom:10px;">
				<input type="button" id="search" show='1'  value="<?php echo $this->Translate('Search'); ?>" />
			</div>
			<div id="button" style="float:right;">
				<input type="button" id="anything"  value="<?php echo $this->Translate('Add_New'); ?>" onclick="window.location='<?php echo SITE_URL; ?>admin/merchants/add'"/>
				<input type="button" id="anything" onclick="Javascript: deleteAllRecords('frmMerchants','<?php echo $this->delete_all_action; ?>')"  value="<?php echo $this->Translate('M_Delete'); ?>"/>	   
				<select name="pagesize" id="pagesize" onchange="this.form.submit();">
					<?php
						foreach($this->arr_pagesize as $key => $val){
							echo "<option value='".$key."'". ($key == $this->pagesize ? ' selected ' : '') ." >" . $val . "</option>";
						}
					?>
				</select>
			</div>
		</div>
		<!--  Buttons end -->
	
		<!--  Search Form start     -->
		<div class="toggler box" style="clear:both; ">
			<div id="effect" class='ui-widget-content ui-corner-all' > 					  
				<div style="padding:20px;">	
					<table class="" width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Merchant_Name'); ?>: 
							</td>
							<td>
								<input type="text" class="Field250" name="user_fname" /> 
							</td>
						</tr>
						<tr><td height="5"></td></tr>
						 <tr>
							<td class="FieldLabel">
								<?php echo $this->Translate('Is_Active'); ?>:
							</td>
							<td>
								<input type="radio" name="user_status" class="" value="1" />
								<?php echo $this->Translate('L_Yes'); ?>&nbsp;
								<input type="radio" name="user_status"  value="0" />
								<?php echo $this->Translate('L_No'); ?> 
							</td>
						</tr>
						<tr><td height="15"></td></tr>
						<tr>
						   <td colspan="2">
								<input type="button" id="anything"  onclick="Javascript: SearchRecords(1,'frmMerchants');"  value="<?php echo $this->Translate('Search'); ?>" />
								<input type="button" id="anything"  onclick="Javascript: SearchRecords(0,'frmMerchants');"  value="<?php echo $this->Translate('Clear'); ?>" />
						   </td>
						</tr>
					</table>
				</div>								
			</div>
		</div>
		<!--  Search Form end     -->
	 
		<div class="Clear"></div>				
 	
		<!--   Records list start   -->
		<div style="margin-top:-10px;" id="table1">		
			<table width="100%" cellpadding="0" cellspacing="0" style="float:left;">
				<tr class="trclass1">
					<td width="5%" class="tdclasshome" style="text-align:left; padding-left:15px;" >
						<?php echo $this->Translate('All'); ?>
					</td>
					<td width="30%" align="center" class="tdclasshome"><?php echo $this->Translate('Merchant_Name'); ?></td>
					<td width="15%" align="center" class="tdclasshome"><?php echo $this->Translate('Merchant_Email'); ?></td>
					<td width="15%" align="center" class="tdclasshome"><?php echo $this->Translate('Merchant_Creation_Date'); ?></td>
					<td width="20%" align="center" class="tdclasshome"><?php echo $this->Translate('Active'); ?></td>
					<td width="15%" align="center" class="tdclasshome bordernone"><?php echo $this->Translate('Action'); ?></td>
				</tr>	
	<?php 
				if(count($this->records) > 0) 	{ 
				
					for($i = 0; $i < count($this->records); $i++)
					{
	?>
				<tr id="tr100" class="GridRow" onmouseover="this.className='GridRowOver'" onmouseout="this.className='GridRow'">
					<td class="FieldLabel2" style="padding-left:15px;" ><input type="checkbox" name="id[]" id="id[]" value="<?php echo $this->records[$i]['user_id']; ?>"></td>
					  
					<td class="FieldLabel2" align="center"><?php echo $this->records[$i]['user_fname']; ?></td>
					<td class="FieldLabel2" align="center"><?php echo $this->records[$i]['user_email']; ?></td>
					<td class="FieldLabel2" align="center"><?php echo date('d/m/Y',strtotime($this->records[$i]['registration_date'])); ?></td>
					<td class="FieldLabel2" align="center">
	<?php 				if($this->records[$i]['user_status'])
						{
							echo $this->Translate('L_Yes');
						}
						else
						{
							echo $this->Translate('L_No');
						} 
	?>		
					</td>
					<td class="FieldLabel2" align="center">
						<ul id="icons" class="ui-widget ui-helper-clearfix" >
							<li class="ui-state-default ui-corner-all" onclick="Javascript: editRecord(<?php echo $this->records[$i]['user_id']; ?>,'frmMerchants','<?php echo $this->edit_action; ?>')" title="<?php echo $this->Translate('Edit'); ?>">
								<span class="ui-icon ui-icon-pencil"></span>
							</li>
							<li onclick="Javascript: deleteRecord(<?php echo $this->records[$i]['user_id']; ?>,'frmMerchants','<?php echo $this->delete_action; ?>')" class="ui-state-default ui-corner-all" title="<?php echo $this->Translate('Delete'); ?>">
								<span class="ui-icon ui-icon-close"></span>
							</li>
						</ul>
					</td>
				</tr>
	<?php 		}
			}	
			else {  	?>
				<tr id="tr100" class="GridRow" onmouseover="this.className='GridRowOver'" onmouseout="this.className='GridRow'">
					<td class="FieldLabel2" colspan="6" align="center"><?php echo $this->Translate('No_record'); ?></td>
				</tr>
	<?php 		 } 		?>				
			
			</table>
			
			
			
			<!--  Pagination start  	 -->
			<div class="box-footer" style="background:none; border:none; float:right; margin-top:10px;">
					<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>					
			</div>
			<!--  Pagination end 		 -->
				
			<!-- 	Hidden field	-->
			<input type="hidden" name="page_no" id="page_no" value="<?php echo $this->page_no; ?>" />
			<input type="hidden" name="is_search" id="is_search" value="<?php echo $this->user_status; ?>" />
			<input type="hidden" name="hidden_primary_id" id="hidden_primary_id" value="" />

		</div>
		<!--   Records list end   -->
	
	</form>
	<!--   Main Form end   -->
	
 	<div class="Clear"></div>	              
</div>

<!--     JS Global Variable for the language    -->

<script language="javascript" type="text/javascript">
	var siteurl = "<?php echo SITE_URL; ?>";
	var HIDE = "<?php echo $this->Translate('Hide'); ?>";  
	var SEARCH = "<?php echo $this->Translate('Search'); ?>";  
	var ERR_MERCHANTS_FNAME = "<?php echo $this->Translate('Err_Merchant_FName'); ?>";  
	var ERR_MERCHANTS_LNAME = "<?php echo $this->Translate('Err_Merchant_LName'); ?>";  
	var ERR_MERCHANTS_EMAIL = "<?php echo $this->Translate('Err_Merchant_Email'); ?>";
	var ERR_MERCHANTS_INVALID_EMAIL = "<?php echo $this->Translate('Err_Merchant_Invalid_Email'); ?>";
	var ERR_MERCHANTS_PASSWORD = "<?php echo $this->Translate('Err_Merchant_Password'); ?>";
	var ERR_MERCHANTS_PASSWORD_MIN_MAX = "<?php echo $this->Translate('Err_Merchant_Password_Min_Max'); ?>";
	var ERR_MERCHANTS_FB = "<?php echo $this->Translate('Err_Merchant_FB'); ?>";
	var ERR_USER_STATUS = "<?php echo $this->Translate('Err_user_status'); ?>" ; 
</script>

<!--     Dialoag box for the delete and delete all    -->

<div id="dialog-confirm" title="<?php echo $this->Translate('Confirm_Delete_Merchant_Title'); ?>" style="display:none;">
	<div style="text-align:left;">
		<span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
		<?php echo $this->Translate('Confirm_Delete_Merchant'); ?>
	</div>
</div>

<div id="dialog-confirm2" title="<?php echo $this->Translate('Confirm_Delete_Merchant_Title'); ?>" style="display:none;">
	<div style="text-align:left;">
		<span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
		<?php echo $this->Translate('Confirm_M_Delete_Merchant'); ?>
	</div>
</div>